// words.js - 英検3級 頻出単語・熟語データ (第1批: 1~250)
// データソース：旺文社《予想問題ドリル》、《集中ゼミ》、《でる順パス単》
// 優先度：実戦でよく出る熟語 ＞ コア動詞 ＞ 頻出名詞

const vocabData = [
    // =============== 【1. 英検3級 必修熟語 (超重要！会話・穴埋め問題)】 ===============
    { en: "a lot of", jp: "たくさんの", enSent: "I have a lot of books.", jpSent: "私はたくさんの本を持っています。" },
    { en: "after school", jp: "放課後", enSent: "Let's play after school.", jpSent: "放課後に遊びましょう。" },
    { en: "agree with", jp: "〜に賛成する", enSent: "I agree with you.", jpSent: "私はあなたに賛成です。" },
    { en: "all over the world", jp: "世界中で", enSent: "Cats live all over the world.", jpSent: "猫は世界中に住んでいます。" },
    { en: "arrive at", jp: "〜に到着する", enSent: "We arrived at the station.", jpSent: "私たちは駅に到着しました。" },
    { en: "as soon as", jp: "〜するとすぐに", enSent: "Call me as soon as you can.", jpSent: "できるだけ早く電話してください。" },
    { en: "ask for", jp: "〜を求める", enSent: "He asked for water.", jpSent: "彼は水を求めました。" },
    { en: "at first", jp: "最初は", enSent: "At first, I was sad.", jpSent: "最初は悲しかったです。" },
    { en: "at last", jp: "ついに", enSent: "At last, we won.", jpSent: "ついに私たちは勝ちました。" },
    { en: "at once", jp: "すぐに", enSent: "Come here at once.", jpSent: "すぐにここに来なさい。" },
    { en: "be afraid of", jp: "〜を恐れる", enSent: "I am afraid of dogs.", jpSent: "私は犬が怖いです。" },
    { en: "be angry with", jp: "〜に怒っている", enSent: "My mother is angry with me.", jpSent: "母は私に怒っています。" },
    { en: "be born", jp: "生まれる", enSent: "I was born in Tokyo.", jpSent: "私は東京で生まれました。" },
    { en: "be covered with", jp: "〜で覆われている", enSent: "The car is covered with snow.", jpSent: "車は雪で覆われています。" },
    { en: "be famous for", jp: "〜で有名である", enSent: "Japan is famous for sushi.", jpSent: "日本は寿司で有名です。" },
    { en: "be filled with", jp: "〜で満たされている", enSent: "The box is filled with toys.", jpSent: "その箱はおもちゃでいっぱいです。" },
    { en: "be fond of", jp: "〜が好きである", enSent: "I am fond of music.", jpSent: "私は音楽が好きです。" },
    { en: "be full of", jp: "〜でいっぱいである", enSent: "The room is full of people.", jpSent: "部屋は人でいっぱいです。" },
    { en: "be glad to", jp: "〜して嬉しい", enSent: "I am glad to see you.", jpSent: "あなたに会えて嬉しいです。" },
    { en: "be going to", jp: "〜するつもりだ", enSent: "I am going to study.", jpSent: "私は勉強するつもりです。" },
    { en: "be good at", jp: "〜が得意である", enSent: "He is good at soccer.", jpSent: "彼はサッカーが得意です。" },
    { en: "be in time for", jp: "〜に間に合う", enSent: "I was in time for the bus.", jpSent: "バスに間に合いました。" },
    { en: "be interested in", jp: "〜に興味がある", enSent: "I am interested in science.", jpSent: "私は科学に興味があります。" },
    { en: "be late for", jp: "〜に遅れる", enSent: "Don't be late for school.", jpSent: "学校に遅れないでください。" },
    { en: "be made of", jp: "〜で作られている", enSent: "This desk is made of wood.", jpSent: "この机は木で作られています。" },
    { en: "be proud of", jp: "〜を誇りに思う", enSent: "I am proud of you.", jpSent: "あなたを誇りに思います。" },
    { en: "be ready for", jp: "〜の準備ができている", enSent: "I am ready for the test.", jpSent: "テストの準備はできています。" },
    { en: "be sorry for", jp: "〜をすまなく思う", enSent: "I am sorry for the mistake.", jpSent: "間違いを申し訳なく思います。" },
    { en: "be surprised at", jp: "〜に驚く", enSent: "I was surprised at the news.", jpSent: "そのニュースに驚きました。" },
    { en: "belong to", jp: "〜に属する", enSent: "This bag belongs to me.", jpSent: "このカバンは私のものです。" },
    { en: "by the way", jp: "ところで", enSent: "By the way, how are you?", jpSent: "ところで、元気ですか？" },
    { en: "call back", jp: "電話をかけ直す", enSent: "I will call back later.", jpSent: "後で電話をかけ直します。" },
    { en: "catch a cold", jp: "風邪をひく", enSent: "I caught a bad cold.", jpSent: "ひどい風邪をひきました。" },
    { en: "catch up with", jp: "〜に追いつく", enSent: "I will catch up with you.", jpSent: "すぐに追いつきます。" },
    { en: "come from", jp: "〜の出身である", enSent: "I come from Japan.", jpSent: "私は日本出身です。" },
    { en: "come true", jp: "実現する", enSent: "Your dream will come true.", jpSent: "あなたの夢は実現するでしょう。" },
    { en: "cut off", jp: "切り取る", enSent: "He cut off a piece of paper.", jpSent: "彼は紙を一枚切り取りました。" },
    { en: "depend on", jp: "〜に頼る / 次第である", enSent: "It depends on you.", jpSent: "それはあなた次第です。" },
    { en: "do one's best", jp: "最善を尽くす", enSent: "I will do my best.", jpSent: "私は最善を尽くします。" },
    { en: "do well", jp: "うまくやる", enSent: "She did well on the test.", jpSent: "彼女はテストでうまくやりました。" },
    { en: "excuse me", jp: "すみません", enSent: "Excuse me, where is the station?", jpSent: "すみません、駅はどこですか？" },
    { en: "fall down", jp: "転ぶ / 倒れる", enSent: "The old tree fell down.", jpSent: "古い木が倒れました。" },
    { en: "far away", jp: "遠く離れて", enSent: "He lives far away.", jpSent: "彼は遠く離れたところに住んでいます。" },
    { en: "far from", jp: "〜から遠い", enSent: "My house is far from here.", jpSent: "私の家はここから遠いです。" },
    { en: "find out", jp: "見つけ出す / 知る", enSent: "I found out the answer.", jpSent: "私は答えを見つけました。" },
    { en: "for a long time", jp: "長い間", enSent: "I waited for a long time.", jpSent: "私は長い間待ちました。" },
    { en: "for example", jp: "例えば", enSent: "I like pets, for example, dogs.", jpSent: "私はペットが好きです、例えば犬など。" },
    { en: "for the first time", jp: "初めて", enSent: "I met him for the first time.", jpSent: "彼に初めて会いました。" },
    { en: "get along with", jp: "〜と仲良くする", enSent: "I get along with my brother.", jpSent: "私は兄と仲良くしています。" },
    { en: "get angry", jp: "怒る", enSent: "He got angry at me.", jpSent: "彼は私に怒りました。" },
    { en: "get back", jp: "戻る", enSent: "I got back home at six.", jpSent: "私は6時に家に戻りました。" },
    { en: "get lost", jp: "道に迷う", enSent: "Don't get lost.", jpSent: "道に迷わないで。" },
    { en: "get off", jp: "（バス・電車から）降りる", enSent: "Let's get off the train.", jpSent: "電車を降りましょう。" },
    { en: "get on", jp: "（バス・電車に）乗る", enSent: "He got on the bus.", jpSent: "彼はバスに乗りました。" },
    { en: "get out of", jp: "〜から外へ出る", enSent: "Get out of the room.", jpSent: "部屋から出なさい。" },
    { en: "get to", jp: "〜に到着する", enSent: "How can I get to the park?", jpSent: "どうすれば公園に着きますか？" },
    { en: "get up", jp: "起きる", enSent: "I get up early.", jpSent: "私は早く起きます。" },
    { en: "get well", jp: "良くなる / 回復する", enSent: "I hope you get well soon.", jpSent: "早く良くなることを願っています。" },
    { en: "give up", jp: "諦める", enSent: "Never give up.", jpSent: "決して諦めないでください。" },
    { en: "go away", jp: "立ち去る", enSent: "Please go away.", jpSent: "どこかへ行ってください。" },
    { en: "go back", jp: "戻る", enSent: "I must go back now.", jpSent: "もう戻らなければなりません。" },
    { en: "go straight", jp: "まっすぐ行く", enSent: "Go straight down this street.", jpSent: "この道をまっすぐ行きなさい。" },
    { en: "go to bed", jp: "寝る", enSent: "I go to bed at ten.", jpSent: "私は10時に寝ます。" },
    { en: "grow up", "jp": "成長する / 大人になる", "enSent": "He grew up in America.", "jpSent": "彼はアメリカで育ちました。" },
    { en: "have to", jp: "〜しなければならない", enSent: "I have to do my homework.", jpSent: "宿題をしなければなりません。" },
    { en: "hear from", jp: "〜から連絡がある", enSent: "Did you hear from her?", jpSent: "彼女から連絡はありましたか？" },
    { en: "help A with B", jp: "AのBを手伝う", enSent: "I help my mother with cooking.", jpSent: "母の料理を手伝います。" },
    { en: "hold on", jp: "電話を切らずに待つ", enSent: "Hold on, please.", jpSent: "（電話で）少々お待ちください。" },
    { en: "hurry up", jp: "急ぐ", enSent: "Hurry up!", jpSent: "急いで！" },
    { en: "in front of", jp: "〜の前に", enSent: "A cat is in front of the door.", jpSent: "ドアの前に猫がいます。" },
    { en: "in the future", jp: "将来", enSent: "I want to be a pilot in the future.", jpSent: "将来パイロットになりたいです。" },
    { en: "keep a diary", jp: "日記をつける", enSent: "I keep a diary every day.", jpSent: "私は毎日日記をつけています。" },
    { en: "laugh at", jp: "〜を笑う", enSent: "Don't laugh at him.", jpSent: "彼を笑わないでください。" },
    { en: "listen to", jp: "〜を聞く", enSent: "Listen to the music.", jpSent: "音楽を聴きなさい。" },
    { en: "look after", jp: "〜の世話をする", enSent: "I look after my sister.", jpSent: "私は妹の世話をします。" },
    { en: "look around", jp: "見回す", enSent: "Look around the room.", jpSent: "部屋を見回してください。" },
    { en: "look at", jp: "〜を見る", enSent: "Look at the sky.", jpSent: "空を見てください。" },
    { en: "look for", jp: "〜を探す", enSent: "I am looking for my pen.", jpSent: "私はペンを探しています。" },
    { en: "look forward to", jp: "〜を楽しみにする", enSent: "I look forward to Sunday.", jpSent: "日曜日を楽しみにしています。" },
    { en: "look like", jp: "〜のように見える", enSent: "It looks like an apple.", jpSent: "それはりんごのように見えます。" },

    // =============== 【2. 英検3級 超高頻出動詞】 ===============
    { en: "accept", jp: "受け入れる", enSent: "Please accept my gift.", jpSent: "私の贈り物を受け取ってください。" },
    { en: "act", jp: "行動する / 演じる", enSent: "He acts like a hero.", jpSent: "彼はヒーローのように振る舞います。" },
    { en: "add", jp: "加える", enSent: "Add water to the cup.", jpSent: "コップに水を加えてください。" },
    { en: "advise", jp: "忠告する", enSent: "My father advised me.", jpSent: "父が私に忠告しました。" },
    { en: "allow", jp: "許す", enSent: "He allowed me to go.", jpSent: "彼は私が行くのを許してくれました。" },
    { en: "answer", jp: "答える", enSent: "Answer my question.", jpSent: "私の質問に答えてください。" },
    { en: "apologize", jp: "謝る", enSent: "I apologize to you.", jpSent: "あなたに謝ります。" },
    { en: "appear", jp: "現れる", enSent: "A bear appeared.", jpSent: "熊が現れました。" },
    { en: "arrive", jp: "到着する", enSent: "The bus arrived.", jpSent: "バスが到着しました。" },
    { en: "ask", jp: "尋ねる / 頼む", enSent: "Can I ask a question?", jpSent: "質問してもいいですか？" },
    { en: "bake", jp: "焼く", enSent: "She bakes cookies.", jpSent: "彼女はクッキーを焼きます。" },
    { en: "bark", jp: "吠える", enSent: "The dog is barking.", jpSent: "犬が吠えています。" },
    { en: "beat", jp: "打ち負かす", enSent: "We beat their team.", jpSent: "私たちは彼らのチームに勝ちました。" },
    { en: "become", jp: "〜になる", enSent: "I want to become a teacher.", jpSent: "私は先生になりたいです。" },
    { en: "begin", jp: "始める", enSent: "The game will begin soon.", jpSent: "試合はすぐに始まります。" },
    { en: "believe", jp: "信じる", enSent: "I believe you.", jpSent: "私はあなたを信じます。" },
    { en: "belong", jp: "属する", enSent: "It belongs to me.", jpSent: "それは私のものです。" },
    { en: "borrow", jp: "借りる", enSent: "Can I borrow this book?", jpSent: "この本を借りてもいいですか？" },
    { en: "break", jp: "壊す", enSent: "Don't break the window.", jpSent: "窓を壊さないでください。" },
    { en: "bring", jp: "持ってくる", enSent: "Bring your notebook.", jpSent: "ノートを持ってきてください。" },
    { en: "build", jp: "建てる", enSent: "They built a new house.", jpSent: "彼らは新しい家を建てました。" },
    { en: "burn", jp: "燃える / 燃やす", enSent: "The paper is burning.", jpSent: "紙が燃えています。" },
    { en: "buy", jp: "買う", enSent: "I bought a new shirt.", jpSent: "私は新しいシャツを買いました。" },
    { en: "call", jp: "呼ぶ / 電話する", enSent: "Call me tonight.", jpSent: "今夜電話してください。" },
    { en: "care", jp: "気にする", enSent: "I don't care.", jpSent: "気にしません。" },
    { en: "carry", jp: "運ぶ", enSent: "Can you carry this bag?", jpSent: "このカバンを運べますか？" },
    { en: "catch", jp: "捕まえる", enSent: "Catch the ball.", jpSent: "ボールを捕まえて。" },
    { en: "cause", jp: "引き起こす", enSent: "What caused the fire?", jpSent: "何が火事を引き起こしたのですか？" },
    { en: "change", jp: "変える", enSent: "Change your clothes.", jpSent: "服を着替えなさい。" },
    { en: "check", jp: "確かめる", enSent: "Check your answers.", jpSent: "答えを確かめなさい。" },
    { en: "cheer", jp: "応援する", enSent: "We cheered for him.", jpSent: "私たちは彼を応援しました。" },
    { en: "choose", jp: "選ぶ", enSent: "Choose one card.", jpSent: "カードを一枚選んでください。" },
    { en: "clean", jp: "掃除する", enSent: "Clean your room.", jpSent: "部屋を掃除しなさい。" },
    { en: "clear", jp: "片付ける / 晴れる", enSent: "Clear the table.", jpSent: "テーブルを片付けてください。" },
    { en: "climb", jp: "登る", enSent: "He climbed the tree.", jpSent: "彼は木に登りました。" },
    { en: "close", jp: "閉める", enSent: "Close the door.", jpSent: "ドアを閉めてください。" },
    { en: "collect", jp: "集める", enSent: "He collects stamps.", jpSent: "彼は切手を集めています。" },
    { en: "come", jp: "来る", enSent: "Please come here.", jpSent: "ここに来てください。" },
    { en: "cook", jp: "料理する", enSent: "My father cooks well.", jpSent: "父は料理が上手です。" },
    { en: "copy", jp: "写す / コピーする", enSent: "Don't copy his homework.", jpSent: "彼の宿題を写さないでください。" },
    { en: "cost", jp: "費用がかかる", enSent: "It costs 10 dollars.", jpSent: "それは10ドルかかります。" },
    { en: "count", jp: "数える", enSent: "Count the apples.", jpSent: "りんごを数えてください。" },
    { en: "cover", jp: "覆う", enSent: "Cover it with a cloth.", jpSent: "それを布で覆ってください。" },
    { en: "cross", jp: "横切る", enSent: "Cross the bridge.", jpSent: "橋を渡ってください。" },
    { en: "cry", jp: "泣く", enSent: "The baby is crying.", jpSent: "赤ちゃんが泣いています。" },
    { en: "cut", jp: "切る", enSent: "Cut the cake.", jpSent: "ケーキを切ってください。" },
    { en: "dance", jp: "踊る", enSent: "Let's dance together.", jpSent: "一緒に踊りましょう。" },
    { en: "decide", jp: "決める", enSent: "I decided to go.", jpSent: "私は行くことに決めました。" },
    { en: "depend", jp: "頼る", enSent: "You can depend on me.", jpSent: "私を頼りにしていいですよ。" },
    { en: "die", jp: "死ぬ", enSent: "The flower died.", jpSent: "花が枯れました。" },
    { en: "differ", jp: "異なる", enSent: "It differs from this one.", jpSent: "それはこれとは異なります。" },
    { en: "dig", jp: "掘る", enSent: "Dig a hole.", jpSent: "穴を掘りなさい。" },
    { en: "discover", jp: "発見する", enSent: "He discovered a star.", jpSent: "彼は星を発見しました。" },
    { en: "do", jp: "する", enSent: "Do your homework.", jpSent: "宿題をしなさい。" },
    { en: "draw", jp: "描く", enSent: "Draw a picture.", jpSent: "絵を描いてください。" },
    { en: "dream", jp: "夢を見る", enSent: "I dreamed of you.", jpSent: "あなたの夢を見ました。" },
    { en: "drink", jp: "飲む", enSent: "Drink some water.", jpSent: "水を飲みなさい。" },
    { en: "drive", jp: "運転する", enSent: "He drives a blue car.", jpSent: "彼は青い車を運転します。" },
    { en: "drop", jp: "落とす", enSent: "Don't drop the glass.", jpSent: "グラスを落とさないでください。" },
    { en: "dry", jp: "乾かす", enSent: "Dry your hair.", jpSent: "髪を乾かしなさい。" },
    { en: "earn", jp: "稼ぐ", enSent: "He earns money.", jpSent: "彼はお金を稼ぎます。" },
    { en: "eat", jp: "食べる", enSent: "I eat an apple.", jpSent: "私はりんごを食べます。" },
    { en: "enjoy", jp: "楽しむ", enSent: "Enjoy your trip.", jpSent: "旅行を楽しんでください。" },
    { en: "enter", jp: "入る", enSent: "Enter the room.", jpSent: "部屋に入りなさい。" },
    { en: "excuse", jp: "許す", enSent: "Excuse me.", jpSent: "すみません（許してください）。" },
    { en: "expect", jp: "期待する", enSent: "I expect good news.", jpSent: "良い知らせを期待しています。" },
    { en: "explain", jp: "説明する", enSent: "Explain it to me.", jpSent: "私にそれを説明してください。" },
    { en: "fail", jp: "失敗する", enSent: "He failed the test.", jpSent: "彼はテストに失敗しました。" },
    { en: "fall", jp: "落ちる", enSent: "The apple fell.", jpSent: "りんごが落ちました。" },
    { en: "feed", jp: "エサをやる", enSent: "Feed the cat.", jpSent: "猫にエサをやってください。" },
    { en: "feel", jp: "感じる", enSent: "I feel cold.", jpSent: "寒く感じます。" },
    { en: "fight", jp: "戦う", enSent: "Don't fight.", jpSent: "喧嘩しないで。" },
    { en: "fill", jp: "満たす", enSent: "Fill the cup.", jpSent: "コップを満たしてください。" },
    { en: "find", jp: "見つける", enSent: "I found my key.", jpSent: "鍵を見つけました。" },
    { en: "finish", jp: "終える", enSent: "Finish your meal.", jpSent: "食事を終えなさい。" },
    { en: "fit", jp: "合う", enSent: "This shirt fits me.", jpSent: "このシャツは私にぴったりです。" },
    { en: "fly", jp: "飛ぶ", enSent: "Birds fly.", jpSent: "鳥は飛びます。" },
    { en: "follow", jp: "ついて行く", enSent: "Follow me.", jpSent: "私についてきて。" },
    { en: "forget", jp: "忘れる", enSent: "Don't forget.", jpSent: "忘れないで。" },
    { en: "forgive", jp: "許す", enSent: "Please forgive me.", jpSent: "私を許してください。" },
    { en: "gather", jp: "集まる / 集める", enSent: "People gathered here.", jpSent: "人々がここに集まりました。" },

    // =============== 【3. 英検3級 超高頻出名詞】 ===============
    { en: "accident", jp: "事故", enSent: "I saw an accident.", jpSent: "私は事故を見ました。" },
    { en: "address", jp: "住所", enSent: "Tell me your address.", jpSent: "住所を教えてください。" },
    { en: "adult", jp: "大人", enSent: "He is an adult.", jpSent: "彼は大人です。" },
    { en: "advice", jp: "助言", enSent: "I need your advice.", jpSent: "あなたの助言が必要です。" },
    { en: "afternoon", jp: "午後", enSent: "Let's meet this afternoon.", jpSent: "今日の午後に会いましょう。" },
    { en: "age", jp: "年齢", enSent: "What is his age?", jpSent: "彼の年齢はいくつですか？" },
    { en: "air", jp: "空気", enSent: "The air is clean.", jpSent: "空気がきれいです。" },
    { en: "airplane", jp: "飛行機", enSent: "I like airplanes.", jpSent: "私は飛行機が好きです。" },
    { en: "airport", jp: "空港", enSent: "We went to the airport.", jpSent: "私たちは空港に行きました。" },
    { en: "animal", jp: "動物", enSent: "Lions are wild animals.", jpSent: "ライオンは野生動物です。" },
    { en: "answer", jp: "答え", enSent: "Write the answer.", jpSent: "答えを書きなさい。" },
    { en: "apartment", jp: "アパート", enSent: "He lives in an apartment.", jpSent: "彼はアパートに住んでいます。" },
    { en: "apple", jp: "りんご", enSent: "I eat an apple.", jpSent: "私はりんごを食べます。" },
    { en: "area", jp: "地域", enSent: "This area is quiet.", jpSent: "この地域は静かです。" },
    { en: "arm", jp: "腕", enSent: "My arm hurts.", jpSent: "腕が痛いです。" },
    { en: "art", jp: "芸術", enSent: "I love art.", jpSent: "私は芸術が大好きです。" },
    { en: "aunt", jp: "おば", enSent: "She is my aunt.", jpSent: "彼女は私のおばです。" },
    { en: "autumn", jp: "秋", enSent: "Autumn is cool.", jpSent: "秋は涼しいです。" },
    { en: "baby", jp: "赤ちゃん", enSent: "The baby is sleeping.", jpSent: "赤ちゃんが寝ています。" },
    { en: "back", jp: "背中 / 後ろ", enSent: "My back hurts.", jpSent: "背中が痛いです。" },
    { en: "bag", jp: "カバン", enSent: "This is my bag.", jpSent: "これは私のカバンです。" },
    { en: "ball", jp: "ボール", enSent: "Throw the ball.", jpSent: "ボールを投げて。" },
    { en: "band", jp: "バンド / 楽団", enSent: "They have a band.", jpSent: "彼らはバンドを組んでいます。" },
    { en: "bank", jp: "銀行", enSent: "I went to the bank.", jpSent: "私は銀行に行きました。" },
    { en: "bath", jp: "お風呂", enSent: "I take a bath.", jpSent: "私はお風呂に入ります。" },
    { en: "beach", jp: "浜辺", enSent: "We ran on the beach.", jpSent: "私たちは浜辺を走りました。" },
    { en: "bear", jp: "熊", enSent: "I saw a bear.", jpSent: "私は熊を見ました。" },
    { en: "beauty", jp: "美しさ", enSent: "The beauty of the mountain.", jpSent: "その山の美しさ。" },
    { en: "bed", jp: "ベッド", enSent: "Go to bed.", jpSent: "ベッドに行きなさい（寝なさい）。" },
    { en: "beef", jp: "牛肉", enSent: "I like beef.", jpSent: "私は牛肉が好きです。" },
    { en: "bell", jp: "ベル / 鐘", enSent: "The bell rang.", jpSent: "ベルが鳴りました。" },
    { en: "bicycle", jp: "自転車", enSent: "I ride a bicycle.", jpSent: "私は自転車に乗ります。" },
    { en: "bird", jp: "鳥", enSent: "A bird is singing.", jpSent: "鳥が歌っています。" },
    { en: "birth", jp: "誕生", enSent: "The birth of a baby.", jpSent: "赤ちゃんの誕生。" },
    { en: "birthday", jp: "誕生日", enSent: "Happy birthday!", jpSent: "お誕生日おめでとう！" },
    { en: "blood", jp: "血", enSent: "Blood is red.", jpSent: "血は赤いです。" },
    { en: "boat", jp: "ボート", enSent: "Look at the boat.", jpSent: "あのボートを見て。" },
    { en: "body", jp: "体", enSent: "Move your body.", jpSent: "体を動かして。" },
    { en: "bone", jp: "骨", enSent: "A dog likes bones.", jpSent: "犬は骨が好きです。" },
    { en: "book", jp: "本", enSent: "Read this book.", jpSent: "この本を読みなさい。" },
    { en: "boss", jp: "上司", enSent: "He is my boss.", jpSent: "彼は私の上司です。" },
    { en: "bottom", jp: "底", enSent: "The bottom of the sea.", jpSent: "海の底。" },
    { en: "box", jp: "箱", enSent: "Open the box.", jpSent: "その箱を開けて。" },
    { en: "boy", jp: "男の子", enSent: "He is a tall boy.", jpSent: "彼は背の高い男の子です。" },
    { en: "brain", jp: "脳", enSent: "Use your brain.", jpSent: "頭（脳）を使いなさい。" },
    { en: "branch", jp: "枝", enSent: "A bird is on the branch.", jpSent: "鳥が枝にいます。" },
    { en: "bread", jp: "パン", enSent: "I eat bread.", jpSent: "私はパンを食べます。" },
    { en: "break", jp: "休憩", enSent: "Take a short break.", jpSent: "短い休憩を取りなさい。" },
    { en: "breakfast", jp: "朝食", enSent: "I eat breakfast.", jpSent: "私は朝食を食べます。" },
    { en: "bridge", jp: "橋", enSent: "Cross the bridge.", jpSent: "橋を渡ってください。" },
    { en: "brother", jp: "兄弟", enSent: "He is my brother.", jpSent: "彼は私の兄弟です。" },
    { en: "building", jp: "建物", enSent: "It is a tall building.", jpSent: "それは高い建物です。" },
    { en: "bus", jp: "バス", enSent: "We take a bus.", jpSent: "私たちはバスに乗ります。" },
    { en: "business", jp: "仕事 / 商売", enSent: "He is on business.", jpSent: "彼は仕事中です。" },
    { en: "butter", jp: "バター", enSent: "I like butter.", jpSent: "私はバターが好きです。" },
    { en: "button", jp: "ボタン", enSent: "Push the button.", jpSent: "ボタンを押してください。" },
    { en: "calendar", jp: "カレンダー", enSent: "Look at the calendar.", jpSent: "カレンダーを見て。" },
    { en: "camera", jp: "カメラ", enSent: "I bought a camera.", jpSent: "私はカメラを買いました。" },
    { en: "camp", jp: "キャンプ", enSent: "Let's go to the camp.", jpSent: "キャンプに行きましょう。" },
    { en: "cap", jp: "帽子", enSent: "Put on your cap.", jpSent: "帽子をかぶりなさい。" },
    { en: "capital", jp: "首都", enSent: "Tokyo is the capital.", jpSent: "東京は首都です。" },
    { en: "captain", jp: "キャプテン", enSent: "He is the captain.", jpSent: "彼がキャプテンです。" },
    { en: "car", jp: "車", enSent: "He drives a car.", jpSent: "彼は車を運転します。" },
    { en: "card", jp: "カード", enSent: "Pick a card.", jpSent: "カードを引いて。" },
    { en: "care", jp: "世話", enSent: "Take care of it.", jpSent: "それの世話をしてください。" },
    { en: "case", jp: "場合 / 箱", enSent: "In this case, wait.", jpSent: "この場合は、待ってください。" },
    { en: "cat", jp: "猫", enSent: "I have a cat.", jpSent: "私は猫を飼っています。" },
    { en: "center", jp: "中心", enSent: "Go to the center.", jpSent: "中心に行きなさい。" },
    { en: "century", jp: "世紀", enSent: "This is the 21st century.", jpSent: "今は21世紀です。" },
    { en: "chair", jp: "椅子", enSent: "Sit on the chair.", jpSent: "椅子に座りなさい。" },
    { en: "chance", jp: "チャンス / 機会", enSent: "This is a good chance.", jpSent: "これは良いチャンスです。" },
    { en: "change", jp: "おつり / 変化", enSent: "Keep the change.", jpSent: "おつりは取っておいて。" },
    { en: "character", jp: "キャラクター / 登場人物", enSent: "I like this character.", jpSent: "私はこのキャラクターが好きです。" },
    { en: "check", jp: "小切手 / 確認", enSent: "Can I pay by check?", jpSent: "小切手で払えますか？" },
    { en: "child", jp: "子供", enSent: "He is a child.", jpSent: "彼は子供です。" },
    { en: "choice", jp: "選択", enSent: "Make your choice.", jpSent: "選択してください。" },
    { en: "church", jp: "教会", enSent: "We go to church.", jpSent: "私たちは教会に行きます。" },
    { en: "circle", jp: "円", enSent: "Draw a circle.", jpSent: "円を描いてください。" },
    { en: "citizen", jp: "市民", enSent: "He is a good citizen.", jpSent: "彼は良い市民です。" },
    { en: "city", jp: "都市 / 市", enSent: "Tokyo is a big city.", jpSent: "東京は大きな都市です。" },
    { en: "class", jp: "クラス / 授業", enSent: "I have a math class.", jpSent: "私は数学の授業があります。" },
    { en: "classmate", jp: "同級生", enSent: "He is my classmate.", jpSent: "彼は私の同級生です。" },
    { en: "clerk", jp: "店員", enSent: "Ask the clerk.", jpSent: "店員に聞いてください。" },
    { en: "climate", jp: "気候", enSent: "The climate is warm.", jpSent: "気候は暖かいです。" },
    { en: "clock", jp: "時計", enSent: "Look at the clock.", jpSent: "時計を見て。" },
    { en: "clothes", jp: "服", enSent: "Wash your clothes.", jpSent: "服を洗いなさい。" },
    { en: "cloud", jp: "雲", enSent: "There are many clouds.", jpSent: "たくさんの雲があります。" },
    { en: "club", jp: "クラブ / 部", enSent: "Join the tennis club.", jpSent: "テニス部に入りなさい。" },
    { en: "coast", jp: "海岸", enSent: "We walked on the coast.", jpSent: "私たちは海岸を歩きました。" },
	
	
	    // =============== 【4. 英検3級 超高頻出動詞 (続き)・形容詞・副詞】 ===============
    { en: "happen", jp: "起こる", enSent: "What happened?", jpSent: "何が起こりましたか？" },
    { en: "hear", jp: "聞こえる", enSent: "I can hear the bird.", jpSent: "鳥の鳴き声が聞こえます。" },
    { en: "help", jp: "手伝う", enSent: "Can you help me?", jpSent: "手伝ってくれますか？" },
    { en: "hit", jp: "打つ", enSent: "He hit the ball.", jpSent: "彼はボールを打ちました。" },
    { en: "hold", jp: "持つ / 開催する", enSent: "Hold my hand.", jpSent: "私の手を握って。" },
    { en: "hope", jp: "望む", enSent: "I hope so.", jpSent: "そうだといいですね。" },
    { en: "hurry", jp: "急ぐ", enSent: "Hurry up!", jpSent: "急いで！" },
    { en: "hurt", jp: "傷つける", enSent: "My leg hurts.", jpSent: "足が痛いです。" },
    { en: "invite", jp: "招待する", enSent: "I invited him to the party.", jpSent: "私は彼をパーティーに招待しました。" },
    { en: "join", jp: "参加する", enSent: "Let's join the club.", jpSent: "クラブに参加しましょう。" },
    { en: "jump", jp: "跳ぶ", enSent: "The frog jumped.", jpSent: "カエルが跳びました。" },
    { en: "keep", jp: "保つ", enSent: "Keep the room clean.", jpSent: "部屋をきれいに保ちなさい。" },
    { en: "kill", jp: "殺す", enSent: "The cat killed a mouse.", jpSent: "猫がネズミを殺しました。" },
    { en: "know", jp: "知っている", enSent: "I know his name.", jpSent: "私は彼の名前を知っています。" },
    { en: "laugh", jp: "笑う", enSent: "They laughed loudly.", jpSent: "彼らは大声で笑いました。" },
    { en: "learn", jp: "学ぶ", enSent: "I learn English at school.", jpSent: "私は学校で英語を学びます。" },
    { en: "leave", jp: "去る / 出発する", enSent: "The train leaves at ten.", jpSent: "電車は10時に出発します。" },
    { en: "let", jp: "〜させる", enSent: "Let me see.", jpSent: "見せてください。" },
    { en: "lie", jp: "横たわる / 嘘をつく", enSent: "He is lying on the bed.", jpSent: "彼はベッドに横たわっています。" },
    { en: "like", jp: "好む", enSent: "I like apples.", jpSent: "私はりんごが好きです。" },
    { en: "listen", jp: "聞く", enSent: "Listen to me.", jpSent: "私の話を聞いてください。" },
    { en: "live", jp: "住む", enSent: "I live in Tokyo.", jpSent: "私は東京に住んでいます。" },
    { en: "look", jp: "見る", enSent: "Look at the picture.", jpSent: "写真を見てください。" },
    { en: "lose", jp: "失う / 負ける", enSent: "I lost my pen.", jpSent: "私はペンをなくしました。" },
    { en: "love", jp: "愛する", enSent: "I love my family.", jpSent: "私は家族が大好きです。" },
    { en: "make", jp: "作る", enSent: "My mother made a cake.", jpSent: "母はケーキを作りました。" },
    { en: "matter", jp: "重要である", enSent: "It doesn't matter.", jpSent: "それは問題ではありません。" },
    { en: "may", jp: "〜かもしれない", enSent: "It may rain tomorrow.", jpSent: "明日は雨が降るかもしれません。" },
    { en: "mean", jp: "意味する", enSent: "What does this mean?", jpSent: "これはどういう意味ですか？" },
    { en: "meet", jp: "会う", enSent: "Nice to meet you.", jpSent: "はじめまして。" },
    { en: "mind", jp: "気にする", enSent: "Do you mind?", jpSent: "気にしますか？" },
    { en: "miss", jp: "逃す / 恋しく思う", enSent: "I missed the bus.", jpSent: "私はバスを逃しました。" },
    { en: "move", jp: "動く", enSent: "Don't move.", jpSent: "動かないで。" },
    { en: "must", jp: "〜しなければならない", enSent: "I must go now.", jpSent: "私はもう行かなければなりません。" },
    { en: "need", jp: "必要とする", enSent: "I need water.", jpSent: "私は水が必要です。" },
    { en: "notice", jp: "気づく", enSent: "I noticed the sound.", jpSent: "私はその音に気づきました。" },
    { en: "open", jp: "開ける", enSent: "Open the window.", jpSent: "窓を開けてください。" },
    { en: "paint", jp: "絵の具で描く", enSent: "He paints a picture.", jpSent: "彼は絵の具で絵を描きます。" },
    { en: "pass", jp: "手渡す / 通過する", enSent: "Please pass me the salt.", jpSent: "塩を取ってください。" },
    { en: "pay", jp: "支払う", enSent: "I will pay for it.", jpSent: "私がそれを支払います。" },
    { en: "pick", jp: "摘む / 選ぶ", enSent: "She picked a flower.", jpSent: "彼女は花を摘みました。" },
    { en: "plan", jp: "計画する", enSent: "We planned a trip.", jpSent: "私たちは旅行を計画しました。" },
    { en: "play", jp: "遊ぶ / する", enSent: "Let's play tennis.", jpSent: "テニスをしましょう。" },
    { en: "please", jp: "喜ばせる", enSent: "He tried to please her.", jpSent: "彼は彼女を喜ばせようとしました。" },
    { en: "point", jp: "指さす", enSent: "He pointed at the bird.", jpSent: "彼は鳥を指さしました。" },
    { en: "practice", jp: "練習する", enSent: "I practice the piano.", jpSent: "私はピアノを練習します。" },
    { en: "prefer", jp: "〜のほうを好む", enSent: "I prefer tea to coffee.", jpSent: "私はコーヒーよりお茶が好きです。" },
    { en: "prepare", jp: "準備する", enSent: "We prepared for the test.", jpSent: "私たちはテストの準備をしました。" },
    { en: "promise", jp: "約束する", enSent: "I promise to come.", jpSent: "私は行くことを約束します。" },
    { en: "pull", jp: "引く", enSent: "Pull the door.", jpSent: "ドアを引いてください。" },
    { en: "push", jp: "押す", enSent: "Push the button.", jpSent: "ボタンを押してください。" },
    { en: "put", jp: "置く", enSent: "Put the book on the desk.", jpSent: "本を机に置いてください。" },
    { en: "rain", jp: "雨が降る", enSent: "It is raining.", jpSent: "雨が降っています。" },
    { en: "reach", jp: "到着する", enSent: "We reached the station.", jpSent: "私たちは駅に着きました。" },
    { en: "read", jp: "読む", enSent: "I read a book.", jpSent: "私は本を読みます。" },
    { en: "realize", jp: "気づく", enSent: "I realized my mistake.", jpSent: "私は自分の間違いに気づきました。" },
    { en: "receive", jp: "受け取る", enSent: "I received a letter.", jpSent: "私は手紙を受け取りました。" },
    { en: "remember", jp: "覚えている", enSent: "I remember his face.", jpSent: "私は彼の顔を覚えています。" },
    { en: "repeat", jp: "繰り返す", enSent: "Please repeat that.", jpSent: "繰り返してください。" },
    { en: "rest", jp: "休む", enSent: "Let's rest here.", jpSent: "ここで休みましょう。" },
    { en: "return", jp: "戻る / 返す", enSent: "I will return soon.", jpSent: "すぐに戻ります。" },
    { en: "ride", jp: "乗る", enSent: "I ride a bike.", jpSent: "私は自転車に乗ります。" },
    { en: "ring", jp: "鳴る", enSent: "The bell is ringing.", jpSent: "ベルが鳴っています。" },
    { en: "run", jp: "走る", enSent: "He runs fast.", jpSent: "彼は走るのが速いです。" },
    { en: "save", jp: "救う / 貯める", enSent: "He saved the dog.", jpSent: "彼は犬を助けました。" },
    { en: "say", jp: "言う", enSent: "What did you say?", jpSent: "何と言いましたか？" },
    { en: "scold", jp: "叱る", enSent: "My father scolded me.", jpSent: "父は私を叱りました。" },
    { en: "see", jp: "見える / 会う", enSent: "I see a bird.", jpSent: "鳥が見えます。" },
    { en: "sell", jp: "売る", enSent: "They sell shoes.", jpSent: "彼らは靴を売っています。" },
    { en: "send", jp: "送る", enSent: "I will send a message.", jpSent: "私はメッセージを送ります。" },
    { en: "set", jp: "置く / 沈む", enSent: "The sun sets in the west.", jpSent: "太陽は西に沈みます。" },
    { en: "shake", jp: "振る", enSent: "Shake the bottle.", jpSent: "ボトルを振ってください。" },
    { en: "share", jp: "共有する", enSent: "Let's share the cake.", jpSent: "ケーキを分け合いましょう。" },
    { en: "shine", jp: "輝く", enSent: "The sun is shining.", jpSent: "太陽が輝いています。" },
    { en: "shoot", jp: "撃つ", enSent: "He shot an arrow.", jpSent: "彼は矢を放ちました。" },
    { en: "shout", jp: "叫ぶ", enSent: "Don't shout in the room.", jpSent: "部屋で叫ばないでください。" },
    { en: "show", jp: "見せる", enSent: "Show me your book.", jpSent: "あなたの本を見せてください。" },
    { en: "shut", jp: "閉める", enSent: "Shut the door.", jpSent: "ドアを閉めてください。" },
    { en: "sing", jp: "歌う", enSent: "She sings well.", jpSent: "彼女は歌が上手です。" },
    { en: "sink", jp: "沈む", enSent: "The boat sank.", jpSent: "ボートが沈みました。" },
    { en: "sit", jp: "座る", enSent: "Sit down, please.", jpSent: "座ってください。" },
    { en: "sleep", jp: "眠る", enSent: "I sleep well.", jpSent: "私はよく眠ります。" },
    { en: "smell", jp: "においがする", enSent: "It smells good.", jpSent: "良いにおいがします。" },
    { en: "smile", jp: "ほほえむ", enSent: "She smiled at me.", jpSent: "彼女は私にほほえみました。" },
    { en: "smoke", jp: "タバコを吸う", enSent: "Don't smoke here.", jpSent: "ここでタバコを吸わないでください。" },
    { en: "snow", jp: "雪が降る", enSent: "It will snow tomorrow.", jpSent: "明日は雪が降るでしょう。" },
    { en: "sound", jp: "聞こえる", enSent: "That sounds fun.", jpSent: "それは楽しそうですね。" },
    { en: "speak", jp: "話す", enSent: "I speak English.", jpSent: "私は英語を話します。" },
    { en: "spend", jp: "費やす", enSent: "I spent 10 dollars.", jpSent: "私は10ドル使いました。" },
    { en: "stand", jp: "立つ", enSent: "Stand up, please.", jpSent: "立ってください。" },
    { en: "start", jp: "出発する / 始める", enSent: "The game starts at ten.", jpSent: "試合は10時に始まります。" },
    { en: "stay", jp: "滞在する", enSent: "I stayed at a hotel.", jpSent: "私はホテルに泊まりました。" },
    { en: "steal", jp: "盗む", enSent: "He stole my bag.", jpSent: "彼は私のカバンを盗みました。" },
    { en: "step", jp: "歩む", enSent: "Step this way.", jpSent: "こちらへ進んでください。" },
    { en: "stop", jp: "止まる / 止める", enSent: "Stop crying.", jpSent: "泣くのをやめなさい。" },
    { en: "strike", jp: "打つ", enSent: "The clock struck twelve.", jpSent: "時計が12時を打ちました。" },
    { en: "study", jp: "勉強する", enSent: "I study math.", jpSent: "私は数学を勉強します。" },
    { en: "survive", jp: "生き残る", enSent: "The cat survived.", jpSent: "その猫は生き残りました。" },
    { en: "swim", jp: "泳ぐ", enSent: "I can swim fast.", jpSent: "私は速く泳げます。" },
    { en: "take", jp: "取る / 乗る", enSent: "Take this medicine.", jpSent: "この薬を飲みなさい。" },
    { en: "talk", jp: "話す", enSent: "Let's talk together.", jpSent: "一緒に話しましょう。" },
    { en: "taste", jp: "味がする", enSent: "This apple tastes sweet.", jpSent: "このりんごは甘い味がします。" },
    { en: "teach", jp: "教える", enSent: "He teaches us science.", jpSent: "彼は私たちに理科を教えます。" },
    { en: "tear", jp: "引き裂く", enSent: "He tore the paper.", jpSent: "彼は紙を破りました。" },
    { en: "tell", jp: "話す / 教える", enSent: "Tell me the story.", jpSent: "その話を聞かせて。" },
    { en: "test", jp: "テストする", enSent: "The teacher tested us.", jpSent: "先生は私たちをテストしました。" },
    { en: "thank", jp: "感謝する", enSent: "Thank you very much.", jpSent: "ありがとうございます。" },
    { en: "think", jp: "考える / 思う", enSent: "I think so too.", jpSent: "私もそう思います。" },
    { en: "throw", jp: "投げる", enSent: "Throw the ball to me.", jpSent: "私にボールを投げて。" },
    { en: "tie", jp: "結ぶ", enSent: "Tie your shoes.", jpSent: "靴ひもを結びなさい。" },
    { en: "touch", jp: "触れる", enSent: "Don't touch the picture.", jpSent: "絵に触らないでください。" },
    { en: "travel", jp: "旅行する", enSent: "I want to travel.", jpSent: "私は旅行したいです。" },
    { en: "try", jp: "試す", enSent: "Try again.", jpSent: "もう一度やってみて。" },
    { en: "turn", jp: "曲がる / 回す", enSent: "Turn left here.", jpSent: "ここで左に曲がってください。" },
    { en: "understand", jp: "理解する", enSent: "I understand you.", jpSent: "あなたの言うことがわかります。" },
    { en: "use", jp: "使う", enSent: "May I use your pen?", jpSent: "あなたのペンを使ってもいいですか？" },
    { en: "visit", jp: "訪問する", enSent: "I visited Kyoto.", jpSent: "私は京都を訪れました。" },
    { en: "wait", jp: "待つ", enSent: "Wait for me.", jpSent: "私を待って。" },
    { en: "wake", jp: "目を覚ます", enSent: "Wake up early.", jpSent: "早く起きなさい。" },
    { en: "walk", jp: "歩く", enSent: "I walk to school.", jpSent: "私は歩いて学校に行きます。" },
    { en: "want", jp: "欲しい", enSent: "I want a new bike.", jpSent: "私は新しい自転車が欲しいです。" },
    { en: "wash", jp: "洗う", enSent: "Wash your hands.", jpSent: "手を洗いなさい。" },
    { en: "waste", jp: "浪費する", enSent: "Don't waste time.", jpSent: "時間を無駄にしないで。" },
    { en: "watch", jp: "見る", enSent: "I watch TV.", jpSent: "私はテレビを見ます。" },
    { en: "wear", jp: "着ている", enSent: "She wears a red coat.", jpSent: "彼女は赤いコートを着ています。" },
    { en: "welcome", jp: "歓迎する", enSent: "Welcome to Japan.", jpSent: "日本へようこそ。" },
    { en: "will", jp: "〜するつもりだ", enSent: "I will go tomorrow.", jpSent: "私は明日行きます。" },
    { en: "win", jp: "勝つ", enSent: "We won the game.", jpSent: "私たちは試合に勝ちました。" },
    { en: "wish", jp: "望む", enSent: "I wish you luck.", jpSent: "あなたの幸運を祈ります。" },
    { en: "wonder", jp: "〜かなと思う", enSent: "I wonder who he is.", jpSent: "彼は誰かなと思います。" },
    { en: "work", jp: "働く", enSent: "He works hard.", jpSent: "彼は一生懸命働きます。" },
    { en: "worry", jp: "心配する", enSent: "Don't worry.", jpSent: "心配しないで。" },
    { en: "write", jp: "書く", enSent: "I write a letter.", jpSent: "私は手紙を書きます。" },
    { en: "able", jp: "できる", enSent: "I am able to run.", jpSent: "私は走ることができます。" },
    { en: "afraid", jp: "恐れて", enSent: "I am afraid of snakes.", jpSent: "私はヘビが怖いです。" },
    { en: "all", jp: "すべての", enSent: "All boys like baseball.", jpSent: "すべての男の子は野球が好きです。" },
    { en: "alone", jp: "一人で", enSent: "I am home alone.", jpSent: "私は家に一人です。" },
    { en: "always", jp: "いつも", enSent: "He is always happy.", jpSent: "彼はいつも幸せです。" },
    { en: "angry", jp: "怒って", enSent: "My mother is angry.", jpSent: "私の母は怒っています。" },
    { en: "another", jp: "別の", enSent: "Show me another one.", jpSent: "別のものを見せてください。" },
    { en: "any", jp: "いくらかの", enSent: "Do you have any pets?", jpSent: "何かペットを飼っていますか？" },
    { en: "bad", jp: "悪い", enSent: "He is a bad boy.", jpSent: "彼は悪い男の子です。" },
    { en: "beautiful", jp: "美しい", enSent: "This flower is beautiful.", jpSent: "この花は美しいです。" },
    { en: "big", jp: "大きい", enSent: "That is a big dog.", jpSent: "あれは大きな犬です。" },
    { en: "black", jp: "黒い", enSent: "He has a black cat.", jpSent: "彼は黒い猫を飼っています。" },
    { en: "blind", jp: "目の見えない", enSent: "He is a blind man.", jpSent: "彼は目の見えない人です。" },
    { en: "blue", jp: "青い", enSent: "The sky is blue.", jpSent: "空は青いです。" },
    { en: "both", jp: "両方の", enSent: "Both of us are students.", jpSent: "私たちは両方とも学生です。" },
    { en: "brave", jp: "勇敢な", enSent: "He is a brave dog.", jpSent: "彼は勇敢な犬です。" },
    { en: "bright", jp: "明るい", enSent: "The sun is bright.", jpSent: "太陽が明るいです。" },
    { en: "busy", jp: "忙しい", enSent: "I am very busy today.", jpSent: "私は今日とても忙しいです。" },
    { en: "careful", jp: "注意深い", enSent: "Be careful.", jpSent: "気をつけて。" },
    { en: "cheap", jp: "安い", enSent: "This bag is cheap.", jpSent: "このカバンは安いです。" },
    { en: "clean", jp: "きれいな", enSent: "Keep your hands clean.", jpSent: "手をきれいにしておきなさい。" },
    { en: "clear", jp: "はっきりした", enSent: "The water is clear.", jpSent: "水が澄んでいます。" },
    { en: "close", jp: "近い", enSent: "The station is close.", jpSent: "駅は近いです。" },
    { en: "cold", jp: "冷たい / 寒い", enSent: "It is cold today.", jpSent: "今日は寒いです。" },
    { en: "cool", jp: "涼しい", enSent: "The wind is cool.", jpSent: "風が涼しいです。" },
    { en: "dark", jp: "暗い", enSent: "It is getting dark.", jpSent: "暗くなってきました。" },
    { en: "dead", jp: "死んだ", enSent: "The bird is dead.", jpSent: "その鳥は死んでいます。" },
    { en: "deep", jp: "深い", enSent: "The river is deep.", jpSent: "その川は深いです。" },
    { en: "different", jp: "異なる", enSent: "We have different ideas.", jpSent: "私たちは違う考えを持っています。" },
    { en: "difficult", jp: "難しい", enSent: "Math is difficult.", jpSent: "数学は難しいです。" },
    { en: "dirty", jp: "汚い", enSent: "Your shoes are dirty.", jpSent: "あなたの靴は汚いです。" },
    { en: "dry", jp: "乾いた", enSent: "My shirt is dry.", jpSent: "私のシャツは乾いています。" },
    { en: "early", jp: "早い", enSent: "I wake up early.", jpSent: "私は早く起きます。" },
    { en: "easy", jp: "簡単な", enSent: "This test is easy.", jpSent: "このテストは簡単です。" },
    { en: "empty", jp: "空の", enSent: "The box is empty.", jpSent: "その箱は空です。" },
    { en: "enough", jp: "十分な", enSent: "We have enough food.", jpSent: "十分な食べ物があります。" },
    { en: "even", jp: "〜でさえ", enSent: "Even a child knows it.", jpSent: "子供でさえそれを知っています。" },
    { en: "ever", jp: "かつて / 今までに", enSent: "Have you ever been there?", jpSent: "そこに行ったことがありますか？" },
    { en: "every", jp: "すべての / 毎〜", enSent: "I play tennis every day.", jpSent: "私は毎日テニスをします。" },
    { en: "famous", jp: "有名な", enSent: "He is a famous writer.", jpSent: "彼は有名な作家です。" },
    { en: "far", jp: "遠い", enSent: "Is the station far?", jpSent: "駅は遠いですか？" },
    { en: "fast", jp: "速い", enSent: "She runs fast.", jpSent: "彼女は速く走ります。" },
    { en: "few", jp: "ほとんどない", enSent: "I have few friends.", jpSent: "私には友達がほとんどいません。" },
    { en: "fine", jp: "晴れた / 元気な", enSent: "I am fine.", jpSent: "私は元気です。" },
    { en: "first", jp: "最初の", enSent: "This is my first time.", jpSent: "これが初めてです。" },
    { en: "foolish", jp: "愚かな", enSent: "That is a foolish idea.", jpSent: "それは愚かな考えです。" },
    { en: "free", jp: "自由な / 暇な", enSent: "I am free today.", jpSent: "私は今日暇です。" },
    { en: "fresh", jp: "新鮮な", enSent: "I like fresh fruit.", jpSent: "私は新鮮な果物が好きです。" },
    { en: "front", jp: "前の", enSent: "The front door is open.", jpSent: "前のドアが開いています。" },
    { en: "full", jp: "いっぱいの", enSent: "The cup is full.", jpSent: "コップはいっぱいです。" },
    { en: "glad", jp: "うれしい", enSent: "I am glad to meet you.", jpSent: "あなたに会えてうれしいです。" },
    { en: "good", jp: "良い", enSent: "You are a good boy.", jpSent: "あなたは良い男の子です。" },
    { en: "great", jp: "偉大な", enSent: "He is a great man.", jpSent: "彼は偉大な人です。" },
    { en: "green", jp: "緑の", enSent: "I like green tea.", jpSent: "私は緑茶が好きです。" },
    { en: "happy", jp: "幸せな", enSent: "I am very happy.", jpSent: "私はとても幸せです。" },
    { en: "hard", jp: "一生懸命に / 難しい", enSent: "Study hard.", jpSent: "一生懸命勉強しなさい。" },
    { en: "heavy", jp: "重い", enSent: "This box is heavy.", jpSent: "この箱は重いです。" },
    { en: "high", jp: "高い", enSent: "That is a high mountain.", jpSent: "あれは高い山です。" },
    { en: "hot", jp: "暑い / 熱い", enSent: "It is very hot today.", jpSent: "今日はとても暑いです。" },
    { en: "hungry", jp: "空腹の", enSent: "I am very hungry.", jpSent: "私はとてもお腹が空いています。" },
    { en: "ill", jp: "病気で", enSent: "My mother is ill.", jpSent: "母は病気です。" },
    { en: "important", jp: "重要な", enSent: "This is important news.", jpSent: "これは重要なニュースです。" },
    { en: "interesting", jp: "面白い", enSent: "This book is interesting.", jpSent: "この本は面白いです。" },
    { en: "just", jp: "ちょうど", enSent: "It is just three o'clock.", jpSent: "ちょうど3時です。" },
    { en: "kind", jp: "親切な", enSent: "He is very kind.", jpSent: "彼はとても親切です。" },
    { en: "large", jp: "大きい", enSent: "Tokyo is a large city.", jpSent: "東京は大きな都市です。" },
    { en: "late", jp: "遅れた", enSent: "You are late.", jpSent: "あなたは遅刻です。" },
    { en: "left", jp: "左の", enSent: "Look at the left side.", jpSent: "左側を見てください。" },
    { en: "light", jp: "軽い / 明るい", enSent: "This bag is light.", jpSent: "このカバンは軽いです。" },
    { en: "little", jp: "少しの / 小さい", enSent: "I have a little money.", jpSent: "私は少しお金を持っています。" },
    { en: "long", jp: "長い", enSent: "It is a long bridge.", jpSent: "それは長い橋です。" },
    { en: "low", jp: "低い", enSent: "The wall is low.", jpSent: "その壁は低いです。" },
    { en: "lucky", jp: "幸運な", enSent: "You are lucky.", jpSent: "あなたは運がいいです。" },
    { en: "many", jp: "多くの", enSent: "I have many books.", jpSent: "私はたくさんの本を持っています。" },
    { en: "much", jp: "たくさんの", enSent: "Thank you very much.", jpSent: "本当にありがとうございます。" },
    { en: "narrow", jp: "狭い", enSent: "This road is narrow.", jpSent: "この道は狭いです。" },
    { en: "near", jp: "近い", enSent: "My school is near here.", jpSent: "私の学校はこの近くです。" },
    { en: "never", jp: "決して〜ない", enSent: "I never lie.", jpSent: "私は決して嘘をつきません。" },
    { en: "new", jp: "新しい", enSent: "I want a new car.", jpSent: "私は新しい車が欲しいです。" },
    { en: "nice", jp: "素敵な", enSent: "Have a nice day.", jpSent: "良い一日を。" },
    { en: "noisy", jp: "騒がしい", enSent: "This room is noisy.", jpSent: "この部屋はうるさいです。" },
    { en: "often", jp: "しばしば", enSent: "I often go there.", jpSent: "私はよくそこに行きます。" },
    { en: "old", jp: "古い / 年とった", enSent: "This is an old house.", jpSent: "これは古い家です。" },
    { en: "only", jp: "ただ〜だけ", enSent: "I have only one pen.", jpSent: "私はペンを一本しか持っていません。" },
    { en: "other", jp: "他の", enSent: "Show me other books.", jpSent: "他の本を見せてください。" },
    { en: "over", jp: "越えて / 終わって", enSent: "The game is over.", jpSent: "試合は終わりました。" },
    { en: "own", jp: "自分自身の", enSent: "I have my own room.", jpSent: "私は自分の部屋を持っています。" },
    { en: "poor", jp: "貧しい / かわいそうな", enSent: "He is a poor man.", jpSent: "彼は貧しい男です。" },
    { en: "popular", jp: "人気のある", enSent: "This song is popular.", jpSent: "この歌は人気があります。" },
    { en: "pretty", jp: "かわいらしい", enSent: "She is a pretty girl.", jpSent: "彼女は可愛い女の子です。" },
    { en: "proud", jp: "誇りに思う", enSent: "I am proud of you.", jpSent: "あなたを誇りに思います。" },
    { en: "quick", jp: "素早い", enSent: "He is a quick runner.", jpSent: "彼は走るのが速いです。" },
    { en: "quiet", jp: "静かな", enSent: "Be quiet, please.", jpSent: "静かにしてください。" },
    { en: "ready", jp: "準備ができた", enSent: "Are you ready?", jpSent: "準備はいいですか？" },
    { en: "real", jp: "本当の", enSent: "Is this a real diamond?", jpSent: "これは本物のダイヤですか？" },
    { en: "rich", jp: "金持ちの", enSent: "He is a rich man.", jpSent: "彼は金持ちです。" },
    { en: "right", jp: "正しい / 右の", enSent: "You are right.", jpSent: "あなたは正しいです。" },
    { en: "sad", jp: "悲しい", enSent: "I feel sad.", jpSent: "私は悲しいです。" },
    { en: "safe", jp: "安全な", enSent: "This place is safe.", jpSent: "この場所は安全です。" },
    { en: "same", jp: "同じ", enSent: "We are in the same class.", jpSent: "私たちは同じクラスです。" },
    { en: "short", jp: "短い", enSent: "She has short hair.", jpSent: "彼女は短い髪をしています。" },
    { en: "sick", jp: "病気の", enSent: "The baby is sick.", jpSent: "赤ちゃんが病気です。" },
    { en: "slow", jp: "遅い", enSent: "This train is slow.", jpSent: "この電車は遅いです。" },
    { en: "small", jp: "小さい", enSent: "It is a small bird.", jpSent: "それは小さな鳥です。" },
    { en: "soft", jp: "やわらかい", enSent: "This bed is soft.", jpSent: "このベッドは柔らかいです。" },
    { en: "some", jp: "いくつかの", enSent: "I need some paper.", jpSent: "紙が少し必要です。" },
    { en: "sometimes", jp: "時々", enSent: "I sometimes eat sushi.", jpSent: "私は時々寿司を食べます。" },
    { en: "soon", jp: "すぐに", enSent: "I will be back soon.", jpSent: "すぐに戻ります。" },
    { en: "special", jp: "特別な", enSent: "This is a special day.", jpSent: "今日は特別な日です。" },
    { en: "strong", jp: "強い", enSent: "He is a strong man.", jpSent: "彼は強い男です。" },
    { en: "stupid", jp: "愚かな", enSent: "That is a stupid idea.", jpSent: "それは愚かな考えです。" },
    { en: "sudden", jp: "突然の", enSent: "It was a sudden rain.", jpSent: "突然の雨でした。" },
    { en: "sure", jp: "確信して", enSent: "I am sure about it.", jpSent: "私はそれを確信しています。" },
    { en: "sweet", jp: "甘い", enSent: "This cake is sweet.", jpSent: "このケーキは甘いです。" },
    { en: "tall", jp: "背が高い", enSent: "He is a tall boy.", jpSent: "彼は背の高い男の子です。" },
    { en: "terrible", jp: "恐ろしい / ひどい", enSent: "It is a terrible storm.", jpSent: "それはひどい嵐です。" },
    { en: "thick", jp: "厚い", enSent: "This is a thick book.", jpSent: "これは分厚い本です。" },
    { en: "thin", jp: "薄い", enSent: "The ice is thin.", jpSent: "氷が薄いです。" },
    { en: "tired", jp: "疲れた", enSent: "I am very tired.", jpSent: "私はとても疲れています。" },
    { en: "true", jp: "本当の", enSent: "Is the story true?", jpSent: "その話は本当ですか？" },
    { en: "useful", jp: "役に立つ", enSent: "This tool is useful.", jpSent: "この道具は役に立ちます。" },
    { en: "warm", jp: "暖かい", enSent: "The weather is warm.", jpSent: "天気が暖かいです。" },
    { en: "weak", jp: "弱い", enSent: "He is weak.", jpSent: "彼は弱いです。" },
    { en: "well", jp: "上手に / 健康で", enSent: "She sings well.", jpSent: "彼女は歌が上手です。" },
    { en: "white", jp: "白い", enSent: "I have a white dog.", jpSent: "私は白い犬を飼っています。" },
    { en: "wide", jp: "広い", enSent: "The road is wide.", jpSent: "その道は広いです。" },
    { en: "wild", jp: "野生の", enSent: "Lions are wild animals.", jpSent: "ライオンは野生動物です。" },
    { en: "wrong", jp: "間違った", enSent: "This is a wrong answer.", jpSent: "これは間違った答えです。" },
    { en: "yellow", jp: "黄色い", enSent: "The flower is yellow.", jpSent: "その花は黄色いです。" },
    { en: "young", jp: "若い", enSent: "He is a young doctor.", jpSent: "彼は若い医者です。" }
];
