  // --- 準一級核心词库 第一批 (51 - 250) ---
const words_pre1_batch1 = [
  // --- Priority 1: 核心痛点动词 & 形容词 ---
  { word: "crucial", meaning: "極めて重要な", exampleEn: "Sleep is crucial for your health.", exampleJp: "睡眠は健康にとって極めて重要です。" },
  { word: "implement", meaning: "実行する、導入する", exampleEn: "The school will implement a new rule next month.", exampleJp: "学校は来月、新しい規則を導入します。" },
  { word: "obstacle", meaning: "障害、邪魔", exampleEn: "Lack of money was a big obstacle for his plan.", exampleJp: "資金不足は彼の計画にとって大きな障害でした。" },
  { word: "deliberately", meaning: "故意に、わざと", exampleEn: "He deliberately broke the window.", exampleJp: "彼はわざと窓を割りました。" },
  { word: "inevitable", meaning: "避けられない、必然の", exampleEn: "Traffic jams are inevitable in this big city.", exampleJp: "この大都市では交通渋滞は避けられません。" },
  { word: "adequate", meaning: "十分な、適切な", exampleEn: "Make sure you have adequate water for the trip.", exampleJp: "旅行のために十分な水があるか確認してください。" },
  { word: "comprehensive", meaning: "総合的な、包括的な", exampleEn: "The book gives a comprehensive guide to cooking.", exampleJp: "その本は料理の総合的なガイドを提供しています。" },
  { word: "compromise", meaning: "妥協する", exampleEn: "They had to compromise to finish the project.", exampleJp: "彼らはプロジェクトを終わらせるために妥協しなければなりませんでした。" },
  { word: "evaluate", meaning: "評価する", exampleEn: "The teacher evaluated the students' drawing skills.", exampleJp: "先生は生徒たちの絵のスキルを評価しました。" },
  { word: "exceed", meaning: "超える、上回る", exampleEn: "The price must not exceed 50 dollars.", exampleJp: "価格は50ドルを超えてはいけません。" },
  { word: "modify", meaning: "修正する、変更する", exampleEn: "We need to modify the design to make it safer.", exampleJp: "より安全にするために、デザインを修正する必要があります。" },
  { word: "reluctant", meaning: "気が進まない", exampleEn: "She was reluctant to talk about her mistake.", exampleJp: "彼女は自分のミスについて話すのが気が進まなかった。" },
  { word: "substitute", meaning: "代わりに使う、代用品", exampleEn: "You can substitute honey for sugar.", exampleJp: "砂糖の代わりにハチミツを使うことができます。" },
  { word: "valid", meaning: "有効な、妥当な", exampleEn: "This ticket is valid for one week.", exampleJp: "このチケットは1週間有効です。" },
  { word: "thrive", meaning: "繁栄する、よく育つ", exampleEn: "These plants thrive in hot weather.", exampleJp: "これらの植物は暑い天候でよく育ちます。" },
  { word: "accumulate", meaning: "蓄積する、集める", exampleEn: "Dust quickly accumulates in this old room.", exampleJp: "この古い部屋ではすぐにほこりが蓄積します。" },
  { word: "eliminate", meaning: "排除する、取り除く", exampleEn: "He exercised to eliminate fat from his body.", exampleJp: "彼は体から脂肪を取り除くために運動しました。" },
  { word: "fascinate", meaning: "魅了する", exampleEn: "The magic trick fascinated the children.", exampleJp: "その手品は子供たちを魅了しました。" },
  { word: "interfere", meaning: "干渉する、邪魔する", exampleEn: "Don't interfere with my homework.", exampleJp: "私の宿題の邪魔をしないでください。" },
  { word: "justify", meaning: "正当化する", exampleEn: "You cannot justify stealing food.", exampleJp: "食べ物を盗むことを正当化することはできません。" },
  { word: "neglect", meaning: "怠る、無視する", exampleEn: "She neglected her plants, so they died.", exampleJp: "彼女が植物の世話を怠ったので、それらは枯れました。" },
  { word: "persist", meaning: "固執する、持続する", exampleEn: "The rain will persist until tomorrow morning.", exampleJp: "雨は明日の朝まで降り続くでしょう。" },
  { word: "stimulate", meaning: "刺激する", exampleEn: "Coffee can stimulate your brain.", exampleJp: "コーヒーは脳を刺激することができます。" },
  { word: "tolerate", meaning: "我慢する、許容する", exampleEn: "I cannot tolerate this loud noise anymore.", exampleJp: "私はこれ以上この大きな騒音を我慢できません。" },
  { word: "abundant", meaning: "豊富な", exampleEn: "This island has an abundant supply of fish.", exampleJp: "この島には豊富な魚の供給があります。" },
  { word: "consistent", meaning: "一貫した、矛盾のない", exampleEn: "His actions are consistent with his words.", exampleJp: "彼の行動は言葉と一貫しています。" },
  { word: "drastic", meaning: "劇的な、思い切った", exampleEn: "The store made a drastic cut in prices.", exampleJp: "その店は価格の思い切った値下げをしました。" },
  { word: "fatal", meaning: "致命的な", exampleEn: "He made a fatal mistake in the game.", exampleJp: "彼はゲームで致命的なミスをしました。" },
  { word: "hostile", meaning: "敵意のある", exampleEn: "The wild dog gave me a hostile look.", exampleJp: "その野犬は私に敵意のある視線を向けました。" },
  { word: "prominent", meaning: "著名な、目立つ", exampleEn: "She is a prominent doctor in this city.", exampleJp: "彼女はこの街で著名な医者です。" },
  { word: "vulnerable", meaning: "傷つきやすい、弱い", exampleEn: "Babies are vulnerable to cold weather.", exampleJp: "赤ちゃんは寒い天候に弱いです。" },
  { word: "flourish", meaning: "栄える、活躍する", exampleEn: "His business began to flourish last year.", exampleJp: "彼のビジネスは昨年から栄え始めました。" },
  { word: "imply", meaning: "ほのめかす、暗示する", exampleEn: "Her smile implied that she agreed with us.", exampleJp: "彼女の笑顔は私たちに同意していることをほのめかしていました。" },
  { word: "clarify", meaning: "明確にする", exampleEn: "Please clarify what you mean by that.", exampleJp: "それで何を意味しているのか明確にしてください。" },
  { word: "inspire", meaning: "奮い立たせる、ひらめきを与える", exampleEn: "The coach's speech inspired the players.", exampleJp: "コーチのスピーチは選手たちを奮い立たせました。" },

  // --- Priority 2: 準一級核心短语 / 惯用语 ---
  { word: "cope with", meaning: "〜をうまく処理する", exampleEn: "It is hard to cope with so much stress.", exampleJp: "これほどのストレスをうまく処理するのは難しいです。" },
  { word: "rule out", meaning: "〜を除外する", exampleEn: "The police ruled out him as a suspect.", exampleJp: "警察は彼を容疑者から除外しました。" },
  { word: "account for", meaning: "〜の割合を占める、〜を説明する", exampleEn: "Rent accounts for half of my salary.", exampleJp: "家賃が私の給料の半分を占めています。" },
  { word: "sum up", meaning: "〜を要約する", exampleEn: "To sum up, we need to work harder.", exampleJp: "要約すると、私たちはもっと懸命に働く必要があります。" },
  { word: "look into", meaning: "〜を調査する", exampleEn: "The boss will look into the problem.", exampleJp: "上司がその問題を調査します。" },
  { word: "point out", meaning: "〜を指摘する", exampleEn: "She pointed out a small mistake in the report.", exampleJp: "彼女は報告書の小さなミスを指摘しました。" },
  { word: "figure out", meaning: "〜を理解する、解決する", exampleEn: "I cannot figure out how to use this machine.", exampleJp: "この機械の使い方が理解できません。" },
  { word: "come up with", meaning: "〜を思いつく", exampleEn: "He came up with a great idea for the party.", exampleJp: "彼はパーティーのための素晴らしいアイデアを思いつきました。" },
  { word: "narrow down", meaning: "〜を絞り込む", exampleEn: "We must narrow down the list of candidates to three.", exampleJp: "候補者のリストを3人に絞り込まなければなりません。" },
  { word: "lay off", meaning: "〜を解雇する", exampleEn: "The company had to lay off 50 workers.", exampleJp: "その会社は50人の労働者を解雇しなければなりませんでした。" },
  { word: "carry out", meaning: "〜を実行する", exampleEn: "The scientists carried out a new experiment.", exampleJp: "科学者たちは新しい実験を実行しました。" },
  { word: "bring about", meaning: "〜を引き起こす", exampleEn: "The internet brought about a big change in our lives.", exampleJp: "インターネットは私たちの生活に大きな変化を引き起こしました。" },
  { word: "make up for", meaning: "〜の埋め合わせをする", exampleEn: "I bought her flowers to make up for being late.", exampleJp: "遅刻の埋め合わせをするために、私は彼女に花を買いました。" },
  { word: "stand for", meaning: "〜を表す、象徴する", exampleEn: "What does WHO stand for?", exampleJp: "WHOは何を表していますか？" },
  { word: "run out of", meaning: "〜を使い果たす", exampleEn: "We ran out of milk, so I will buy some.", exampleJp: "牛乳を使い果たしたので、買ってきます。" },


  // 核心动词 (Priority 1 & 3)
  { word: "assess", meaning: "評価する、査定する", exampleEn: "The teacher assessed the test results.", exampleJp: "先生はテストの結果を評価しました。" },
  { word: "assign", meaning: "割り当てる", exampleEn: "The boss assigned a new task to me.", exampleJp: "上司は私に新しい仕事を割り当てました。" },
  { word: "betray", meaning: "裏切る", exampleEn: "He betrayed his best friend.", exampleJp: "彼は親友を裏切りました。" },
  { word: "boast", meaning: "自慢する", exampleEn: "She always boasts about her good grades.", exampleJp: "彼女はいつも良い成績を自慢します。" },
  { word: "cease", meaning: "終わる、やめる", exampleEn: "The factory ceased making those cars.", exampleJp: "その工場はそれらの車の製造をやめました。" },
  { word: "collapse", meaning: "崩壊する、倒れる", exampleEn: "The old bridge collapsed during the storm.", exampleJp: "古い橋は嵐の間に崩壊しました。" },
  { word: "conceal", meaning: "隠す", exampleEn: "He tried to conceal his anger.", exampleJp: "彼は怒りを隠そうとしました。" },
  { word: "condemn", meaning: "非難する", exampleEn: "Many people condemned the violent attack.", exampleJp: "多くの人々がその暴力的な攻撃を非難しました。" },
  { word: "confess", meaning: "告白する", exampleEn: "The thief confessed his crime to the police.", exampleJp: "泥棒は警察に犯罪を告白しました。" },
  { word: "confront", meaning: "直面する、立ち向かう", exampleEn: "You must confront your fear of the dark.", exampleJp: "あなたは暗闇への恐怖に立ち向かわなければなりません。" },
  { word: "convey", meaning: "伝える、運ぶ", exampleEn: "Words cannot convey my deep sadness.", exampleJp: "言葉では私の深い悲しみを伝えることができません。" },
  { word: "decay", meaning: "腐る、衰退する", exampleEn: "Eating too much sugar makes your teeth decay.", exampleJp: "砂糖を食べすぎると歯が虫歯になります（腐ります）。" },
  { word: "deceive", meaning: "だます", exampleEn: "He deceived the old man to get his money.", exampleJp: "彼はお金を手に入れるためにその老人をだました。" },
  { word: "declare", meaning: "宣言する", exampleEn: "The country declared war on its neighbor.", exampleJp: "その国は隣国に宣戦布告（戦争を宣言）しました。" },
  { word: "decline", meaning: "断る、減少する", exampleEn: "I had to decline his invitation to the party.", exampleJp: "私は彼のパーティーへの招待を断らなければなりませんでした。" },
  { word: "dedicate", meaning: "捧げる", exampleEn: "She dedicated her life to helping poor children.", exampleJp: "彼女は貧しい子供たちを助けることに人生を捧げました。" },
  { word: "defeat", meaning: "打ち負かす", exampleEn: "Our team defeated the champions.", exampleJp: "私たちのチームはチャンピオンを打ち負かしました。" },
  { word: "deprive", meaning: "奪う", "exampleEn": "The new law deprives people of their freedom.", exampleJp: "新しい法律は人々から自由を奪います。" },
  { word: "derive", meaning: "引き出す、由来する", exampleEn: "He derives great joy from playing the piano.", exampleJp: "彼はピアノを弾くことから大きな喜びを引き出します。" },
  { word: "detect", meaning: "見つける、感知する", exampleEn: "The dog can detect the smell of drugs.", exampleJp: "その犬は薬物の匂いを感知することができます。" },
  { word: "deteriorate", meaning: "悪化する", exampleEn: "The weather will deteriorate tomorrow.", exampleJp: "明日は天気が悪化するでしょう。" },
  { word: "diminish", meaning: "減る、少なくなる", exampleEn: "His pain diminished after he took the medicine.", exampleJp: "薬を飲んだ後、彼の痛みは減りました。" },
  { word: "discard", meaning: "捨てる", exampleEn: "Please discard your old clothes.", exampleJp: "古い服は捨ててください。" },
  { word: "disclose", meaning: "明らかにする、暴く", exampleEn: "The company refused to disclose its secret.", exampleJp: "その会社は秘密を明らかにすることを拒否しました。" },
  { word: "dismiss", meaning: "解雇する、退ける", exampleEn: "The boss dismissed him for being late.", exampleJp: "上司は遅刻したことで彼を解雇しました。" },
  { word: "distract", meaning: "気をそらす", exampleEn: "The loud music distracted me from my reading.", exampleJp: "大音量の音楽が私の読書から気をそらしました。" },
  { word: "distribute", meaning: "分配する、配る", exampleEn: "The teacher distributed the test papers.", exampleJp: "先生はテスト用紙を配りました。" },
  { word: "dominate", meaning: "支配する", exampleEn: "The strong team dominated the basketball game.", exampleJp: "その強いチームがバスケットボールの試合を支配しました。" },
  { word: "drag", meaning: "引きずる", exampleEn: "He dragged the heavy box across the floor.", exampleJp: "彼は重い箱を床に引きずりました。" },
  { word: "dwell", meaning: "住む、こだわる", exampleEn: "Do not dwell on your past mistakes.", exampleJp: "過去の失敗にこだわってはいけません。" },
  { word: "embrace", meaning: "抱きしめる、受け入れる", exampleEn: "She embraced her son at the airport.", exampleJp: "彼女は空港で息子を抱きしめました。" },
  { word: "emerge", meaning: "現れる", exampleEn: "A large bear emerged from the dark cave.", exampleJp: "大きなクマが暗い洞窟から現れました。" },
  { word: "endure", meaning: "耐える", exampleEn: "They had to endure cold weather without coats.", exampleJp: "彼らはコートなしで寒い天候に耐えなければなりませんでした。" },
  { word: "enhance", meaning: "高める、向上させる", exampleEn: "Good lighting can enhance the beauty of a room.", exampleJp: "良い照明は部屋の美しさを高めることができます。" },
  { word: "ensure", meaning: "確実にする", exampleEn: "Please lock the door to ensure our safety.", exampleJp: "私たちの安全を確実にするために、ドアに鍵をかけてください。" },
  { word: "exaggerate", meaning: "誇張する", exampleEn: "He tends to exaggerate his fishing stories.", exampleJp: "彼は釣りの話を誇張する傾向があります。" },
  { word: "exhibit", meaning: "展示する、示す", exampleEn: "The museum exhibits old paintings.", exampleJp: "その博物館は古い絵画を展示しています。" },
  { word: "exploit", meaning: "不当に利用する、搾取する", exampleEn: "It is wrong to exploit young workers.", exampleJp: "若い労働者を搾取するのは間違っています。" },
  { word: "extract", meaning: "引き出す、抽出する", exampleEn: "Dentists extract bad teeth.", exampleJp: "歯医者は悪い歯を抜きます（引き出します）。" },
  { word: "fade", meaning: "色あせる、消えていく", exampleEn: "The colors of the old shirt began to fade.", exampleJp: "古いシャツの色が色あせ始めました。" },
  { word: "fluctuate", meaning: "変動する", exampleEn: "Vegetable prices fluctuate depending on the season.", exampleJp: "野菜の価格は季節によって変動します。" },
  { word: "forbid", meaning: "禁じる", exampleEn: "The law forbids smoking in this area.", exampleJp: "法律でこのエリアでの喫煙を禁じています。" },
  { word: "generate", meaning: "生み出す、発生させる", exampleEn: "Wind power can generate electricity.", exampleJp: "風力は電気を生み出すことができます。" },
  { word: "grasp", meaning: "しっかり握る、理解する", exampleEn: "He grasped my hand firmly.", exampleJp: "彼は私の手をしっかりと握りました。" },
  { word: "heal", meaning: "治る、癒やす", exampleEn: "The cut on his finger healed quickly.", exampleJp: "彼の指の切り傷はすぐに治りました。" },
  { word: "hesitate", meaning: "ためらう", exampleEn: "Do not hesitate to ask me questions.", exampleJp: "ためらわずに私に質問してください。" },
  { word: "ignore", meaning: "無視する", exampleEn: "She completely ignored his rude comment.", exampleJp: "彼女は彼の失礼なコメントを完全に無視しました。" },
  { word: "illustrate", meaning: "説明する、図解する", exampleEn: "He used pictures to illustrate his idea.", exampleJp: "彼は自分のアイデアを説明するために絵を使いました。" },
  { word: "imitate", meaning: "真似る", exampleEn: "Parrots can imitate human voices.", exampleJp: "オウムは人間の声を真似ることができます。" },
  { word: "impose", meaning: "課す、押しつける", exampleEn: "The government imposed a new tax on cars.", exampleJp: "政府は車に新しい税金を課しました。" },
  { word: "incorporate", meaning: "組み込む、合体させる", exampleEn: "We will incorporate your idea into the new plan.", exampleJp: "あなたのアイデアを新しい計画に組み込みます。" },
  { word: "indicate", meaning: "示す、指し示す", exampleEn: "The dark clouds indicate rain.", exampleJp: "暗い雲は雨を示しています。" },
  { word: "induce", meaning: "引き起こす、誘発する", exampleEn: "Too much stress can induce headaches.", exampleJp: "ストレスが多すぎると頭痛を引き起こすことがあります。" },
  { word: "inherit", meaning: "相続する、受け継ぐ", exampleEn: "He inherited a large house from his grandfather.", exampleJp: "彼は祖父から大きな家を相続しました。" },
  { word: "initiate", meaning: "始める", exampleEn: "They initiated a new project last week.", exampleJp: "彼らは先週、新しいプロジェクトを始めました。" },
  { word: "inquire", meaning: "尋ねる", exampleEn: "I called the station to inquire about train times.", exampleJp: "私は電車の時間について尋ねるために駅に電話しました。" },
  { word: "instruct", meaning: "指示する、教える", exampleEn: "The coach instructed them to run faster.", exampleJp: "コーチは彼らにもっと速く走るよう指示しました。" },
  { word: "integrate", meaning: "統合する", exampleEn: "The school integrates students from different countries.", exampleJp: "その学校は異なる国からの生徒たちを統合しています。" },
  { word: "interact", meaning: "交流する、相互に作用する", exampleEn: "Children learn a lot when they interact with others.", exampleJp: "子供たちは他人と交流するときに多くを学びます。" },
  { word: "investigate", meaning: "調査する", exampleEn: "The police are investigating the murder case.", exampleJp: "警察はその殺人事件を調査しています。" },

  // 核心形容词 (Priority 1 & 4)
  { word: "absurd", meaning: "ばかげた", exampleEn: "Wearing a heavy coat in summer is absurd.", exampleJp: "夏に厚いコートを着るのはばかげています。" },
  { word: "acute", meaning: "鋭い、深刻な", exampleEn: "Dogs have an acute sense of smell.", exampleJp: "犬は鋭い嗅覚を持っています。" },
  { word: "aggressive", meaning: "攻撃的な", exampleEn: "The aggressive dog barked at everyone.", exampleJp: "その攻撃的な犬は全員に吠えました。" },
  { word: "ambiguous", meaning: "あいまいな", exampleEn: "His answer was ambiguous, so I was confused.", exampleJp: "彼の答えはあいまいだったので、私は混乱しました。" },
  { word: "ambitious", meaning: "野心的な", exampleEn: "He is an ambitious young man who wants to be CEO.", exampleJp: "彼はCEOになりたい野心的な若者です。" },
  { word: "ample", meaning: "十分な、たっぷりの", exampleEn: "There is ample space for your bags in the trunk.", exampleJp: "トランクにはあなたの荷物を入れる十分なスペースがあります。" },
  { word: "anonymous", meaning: "匿名の", exampleEn: "The letter was written by an anonymous person.", exampleJp: "その手紙は匿名の人物によって書かれました。" },
  { word: "apparent", meaning: "明らかな", exampleEn: "It was apparent that he was lying.", exampleJp: "彼が嘘をついていることは明らかでした。" },
  { word: "appropriate", meaning: "適切な", exampleEn: "Jeans are not appropriate for a formal party.", exampleJp: "ジーンズは正式なパーティーには適切ではありません。" },
  { word: "arbitrary", meaning: "任意の、勝手な", exampleEn: "The teacher made an arbitrary decision.", exampleJp: "先生は勝手な決定を下しました。" },
  { word: "artificial", meaning: "人工の", exampleEn: "This drink has artificial colors in it.", exampleJp: "この飲み物には人工着色料が含まれています。" },
  { word: "awkward", meaning: "気まずい、ぎこちない", exampleEn: "There was an awkward silence in the room.", exampleJp: "部屋には気まずい沈黙がありました。" },
  { word: "barren", meaning: "不毛の、荒れ果てた", exampleEn: "Trees cannot grow on this barren land.", exampleJp: "この不毛の土地には木が育ちません。" },
  { word: "brilliant", meaning: "素晴らしい、光り輝く", exampleEn: "She had a brilliant idea to solve the problem.", exampleJp: "彼女は問題を解決するための素晴らしいアイデアを思いつきました。" },
  { word: "brutal", meaning: "残酷な", exampleEn: "The king was known for his brutal actions.", exampleJp: "その王は残酷な行いで知られていました。" },
  { word: "casual", meaning: "何気ない、偶然の", exampleEn: "We had a casual conversation about the weather.", exampleJp: "私たちは天気について何気ない会話をしました。" },
  { word: "cautious", meaning: "慎重な", exampleEn: "You must be cautious when driving in the snow.", exampleJp: "雪の中で運転するときは慎重にならなければなりません。" },
  { word: "clumsy", meaning: "不器用な", exampleEn: "I am so clumsy that I often drop my phone.", exampleJp: "私はとても不器用で、よく電話を落とします。" },
  { word: "coarse", meaning: "粗い", exampleEn: "This cloth is very coarse and uncomfortable.", exampleJp: "この布はとても粗くて不快です。" },
  { word: "coherent", meaning: "首尾一貫した", exampleEn: "His story was not coherent and hard to believe.", exampleJp: "彼の話は首尾一貫しておらず、信じがたいものでした。" },
  { word: "competent", meaning: "有能な", exampleEn: "She is a highly competent manager.", exampleJp: "彼女は非常に有能なマネージャーです。" },
  { word: "complex", meaning: "複雑な", exampleEn: "The human brain is very complex.", exampleJp: "人間の脳は非常に複雑です。" },
  { word: "compulsory", meaning: "義務の、必須の", exampleEn: "Math is a compulsory subject in our school.", exampleJp: "数学は私たちの学校で必須の科目です。" },
  { word: "concise", meaning: "簡潔な", exampleEn: "Please write a concise report, not a long one.", exampleJp: "長いものではなく、簡潔な報告書を書いてください。" },
  { word: "concrete", meaning: "具体的な", exampleEn: "We need concrete evidence to prove it.", exampleJp: "それを証明するためには具体的な証拠が必要です。" },
  { word: "conscious", meaning: "意識している", exampleEn: "I am conscious of my weak points.", exampleJp: "私は自分の弱点を意識しています。" },
  { word: "conservative", meaning: "保守的な", exampleEn: "My parents have very conservative views.", exampleJp: "私の両親は非常に保守的な考えを持っています。" },
  { word: "considerable", meaning: "かなりの、相当な", exampleEn: "He spent a considerable amount of time reading.", exampleJp: "彼は読書にかなりの時間を費やしました。" },
  { word: "contemporary", meaning: "現代の、同時代の", exampleEn: "I love contemporary art.", exampleJp: "私は現代アートが大好きです。" },
  { word: "controversial", meaning: "論争を呼ぶ", exampleEn: "Taxes are always a controversial topic.", exampleJp: "税金は常に論争を呼ぶトピックです。" },
  { word: "conventional", meaning: "従来の、型にはまった", exampleEn: "They decided to have a conventional wedding.", exampleJp: "彼らは従来の結婚式を挙げることに決めました。" },
  { word: "cruel", meaning: "残酷な", exampleEn: "It is cruel to hit small animals.", exampleJp: "小さな動物を叩くのは残酷です。" },
  { word: "curious", meaning: "好奇心の強い", exampleEn: "The curious cat looked inside the box.", exampleJp: "好奇心の強い猫が箱の中を覗き込みました。" },
  { word: "cynical", meaning: "皮肉な、冷笑的な", exampleEn: "He always makes cynical comments about politicians.", exampleJp: "彼はいつも政治家について皮肉なコメントをします。" },
  { word: "decent", meaning: "まともな、きちんとした", exampleEn: "He makes a decent living as a writer.", exampleJp: "彼は作家としてまともな生活を送っています。" },
  { word: "defective", meaning: "欠陥のある", exampleEn: "I returned the defective toy to the store.", exampleJp: "私は欠陥のあるおもちゃを店に返品しました。" },
  { word: "delicate", meaning: "繊細な、壊れやすい", exampleEn: "Please be careful with these delicate glasses.", exampleJp: "これらの繊細なグラスには気をつけてください。" },
  { word: "dense", meaning: "密集した、濃い", exampleEn: "We got lost in the dense forest.", exampleJp: "私たちは密集した森の中で迷子になりました。" },
  { word: "desperate", meaning: "絶望的な、必死の", exampleEn: "The lost hiker was in a desperate situation.", exampleJp: "迷子になったハイカーは絶望的な状況にありました。" },
  { word: "diligently", meaning: "勤勉に（副詞）", exampleEn: "She studied diligently for her exams.", exampleJp: "彼女は試験のために勤勉に勉強しました。" },

  // 常考主题名词 (Priority 4)
  { word: "access", meaning: "接近、利用する権利", exampleEn: "Only staff have access to this room.", exampleJp: "スタッフのみがこの部屋にアクセス（入室）できます。" },
  { word: "accommodation", meaning: "宿泊施設", exampleEn: "We booked cheap accommodation for our trip.", exampleJp: "私たちは旅行のために安い宿泊施設を予約しました。" },
  { word: "accuracy", meaning: "正確さ", exampleEn: "The machine cuts metal with great accuracy.", exampleJp: "その機械は高い正確さで金属を切ります。" },
  { word: "agriculture", meaning: "農業", exampleEn: "Agriculture is important for this country's economy.", exampleJp: "農業はこの国の経済にとって重要です。" },
  { word: "altitude", meaning: "高度、標高", exampleEn: "The plane is flying at a high altitude.", exampleJp: "飛行機は高い高度を飛んでいます。" },
  { word: "ancestor", meaning: "祖先", exampleEn: "His ancestors came from Italy.", exampleJp: "彼の祖先はイタリアから来ました。" },
  { word: "appetite", meaning: "食欲", exampleEn: "Swimming gave me a big appetite.", exampleJp: "水泳をして食欲が出ました。" },
  { word: "atmosphere", meaning: "大気、雰囲気", exampleEn: "The earth's atmosphere protects us.", exampleJp: "地球の大気は私たちを守っています。" },
  { word: "authority", meaning: "権威、権力", exampleEn: "The police have the authority to arrest criminals.", exampleJp: "警察は犯罪者を逮捕する権限を持っています。" },
  { word: "budget", meaning: "予算", exampleEn: "I need to plan my monthly budget.", exampleJp: "私は毎月の予算を計画する必要があります。" },
  { word: "candidate", meaning: "候補者", exampleEn: "There are three candidates for the job.", exampleJp: "その仕事には3人の候補者がいます。" },
  { word: "capacity", meaning: "収容能力、能力", exampleEn: "The theater has a seating capacity of 500.", exampleJp: "その劇場は500人の座席収容能力があります。" },
  { word: "category", meaning: "種類、範疇", exampleEn: "Tomato belongs to the fruit category.", exampleJp: "トマトは果物のカテゴリーに属します。" },
  { word: "circumstance", meaning: "状況、事情", exampleEn: "Under no circumstances should you open this door.", exampleJp: "いかなる状況でもこのドアを開けてはいけません。" },
  { word: "colleague", meaning: "同僚", exampleEn: "I went out for lunch with my colleagues.", exampleJp: "私は同僚たちとランチに出かけました。" },
  { word: "committe", meaning: "委員会", exampleEn: "The committee will make a decision tomorrow.", exampleJp: "委員会は明日決定を下します。" },
  { word: "commodity", meaning: "商品、日用品", exampleEn: "Oil is an important global commodity.", exampleJp: "石油は重要な世界の商品です。" },
  { word: "conflict", meaning: "対立、紛争", exampleEn: "There is a conflict between the two teams.", exampleJp: "2つのチームの間に対立があります。" },
  { word: "consequence", meaning: "結果、影響", exampleEn: "You must accept the consequences of your action.", exampleJp: "あなたは自分の行動の結果を受け入れなければなりません。" },
  { word: "conservation", meaning: "保護、保存", exampleEn: "Wildlife conservation is necessary for our future.", exampleJp: "野生動物の保護は私たちの未来に必要です。" },

  // 核心惯用语 / 动词短语 (Priority 2)
  { word: "abide by", meaning: "〜に従う", exampleEn: "All players must abide by the rules.", exampleJp: "すべての選手は規則に従わなければなりません。" },
  { word: "adhere to", meaning: "〜に固執する、くっつく", exampleEn: "You should adhere to your original plan.", exampleJp: "あなたは最初の計画に固執するべきです。" },
  { word: "allow for", meaning: "〜を考慮に入れる", exampleEn: "We must allow for traffic delays.", exampleJp: "私たちは交通の遅れを考慮に入れなければなりません。" },
  { word: "amount to", meaning: "総計〜になる、結局〜になる", exampleEn: "The bill amounted to 100 dollars.", exampleJp: "請求書は総計100ドルになりました。" },
  { word: "apply for", meaning: "〜に申し込む", exampleEn: "I am going to apply for a new job.", exampleJp: "私は新しい仕事に申し込むつもりです。" },
  { word: "approve of", meaning: "〜に賛成する", exampleEn: "My mother does not approve of my dyed hair.", exampleJp: "母は私の染めた髪に賛成していません。" },
  { word: "back up", meaning: "〜を支持する、後援する", exampleEn: "I will back up your story.", exampleJp: "私があなたの話を支持（裏付け）します。" },
  { word: "break down", meaning: "故障する", exampleEn: "My car broke down on the highway.", exampleJp: "私の車が高速道路で故障しました。" },
  { word: "bring up", meaning: "〜を育てる、〜を話題に出す", exampleEn: "She brought up three children by herself.", exampleJp: "彼女は一人で3人の子供を育てました。" },
  { word: "call off", meaning: "〜を中止する", exampleEn: "They had to call off the baseball game.", exampleJp: "彼らは野球の試合を中止しなければなりませんでした。" },
  { word: "catch up with", meaning: "〜に追いつく", exampleEn: "Run fast, and you can catch up with him.", exampleJp: "速く走れば、彼に追いつくことができます。" },
  { word: "come across", meaning: "〜に偶然出会う", exampleEn: "I came across an old photo yesterday.", exampleJp: "昨日、古い写真を偶然見つけました。" },
  { word: "count on", meaning: "〜を頼りにする", exampleEn: "You can always count on my help.", exampleJp: "いつでも私の助けを頼りにしていいですよ。" },
  { word: "cut down on", meaning: "〜を減らす", exampleEn: "I need to cut down on sugar to lose weight.", exampleJp: "体重を減らすために砂糖を減らす必要があります。" },
  { word: "deal with", meaning: "〜に対処する、扱う", exampleEn: "He is good at dealing with angry customers.", exampleJp: "彼は怒っている客に対処するのが得意です。" },
  { word: "do away with", meaning: "〜を廃止する", exampleEn: "The school should do away with that stupid rule.", exampleJp: "学校はそのばかげた規則を廃止するべきです。" },
  { word: "drop by", meaning: "ふらりと立ち寄る", exampleEn: "Please drop by my house anytime.", exampleJp: "いつでも私の家にふらりと立ち寄ってください。" },
  { word: "end up", meaning: "結局〜になる", exampleEn: "If you don't study, you will end up failing.", exampleJp: "勉強しないと、結局は失敗することになります。" },
  { word: "fall back on", meaning: "〜に頼る（最後の手段として）", exampleEn: "He has some savings to fall back on.", exampleJp: "彼には頼りにできる貯金がいくらかあります。" },
  { word: "fill in for", meaning: "〜の代理を務める", exampleEn: "Can you fill in for me tomorrow?", exampleJp: "明日、私の代理を務めてくれますか？" },
  { word: "get along with", meaning: "〜と仲良くやる", exampleEn: "I get along with my new roommate.", exampleJp: "私は新しいルームメイトと仲良くやっています。" },
  { word: "get over", meaning: "〜から回復する、乗り越える", exampleEn: "It took a long time to get over the flu.", exampleJp: "インフルエンザから回復するのに長い時間がかかりました。" },
  { word: "give in", meaning: "降参する、屈する", exampleEn: "The soldiers fought hard but finally gave in.", exampleJp: "兵士たちは激しく戦いましたが、最後には降参しました。" },
  { word: "go over", meaning: "〜をよく調べる、復習する", exampleEn: "Let's go over the test results together.", exampleJp: "一緒にテストの結果を復習しましょう。" },
  { word: "hand in", meaning: "〜を提出する", exampleEn: "Please hand in your homework by Friday.", exampleJp: "金曜日までに宿題を提出してください。" },
  { word: "hold back", meaning: "〜をこらえる、抑える", exampleEn: "She tried to hold back her tears.", exampleJp: "彼女は涙をこらえようとしました。" },
  { word: "keep up with", meaning: "〜についていく", exampleEn: "It is hard to keep up with the latest news.", exampleJp: "最新のニュースについていくのは大変です。" },
  { word: "leave out", meaning: "〜を省く、除外する", exampleEn: "Don't leave out any details in your report.", exampleJp: "レポートで詳細を省かないでください。" },
  { word: "live up to", meaning: "（期待など）に応える", exampleEn: "He tried to live up to his parents' expectations.", exampleJp: "彼は両親の期待に応えようとしました。" },
  { word: "look down on", meaning: "〜を見下す", exampleEn: "You should not look down on poor people.", exampleJp: "貧しい人々を見下すべきではありません。" },
  { word: "make out", meaning: "〜を理解する、判読する", exampleEn: "I cannot make out what is written here.", exampleJp: "ここに何が書かれているのか判読できません。" },
  { word: "pass away", meaning: "亡くなる", exampleEn: "My lovely dog passed away last night.", exampleJp: "私の可愛い犬が昨夜亡くなりました。" },
  { word: "put off", meaning: "〜を延期する", exampleEn: "We decided to put off the meeting until next week.", exampleJp: "私たちは会議を来週まで延期することに決めました。" },
  { word: "put up with", meaning: "〜を我慢する", exampleEn: "I cannot put up with the heat anymore.", exampleJp: "もうこの暑さを我慢できません。" },
  { word: "show off", meaning: "見せびらかす", exampleEn: "He drove his new car just to show off.", exampleJp: "彼はただ見せびらかすために新車を運転しました。" },
  { word: "stand out", meaning: "目立つ", exampleEn: "Her bright red hat makes her stand out.", exampleJp: "彼女の明るい赤い帽子が彼女を目立たせています。" },
  { word: "take after", meaning: "〜に似ている", exampleEn: "She takes after her mother in looks.", exampleJp: "彼女は外見が母親に似ています。" },
  { word: "take over", meaning: "〜を引き継ぐ", exampleEn: "He will take over the business from his father.", exampleJp: "彼は父親からビジネスを引き継ぐ予定です。" },
  { word: "turn down", meaning: "〜を拒絶する、（音量などを）下げる", exampleEn: "He turned down the job offer.", exampleJp: "彼はその仕事のオファーを断りました。" },
  { word: "wear out", meaning: "〜をすり減らす、疲れ果てさせる", exampleEn: "My shoes wore out completely.", exampleJp: "私の靴は完全にすり減りました。" },


// --- 準一級核心词库 第一批 (补充剩余的 211 - 250) ---
  // 补充高频核心动词
  { word: "contribute", meaning: "貢献する、寄付する", exampleEn: "She contributed 10 dollars to the charity.", exampleJp: "彼女は慈善団体に10ドルを寄付しました。" },
  { word: "convince", meaning: "納得させる", exampleEn: "I convinced him to buy the red car.", exampleJp: "私は彼を説得して赤い車を買わせました。" },
  { word: "coordinate", meaning: "調整する", exampleEn: "He will coordinate the school festival this year.", exampleJp: "彼は今年の学園祭を調整（取りまとめ）します。" },
  { word: "crawl", meaning: "這う", exampleEn: "The baby learned to crawl on the floor.", exampleJp: "赤ちゃんは床を這うことを覚えました。" },
  { word: "dash", meaning: "突進する、急いで行く", exampleEn: "I had to dash to the station to catch the train.", exampleJp: "電車に間に合うように駅へ突進しなければ（急いで行かなければ）なりませんでした。" },
  { word: "define", meaning: "定義する", exampleEn: "Can you define this difficult word?", exampleJp: "この難しい単語を定義できますか？" },
  { word: "delay", meaning: "遅らせる", exampleEn: "Heavy rain delayed the baseball game.", exampleJp: "大雨が野球の試合を遅らせました。" },
  { word: "deserve", meaning: "値する", exampleEn: "You worked hard, so you deserve a rest.", exampleJp: "一生懸命働いたのだから、あなたは休むに値します。" },
  { word: "distinguish", meaning: "区別する", exampleEn: "It is hard to distinguish the twin brothers.", exampleJp: "その双子の兄弟を区別するのは難しいです。" },
  { word: "encounter", meaning: "遭遇する", exampleEn: "We encountered a big bear in the woods.", exampleJp: "私たちは森の中で大きなクマに遭遇しました。" },

  // 补充高频核心名词
  { word: "crisis", meaning: "危機", exampleEn: "The country is facing a water crisis.", exampleJp: "その国は水危機に直面しています。" },
  { word: "dawn", meaning: "夜明け", exampleEn: "The birds start singing at dawn.", exampleJp: "鳥たちは夜明けに歌い始めます。" },
  { word: "defect", meaning: "欠陥", exampleEn: "This new machine has a serious defect.", exampleJp: "この新しい機械には深刻な欠陥があります。" },
  { word: "destination", meaning: "目的地", exampleEn: "Hawaii is our final holiday destination.", exampleJp: "ハワイが私たちの最終的な休日の目的地です。" },
  { word: "diameter", meaning: "直径", exampleEn: "The coin has a diameter of two centimeters.", exampleJp: "そのコインは直径2センチメートルです。" },
  { word: "disaster", meaning: "災害", exampleEn: "The earthquake was a terrible disaster.", exampleJp: "その地震は恐ろしい災害でした。" },
  { word: "disease", meaning: "病気", exampleEn: "Washing hands can stop the spread of disease.", exampleJp: "手を洗うことで病気の広がりを止めることができます。" },
  { word: "equivalent", meaning: "同等のもの", exampleEn: "One dollar is the equivalent of 100 cents.", exampleJp: "1ドルは100セントと同等です。" },
  { word: "era", meaning: "時代", exampleEn: "We live in the era of the internet.", exampleJp: "私たちはインターネットの時代に生きています。" },
  { word: "estimate", meaning: "見積もり", exampleEn: "The builder gave me an estimate for the house.", exampleJp: "建築業者は家について私に見積もりを出しました。" },
  { word: "evidence", meaning: "証拠", exampleEn: "The police found no evidence of a crime.", exampleJp: "警察は犯罪の証拠を何も見つけませんでした。" },
  { word: "exception", meaning: "例外", exampleEn: "Everyone must go to bed at 9, with no exceptions.", exampleJp: "誰もが9時に寝なければなりません、例外はありません。" },
  { word: "excuse", meaning: "言い訳", exampleEn: "He made a bad excuse for being late.", exampleJp: "彼は遅刻したことについてひどい言い訳をしました。" },
  { word: "fatigue", meaning: "疲労", exampleEn: "The long flight caused great fatigue.", exampleJp: "長時間のフライトが大きな疲労を引き起こしました。" },
  { word: "fee", meaning: "料金", exampleEn: "You must pay a fee to enter the park.", exampleJp: "公園に入るには料金を支払わなければなりません。" },
  { word: "flock", meaning: "群れ", exampleEn: "A large flock of birds flew over the tree.", exampleJp: "大きな鳥の群れが木の上を飛んでいきました。" },
  { word: "fund", meaning: "資金", exampleEn: "We need more funds to build the school.", exampleJp: "学校を建てるためにもっと資金が必要です。" },
  { word: "fuss", meaning: "大騒ぎ", exampleEn: "The little boy made a fuss about his broken toy.", exampleJp: "小さな男の子は壊れたおもちゃについて大騒ぎしました。" },
  { word: "gap", meaning: "隙間、格差", exampleEn: "There is a big gap between the rich and the poor.", exampleJp: "豊かな人と貧しい人の間には大きな格差があります。" },
  { word: "glance", meaning: "ちらりと見ること", exampleEn: "He took a quick glance at his watch.", exampleJp: "彼は時計をちらりと見ました。" },

  // 补充高频动词短语 / 惯用语
  { word: "give away", meaning: "無料で与える、秘密を漏らす", exampleEn: "The store gave away free apples today.", exampleJp: "その店は今日、無料のりんごを与えました。" },
  { word: "go along with", meaning: "〜に賛成する", exampleEn: "I will go along with your plan.", exampleJp: "私はあなたの計画に賛成します。" },
  { word: "hang up", meaning: "電話を切る", exampleEn: "Do not hang up the phone yet.", exampleJp: "まだ電話を切らないでください。" },
  { word: "lay out", meaning: "広げる、設計する", exampleEn: "He laid out the map on the table.", exampleJp: "彼はテーブルの上に地図を広げました。" },
  { word: "leave behind", meaning: "置き去りにする", exampleEn: "Don't leave your umbrella behind.", exampleJp: "傘を置き忘れないでください。" },
  { word: "look back on", meaning: "〜を振り返る", exampleEn: "Old people often look back on their youth.", exampleJp: "お年寄りはよく若かった頃を振り返ります。" },
  { word: "look over", meaning: "〜に目を通す", exampleEn: "Please look over this document carefully.", exampleJp: "この書類に注意深く目を通してください。" },
  { word: "make up", meaning: "でっち上げる", exampleEn: "He made up a story about a ghost.", exampleJp: "彼は幽霊についての話をでっち上げました。" },
  { word: "pass out", meaning: "気を失う", exampleEn: "It was so hot that she passed out.", exampleJp: "とても暑かったので、彼女は気を失いました。" },
  { word: "point to", meaning: "〜を指し示す", exampleEn: "All the facts point to him as the thief.", exampleJp: "すべての事実が泥棒として彼を指し示しています。" },

  // --- Priority 3: 高频核心动词 (251 - 330) ---
  { word: "multiply", meaning: "増やす、繁殖する", exampleEn: "Rabbits multiply very quickly.", exampleJp: "ウサギはとても速く繁殖します。" },
  { word: "negotiate", meaning: "交渉する", exampleEn: "The two bosses negotiated a new price.", exampleJp: "二人のボスは新しい価格を交渉しました。" },
  { word: "overcome", meaning: "克服する", exampleEn: "She overcame her fear of the dark.", exampleJp: "彼女は暗闇への恐怖を克服しました。" },
  { word: "perceive", meaning: "知覚する、気づく", exampleEn: "Cats can perceive things in the dark.", exampleJp: "猫は暗闇の中で物事に気づく（知覚する）ことができます。" },
  { word: "predict", meaning: "予測する", exampleEn: "The weatherman predicted rain for tomorrow.", exampleJp: "天気予報士は明日の雨を予測しました。" },
  { word: "prevail", meaning: "普及する、勝つ", exampleEn: "Justice will always prevail in the end.", exampleJp: "最後には常に正義が勝ちます。" },
  { word: "prohibit", meaning: "禁止する", exampleEn: "The school prohibits running in the hall.", exampleJp: "学校は廊下を走ることを禁止しています。" },
  { word: "pursue", meaning: "追求する、追跡する", exampleEn: "The police pursued the fast car.", exampleJp: "警察は速い車を追跡しました。" },
  { word: "quote", meaning: "引用する", exampleEn: "He quoted a famous line from the movie.", exampleJp: "彼は映画の有名なセリフを引用しました。" },
  { word: "rebel", meaning: "反逆する", exampleEn: "The angry workers rebelled against the boss.", exampleJp: "怒った労働者たちはボスに反逆しました。" },
  { word: "recall", meaning: "思い出す", exampleEn: "I cannot recall his name.", exampleJp: "私は彼の名前を思い出せません。" },
  { word: "register", meaning: "登録する", exampleEn: "You must register to join the club.", exampleJp: "クラブに参加するには登録しなければなりません。" },
  { word: "relieve", meaning: "和らげる、安心させる", exampleEn: "This medicine will relieve your headache.", exampleJp: "この薬はあなたの頭痛を和らげます。" },
  { word: "resolve", meaning: "解決する、決心する", exampleEn: "We must resolve this problem quickly.", exampleJp: "私たちはこの問題を早く解決しなければなりません。" },
  { word: "restore", meaning: "修復する、回復させる", exampleEn: "They restored the old painting perfectly.", exampleJp: "彼らは古い絵を完璧に修復しました。" },
  { word: "restrict", meaning: "制限する", exampleEn: "The park restricts the number of visitors.", exampleJp: "公園は訪問者の数を制限しています。" },
  { word: "retain", meaning: "保持する、保つ", exampleEn: "This cup retains heat very well.", exampleJp: "このカップは熱をとてもよく保ちます。" },
  { word: "reverse", meaning: "逆にする", exampleEn: "He reversed his car into the garage.", exampleJp: "彼は車をバックで（逆に）ガレージに入れました。" },
  { word: "revise", meaning: "修正する、改訂する", exampleEn: "The writer revised her book.", exampleJp: "作家は自分の本を改訂しました。" },
  { word: "ruin", meaning: "台無しにする、破壊する", exampleEn: "The heavy rain ruined our picnic.", exampleJp: "大雨が私たちのピクニックを台無しにしました。" },
  { word: "sacrifice", meaning: "犠牲にする", exampleEn: "Mothers often sacrifice their time for children.", exampleJp: "母親はよく子供のために自分の時間を犠牲にします。" },
  { word: "scan", meaning: "注意深く調べる、ざっと見る", exampleEn: "He scanned the room to find his friend.", exampleJp: "彼は友達を見つけるために部屋をざっと見ました。" },
  { word: "scatter", meaning: "ばらまく、散らす", exampleEn: "The wind scattered the leaves everywhere.", exampleJp: "風が葉をあちこちに散らしました。" },
  { word: "scold", meaning: "叱る", exampleEn: "The teacher scolded the boy for fighting.", exampleJp: "先生は喧嘩をしたことでその男の子を叱りました。" },
  { word: "scrape", meaning: "こすり落とす", exampleEn: "I scraped the ice off the window.", exampleJp: "私は窓から氷をこすり落としました。" },
  { word: "seal", meaning: "封をする", exampleEn: "She sealed the letter with tape.", exampleJp: "彼女はテープで手紙に封をしました。" },
  { word: "seize", meaning: "つかむ、奪う", exampleEn: "The dog seized the bone in its mouth.", exampleJp: "犬は骨を口でつかみました。" },
  { word: "shrink", meaning: "縮む", exampleEn: "My wool sweater shrank in the hot water.", exampleJp: "私のウールのセーターは熱いお湯で縮みました。" },
  { word: "sigh", meaning: "ため息をつく", exampleEn: "She sighed deeply when she saw the test.", exampleJp: "彼女はテストを見たとき、深くため息をつきました。" },
  { word: "smash", meaning: "粉砕する", exampleEn: "The ball smashed the window.", exampleJp: "ボールが窓を粉砕しました。" },
  { word: "soar", meaning: "急上昇する、空高く飛ぶ", exampleEn: "The eagle soared high in the sky.", exampleJp: "ワシは空高く飛びました。" },
  { word: "soothe", meaning: "なだめる、和らげる", exampleEn: "Soft music can soothe a crying baby.", exampleJp: "静かな音楽は泣いている赤ちゃんをなだめることができます。" },
  { word: "spoil", meaning: "台無しにする、甘やかす", exampleEn: "Do not let one bad apple spoil the rest.", exampleJp: "一つの悪いりんごに他のものを台無しにさせてはいけません。" },
  { word: "squeeze", meaning: "絞る", exampleEn: "He squeezed the lemon into his tea.", exampleJp: "彼はレモンをお茶に絞りました。" },
  { word: "stare", meaning: "じっと見つめる", exampleEn: "It is rude to stare at strangers.", exampleJp: "見知らぬ人をじっと見つめるのは失礼です。" },
  { word: "starve", meaning: "飢える", exampleEn: "The poor animals starved during the winter.", exampleJp: "かわいそうな動物たちは冬の間に飢えました。" },
  { word: "steer", meaning: "操縦する、導く", exampleEn: "He steered the boat away from the rocks.", exampleJp: "彼は岩から離れるようにボートを操縦しました。" },
  { word: "strain", meaning: "負担をかける、引っ張る", exampleEn: "Reading in the dark strains your eyes.", exampleJp: "暗いところで本を読むと目に負担がかかります。" },
  { word: "stumble", meaning: "つまずく", exampleEn: "I stumbled over a rock and fell down.", exampleJp: "私は岩につまずいて転びました。" },
  { word: "submit", meaning: "提出する、服従する", exampleEn: "You must submit your report by tomorrow.", exampleJp: "明日までにレポートを提出しなければなりません。" },
  { word: "subscribe", meaning: "定期購読する", exampleEn: "I subscribe to a science magazine.", exampleJp: "私は科学雑誌を定期購読しています。" },
  { word: "suppress", meaning: "抑える、鎮圧する", exampleEn: "She could not suppress her laughter.", exampleJp: "彼女は笑いを抑えることができませんでした。" },
  { word: "surrender", meaning: "降伏する、明け渡す", "exampleEn": "The thief surrendered to the police.", exampleJp: "泥棒は警察に降伏しました。" },
  { word: "survive", meaning: "生き残る", exampleEn: "Camels can survive without water for days.", exampleJp: "ラクダは水なしで何日も生き残ることができます。" },
  { word: "swallow", meaning: "飲み込む", exampleEn: "He swallowed the pill with a glass of water.", exampleJp: "彼はコップ一杯の水と一緒に薬を飲み込みました。" },
  { word: "swear", meaning: "誓う、ののしる", exampleEn: "I swear to tell the truth.", exampleJp: "私は真実を話すことを誓います。" },
  { word: "sweep", meaning: "掃く", exampleEn: "Please sweep the floor before guests arrive.", exampleJp: "お客さんが来る前に床を掃いてください。" },
  { word: "swell", meaning: "腫れる、膨らむ", exampleEn: "My ankle swelled up after I fell.", exampleJp: "転んだ後、私の足首が腫れました。" },
  { word: "tease", meaning: "からかう", exampleEn: "The big boys teased the little boy.", exampleJp: "大きな男の子たちが小さな男の子をからかいました。" },
  { word: "thrill", meaning: "わくわくさせる", exampleEn: "The roller coaster thrilled the children.", exampleJp: "ジェットコースターは子供たちをわくわくさせました。" },
  { word: "toss", meaning: "軽く投げる", exampleEn: "Toss the ball to me!", exampleJp: "ボールを私に（軽く）投げて！" },
  { word: "trace", meaning: "たどる、なぞる", exampleEn: "The police traced the lost dog to a park.", exampleJp: "警察は迷子になった犬を公園までたどりました。" },
  { word: "trail", meaning: "引きずる、後を追う", exampleEn: "The bride's long dress trailed on the floor.", exampleJp: "花嫁の長いドレスが床に引きずられていました。" },
  { word: "transform", meaning: "変形させる、変える", exampleEn: "The magic wand transformed the frog into a prince.", exampleJp: "魔法の杖がカエルを王子に変えました。" },
  { word: "transmit", meaning: "送信する、伝染させる", exampleEn: "The tower transmits TV signals.", exampleJp: "その塔はテレビの信号を送信しています。" },
  { word: "transport", meaning: "輸送する", exampleEn: "Trucks transport food to the city.", exampleJp: "トラックが食べ物を街へ輸送します。" },
  { word: "trap", meaning: "罠にかける、閉じ込める", exampleEn: "The hunter trapped a bear in the forest.", exampleJp: "ハンターは森でクマを罠にかけました。" },
  { word: "tremble", meaning: "震える", exampleEn: "He trembled with cold in the snow.", exampleJp: "彼は雪の中で寒さで震えました。" },
  { word: "urge", meaning: "強く促す", exampleEn: "I urge you to study harder.", exampleJp: "私はあなたにもっと一生懸命勉強するよう強く促します。" },
  { word: "vanish", meaning: "消える", exampleEn: "The magician made the rabbit vanish.", exampleJp: "マジシャンはウサギを消えさせました。" },
  { word: "vary", meaning: "異なる、変わる", exampleEn: "Prices vary from store to store.", exampleJp: "価格は店によって異なります。" },
  { word: "wander", meaning: "歩き回る、さまよう", exampleEn: "We wandered around the old town.", exampleJp: "私たちは古い町を歩き回りました。" },
  { word: "warn", meaning: "警告する", exampleEn: "The sign warns people about the bad dog.", exampleJp: "その標識は猛犬について人々に警告しています。" },
  { word: "weave", meaning: "織る", exampleEn: "She weaves beautiful baskets from grass.", exampleJp: "彼女は草から美しいバスケットを織ります。" },
  { word: "weep", meaning: "泣く", exampleEn: "The little girl wept because she lost her doll.", exampleJp: "小さな女の子は人形をなくしたので泣きました。" },
  { word: "weigh", meaning: "重さを量る", exampleEn: "The nurse weighed the baby.", exampleJp: "看護師は赤ちゃんの重さを量りました。" },
  { word: "whip", meaning: "むち打つ", exampleEn: "The rider whipped his horse to run faster.", exampleJp: "乗り手はもっと速く走らせるために馬をむち打ちました。" },
  { word: "whisper", meaning: "ささやく", exampleEn: "She whispered a secret in my ear.", exampleJp: "彼女は私の耳に秘密をささやきました。" },
  { word: "wipe", meaning: "拭く", exampleEn: "Please wipe the table with a wet cloth.", exampleJp: "濡れた布でテーブルを拭いてください。" },
  { word: "wrap", meaning: "包む", exampleEn: "I wrapped the gift in red paper.", exampleJp: "私はプレゼントを赤い紙で包みました。" },
  { word: "wreck", meaning: "難破させる、破壊する", exampleEn: "The storm wrecked the small boat.", exampleJp: "嵐が小さなボートを破壊しました。" },
  { word: "yield", meaning: "産出する、屈服する", exampleEn: "This farm yields a lot of corn.", exampleJp: "この農場はたくさんのトウモロコシを産出します。" },
  { word: "abandon", meaning: "見捨てる、放棄する", exampleEn: "They had to abandon the sinking ship.", exampleJp: "彼らは沈みゆく船を見捨てなければなりませんでした。" },
  { word: "absorb", meaning: "吸収する", exampleEn: "Sponges absorb water very well.", exampleJp: "スポンジは水をとてもよく吸収します。" },
  { word: "abuse", meaning: "乱用する、虐待する", exampleEn: "It is a crime to abuse children.", exampleJp: "子供を虐待するのは犯罪です。" },
  { word: "accommodate", meaning: "収容する", exampleEn: "This hotel can accommodate 500 guests.", exampleJp: "このホテルは500人の客を収容できます。" },
  { word: "accompany", meaning: "同行する", exampleEn: "I will accompany you to the hospital.", exampleJp: "私が病院まであなたに同行します。" },
  { word: "accomplish", meaning: "達成する", exampleEn: "You can accomplish anything if you try hard.", exampleJp: "一生懸命努力すれば、何でも達成できます。" },
  { word: "accuse", meaning: "非難する、告発する", exampleEn: "She accused him of stealing her money.", exampleJp: "彼女は彼女のお金を盗んだことで彼を非難しました。" },

  // --- Priority 4: 核心形容词 (331 - 375) ---
  { word: "massive", meaning: "巨大な、大規模な", exampleEn: "A massive rock fell on the road.", exampleJp: "巨大な岩が道路に落ちました。" },
  { word: "miniature", meaning: "小型の", exampleEn: "He collects miniature cars.", exampleJp: "彼は小型の車を集めています。" },
  { word: "minor", meaning: "小さな、重要でない", exampleEn: "I made a minor mistake on the test.", exampleJp: "テストで小さなミスをしました。" },
  { word: "miserable", meaning: "惨めな、悲惨な", exampleEn: "I feel miserable because I have a bad cold.", exampleJp: "ひどい風邪をひいているので、私は惨めな気分です。" },
  { word: "moderate", meaning: "適度な、中くらいの", exampleEn: "Moderate exercise is good for your health.", exampleJp: "適度な運動は健康に良いです。" },
  { word: "modest", meaning: "謙虚な、控えめな", exampleEn: "He is a modest man and never boasts.", exampleJp: "彼は謙虚な人で、決して自慢しません。" },
  { word: "mutual", meaning: "相互の、共通の", exampleEn: "They have a mutual interest in music.", exampleJp: "彼らは音楽という共通の興味を持っています。" },
  { word: "naked", meaning: "裸の", exampleEn: "The naked baby played in the water.", exampleJp: "裸の赤ちゃんが水の中で遊んでいました。" },
  { word: "nasty", meaning: "不快な、意地悪な", exampleEn: "That medicine has a nasty smell.", exampleJp: "その薬は不快な匂いがします。" },
  { word: "neat", meaning: "きちんとした", exampleEn: "Her room is always clean and neat.", exampleJp: "彼女の部屋はいつも清潔できちんとしています。" },
  { word: "negative", meaning: "否定的な、マイナスの", exampleEn: "Do not have a negative attitude.", exampleJp: "否定的な態度を持たないでください。" },
  { word: "neutral", meaning: "中立の", exampleEn: "Switzerland remained neutral during the war.", exampleJp: "スイスは戦争中、中立を保ちました。" },
  { word: "noble", meaning: "気高い、貴族の", exampleEn: "Helping poor people is a noble act.", exampleJp: "貧しい人々を助けることは気高い行動です。" },
  { word: "notorious", meaning: "悪名高い", exampleEn: "The town is notorious for its bad weather.", exampleJp: "その町は悪天候で悪名高いです。" },
  { word: "nuclear", meaning: "原子力の", exampleEn: "They produce electricity in a nuclear power plant.", exampleJp: "彼らは原子力発電所で電気を作ります。" },
  { word: "null", meaning: "無効の", exampleEn: "The contract is now null and void.", exampleJp: "その契約は今や無効です。" },
  { word: "numerous", meaning: "非常に多くの", exampleEn: "He has received numerous awards.", exampleJp: "彼は非常に多くの賞を受け取っています。" },
  { word: "obscure", meaning: "不明瞭な、無名の", exampleEn: "The meaning of his poem is obscure.", exampleJp: "彼の詩の意味は不明瞭です。" },
  { word: "obsolete", meaning: "時代遅れの、使われなくなった", exampleEn: "Typewriters are now obsolete.", exampleJp: "タイプライターは今や時代遅れ（使われないもの）です。" },
  { word: "odd", meaning: "奇妙な、奇数の", exampleEn: "That is an odd looking house.", exampleJp: "それは奇妙な見た目の家です。" },
  { word: "optimal", meaning: "最適な", exampleEn: "This temperature is optimal for growing plants.", exampleJp: "この温度は植物を育てるのに最適です。" },
  { word: "oral", meaning: "口頭の", exampleEn: "We have an oral test in English class tomorrow.", exampleJp: "明日の英語の授業で口頭テストがあります。" },
  { word: "ordinary", meaning: "普通の、ありふれた", exampleEn: "He is just an ordinary high school student.", exampleJp: "彼はただの普通の高校生です。" },
  { word: "outstanding", meaning: "目立った、傑出した", exampleEn: "She gave an outstanding performance in the play.", exampleJp: "彼女は劇で傑出した演技をしました。" },
  { word: "overall", meaning: "全体的な", exampleEn: "The overall cost will be 100 dollars.", exampleJp: "全体的な費用は100ドルになります。" },
  { word: "pale", meaning: "青白い、淡い", exampleEn: "He looks pale because he is sick.", exampleJp: "彼は病気なので顔色が青白く見えます。" },
  { word: "partial", meaning: "部分的な、不公平な", exampleEn: "I only have a partial memory of the event.", exampleJp: "私はその出来事の部分的な記憶しかありません。" },
  { word: "passive", meaning: "受動的な、消極的な", exampleEn: "You should not be passive in class.", exampleJp: "授業では消極的であってはいけません。" },
  { word: "peculiar", meaning: "独特の、妙な", exampleEn: "This cheese has a peculiar taste.", exampleJp: "このチーズには独特の味があります。" },
  { word: "permanent", meaning: "永久の", exampleEn: "Nothing in this world is permanent.", exampleJp: "この世界に永久なものは何もありません。" },
  { word: "perpetual", meaning: "絶え間ない", exampleEn: "I am tired of his perpetual complaining.", exampleJp: "私は彼の絶え間ない文句にうんざりしています。" },
  { word: "plain", meaning: "明白な、質素な、平原", exampleEn: "The instructions are written in plain English.", exampleJp: "指示は明白な（簡単な）英語で書かれています。" },
  { word: "plausible", meaning: "もっともらしい", exampleEn: "His excuse sounded plausible.", exampleJp: "彼の言い訳はもっともらしく聞こえました。" },
  { word: "polite", meaning: "礼儀正しい", exampleEn: "You must be polite to older people.", exampleJp: "年上の人には礼儀正しくしなければなりません。" },
  { word: "poor", meaning: "貧しい、下手な", exampleEn: "He is very poor at playing tennis.", exampleJp: "彼はテニスをするのがとても下手です。" },
  { word: "positive", meaning: "前向きな、確信して", exampleEn: "I am positive that we will win.", exampleJp: "私たちが勝つと確信しています。" },
  { word: "potential", meaning: "潜在的な、可能性のある", exampleEn: "We have to identify potential dangers.", exampleJp: "私たちは潜在的な危険を特定しなければなりません。" },
  { word: "precious", meaning: "貴重な", exampleEn: "Time is very precious, so do not waste it.", exampleJp: "時間はとても貴重なので、無駄にしないでください。" },
  { word: "precise", meaning: "正確な", exampleEn: "Please give me precise details about the event.", exampleJp: "そのイベントについての正確な詳細を教えてください。" },
  { word: "pregnant", meaning: "妊娠している", exampleEn: "My sister is six months pregnant.", exampleJp: "私の姉は妊娠6ヶ月です。" },
  { word: "premature", meaning: "時期尚早の、早産", exampleEn: "It is premature to talk about marriage.", exampleJp: "結婚について話すのは時期尚早です。" },
  { word: "previous", meaning: "以前の", exampleEn: "I liked my previous job better.", exampleJp: "私は以前の仕事の方が好きでした。" },
  { word: "primary", meaning: "主要な、初等の", exampleEn: "His primary goal is to become a doctor.", exampleJp: "彼の主要な目標は医者になることです。" },
  { word: "primitive", meaning: "原始的な", exampleEn: "Early humans used primitive stone tools.", exampleJp: "初期の人類は原始的な石器を使いました。" },
  { word: "prior", meaning: "前の、先の", exampleEn: "I have a prior arrangement today.", exampleJp: "今日は先約（前の予定）があります。" },
  

  // --- Priority 4 继续: 核心形容词 (376 - 410) ---
  { word: "private", meaning: "私有の、個人的な", exampleEn: "This is a private beach for hotel guests only.", exampleJp: "これはホテルの宿泊客専用のプライベートビーチです。" },
  { word: "probable", meaning: "起こりそうな、有望な", exampleEn: "It is probable that it will snow tonight.", exampleJp: "今夜は雪が降りそうです。" },
  { word: "profound", meaning: "深い、重大な", exampleEn: "The book had a profound effect on me.", exampleJp: "その本は私に深い影響を与えました。" },
  { word: "prompt", meaning: "迅速な", exampleEn: "Thank you for your prompt reply.", exampleJp: "迅速な返信をありがとうございます。" },
  { word: "prone", meaning: "〜しがちな", exampleEn: "Tired drivers are prone to make mistakes.", exampleJp: "疲れた運転手はミスをしがちです。" },
  { word: "proper", meaning: "適切な、ふさわしい", exampleEn: "You need proper tools to fix the bike.", exampleJp: "自転車を修理するには適切な道具が必要です。" },
  { word: "proud", meaning: "誇りに思う", exampleEn: "I am proud of my clever son.", exampleJp: "私は賢い息子を誇りに思います。" },
  { word: "pure", meaning: "純粋な", exampleEn: "This ring is made of pure gold.", exampleJp: "この指輪は純金で作られています。" },
  { word: "random", meaning: "無作為の、手当たり次第の", exampleEn: "The computer picks a random number.", exampleJp: "コンピュータが無作為な数字を選びます。" },
  { word: "rapid", meaning: "急速な", exampleEn: "The country saw rapid economic growth.", exampleJp: "その国は急速な経済成長を遂げました。" },
  { word: "rare", meaning: "まれな、珍しい", exampleEn: "This is a very rare butterfly.", exampleJp: "これはとても珍しい蝶です。" },
  { word: "rational", meaning: "合理的な、理性的な", exampleEn: "There must be a rational explanation for this.", exampleJp: "これには合理的な説明があるはずです。" },
  { word: "raw", meaning: "生の、加工されていない", exampleEn: "You should not eat raw chicken.", exampleJp: "生の鶏肉を食べてはいけません。" },
  { word: "realistic", meaning: "現実的な", exampleEn: "We need a realistic plan to save money.", exampleJp: "私たちにはお金を節約するための現実的な計画が必要です。" },
  { word: "rear", meaning: "後部の", exampleEn: "The dog sat in the rear seat of the car.", exampleJp: "犬は車の後部座席に座りました。" },
  { word: "reasonable", meaning: "合理的な、手頃な", exampleEn: "The price of this computer is reasonable.", exampleJp: "このコンピュータの価格は手頃です。" },
  { word: "reckless", meaning: "無謀な", exampleEn: "His reckless driving caused an accident.", exampleJp: "彼の無謀な運転が事故を引き起こしました。" },
  { word: "reliable", meaning: "信頼できる", exampleEn: "She is a reliable friend who always helps me.", exampleJp: "彼女はいつも私を助けてくれる信頼できる友人です。" },
  { word: "remote", meaning: "遠く離れた", exampleEn: "My grandfather lives in a remote village.", exampleJp: "私の祖父は遠く離れた村に住んでいます。" },
  { word: "rigid", meaning: "厳格な、硬い", exampleEn: "The school has rigid rules about uniforms.", exampleJp: "学校には制服についての厳格な規則があります。" },
  { word: "rough", meaning: "ざらざらした、大まかな", exampleEn: "The bark of this tree is very rough.", exampleJp: "この木の樹皮はとてもざらざらしています。" },
  { word: "royal", meaning: "王室の", exampleEn: "The royal family lives in a large palace.", exampleJp: "王室の家族は大きな宮殿に住んでいます。" },
  { word: "rural", meaning: "田舎の", exampleEn: "I enjoy the quiet life in a rural area.", exampleJp: "私は田舎の地域での静かな生活を楽しんでいます。" },
  { word: "sacred", meaning: "神聖な", exampleEn: "Cows are sacred animals in India.", exampleJp: "インドでは牛は神聖な動物です。" },
  { word: "scarce", meaning: "乏しい、不十分な", exampleEn: "Food was scarce during the cold winter.", exampleJp: "寒い冬の間、食べ物は乏しかった。" },
  { word: "scary", meaning: "怖い", exampleEn: "We watched a scary movie last night.", exampleJp: "私たちは昨夜、怖い映画を見ました。" },
  { word: "secondary", meaning: "二次的な、中等度の", exampleEn: "Money is of secondary importance to him.", exampleJp: "彼にとってお金は二次的な重要性しかありません（二の次です）。" },
  { word: "secure", meaning: "安全な、しっかりした", exampleEn: "Keep your passport in a secure place.", exampleJp: "パスポートは安全な場所に保管してください。" },
  { word: "severe", meaning: "厳しい、ひどい", exampleEn: "He suffered severe injuries in the crash.", exampleJp: "彼は衝突事故でひどい怪我を負いました。" },
  { word: "shallow", meaning: "浅い", exampleEn: "Children should play in the shallow pool.", exampleJp: "子供たちは浅いプールで遊ぶべきです。" },
  { word: "sharp", meaning: "鋭い", exampleEn: "Be careful with that sharp knife.", exampleJp: "その鋭いナイフには気をつけてください。" },
  { word: "sheer", meaning: "まったくの、純然たる", exampleEn: "It was sheer luck that we found the keys.", exampleJp: "私たちが鍵を見つけたのはまったくの幸運でした。" },
  { word: "silly", meaning: "愚かな、ばかばかしい", exampleEn: "Stop asking such silly questions.", exampleJp: "そんなばかばかしい質問をするのはやめてください。" },
  { word: "sincere", meaning: "誠実な、心からの", exampleEn: "Please accept my sincere apologies.", exampleJp: "私の心からの謝罪を受け入れてください。" },
  { word: "slim", meaning: "わずかな、ほっそりした", exampleEn: "There is only a slim chance of winning.", exampleJp: "勝つ見込みはわずかしかありません。" },

  // --- Priority 4 继续: 历年常考主题名词 (411 - 460) ---
  { word: "habit", meaning: "習慣", exampleEn: "Biting nails is a bad habit.", exampleJp: "爪を噛むのは悪い習慣です。" },
  { word: "harmony", meaning: "調和", exampleEn: "The two countries lived in peace and harmony.", exampleJp: "その二国は平和と調和の中で暮らしていました。" },
  { word: "harvest", meaning: "収穫", exampleEn: "The farmers had a good harvest of rice this year.", exampleJp: "農家は今年、米の良い収穫を得ました。" },
  { word: "hazard", meaning: "危険", exampleEn: "Smoking is a serious health hazard.", exampleJp: "喫煙は深刻な健康への危険です。" },
  { word: "headquarters", meaning: "本部、本社", exampleEn: "The company headquarters is in Tokyo.", exampleJp: "その会社の本社は東京にあります。" },
  { word: "heap", meaning: "積み重なったもの", exampleEn: "He left his dirty clothes in a heap.", exampleJp: "彼は汚れた服を山積みにしておきました。" },
  { word: "heaven", meaning: "天国", exampleEn: "He believes good people go to heaven.", exampleJp: "彼は良い人は天国に行くと信じています。" },
  { word: "height", meaning: "高さ", exampleEn: "What is the height of that tall building?", exampleJp: "あの高い建物の高さはどれくらいですか？" },
  { word: "heir", meaning: "相続人、後継者", exampleEn: "The prince is the heir to the throne.", exampleJp: "その王子は王位の継承者です。" },
  { word: "hero", meaning: "英雄", exampleEn: "The fireman who saved the baby is a hero.", exampleJp: "赤ちゃんを救った消防士は英雄です。" },
  { word: "hierarchy", meaning: "階層、ヒエラルキー", exampleEn: "The military has a strict hierarchy.", exampleJp: "軍隊には厳格な階層があります。" },
  { word: "highway", meaning: "幹線道路、高速道路", exampleEn: "We drove our car on the new highway.", exampleJp: "私たちは新しい高速道路で車を運転しました。" },
  { word: "hint", meaning: "ヒント、ほのめかし", exampleEn: "Can you give me a hint to solve this puzzle?", exampleJp: "このパズルを解くためのヒントをくれませんか？" },
  { word: "hire", meaning: "雇う", exampleEn: "The shop will hire two new workers.", exampleJp: "その店は2人の新しい店員を雇います。" },
  { word: "historian", meaning: "歴史家", exampleEn: "The historian wrote a book about the war.", exampleJp: "その歴史家は戦争についての本を書きました。" },
  { word: "hobby", meaning: "趣味", exampleEn: "Collecting stamps is my favorite hobby.", exampleJp: "切手を集めることは私のお気に入りの趣味です。" },
  { word: "holiday", meaning: "休日", exampleEn: "We will go to the beach on our next holiday.", exampleJp: "次の休日にはビーチに行きます。" },
  { word: "honor", meaning: "名誉、敬意", exampleEn: "It is a great honor to meet the president.", exampleJp: "大統領に会えることは大きな名誉です。" },
  { word: "hook", meaning: "フック、掛け金", exampleEn: "Hang your coat on the hook.", exampleJp: "コートをフックに掛けてください。" },
  { word: "horizon", meaning: "地平線、水平線", exampleEn: "The sun sank below the horizon.", exampleJp: "太陽が地平線の下に沈みました。" },
  { word: "horror", meaning: "恐怖", exampleEn: "She screamed in horror when she saw the spider.", exampleJp: "彼女はクモを見て恐怖で叫びました。" },
  { word: "host", meaning: "主催者、主人", exampleEn: "The host of the party welcomed all the guests.", exampleJp: "パーティーの主催者はすべての客を歓迎しました。" },
  { word: "household", meaning: "世帯、家庭", exampleEn: "Every household in the town recycles trash.", exampleJp: "町のすべての世帯がゴミをリサイクルしています。" },
  { word: "humanity", meaning: "人類、人間性", exampleEn: "Pollution is a big problem for all humanity.", exampleJp: "環境汚染は全人類にとって大きな問題です。" },
  { word: "humor", meaning: "ユーモア", exampleEn: "Our teacher has a great sense of humor.", exampleJp: "私たちの先生は素晴らしいユーモアのセンスを持っています。" },
  { word: "hunger", meaning: "飢え、空腹", exampleEn: "Many children in the world suffer from hunger.", exampleJp: "世界中の多くの子供たちが飢えに苦しんでいます。" },
  { word: "hunt", meaning: "狩り、探求", exampleEn: "The police started a hunt for the killer.", exampleJp: "警察は殺人犯の捜索（狩り）を始めました。" },
  { word: "hypothesis", meaning: "仮説", exampleEn: "The scientist tested his new hypothesis.", exampleJp: "その科学者は自分の新しい仮説をテストしました。" },
  { word: "identity", meaning: "身元、アイデンティティ", exampleEn: "The police discovered the thief's identity.", exampleJp: "警察は泥棒の身元を発見しました。" },
  { word: "illusion", meaning: "錯覚、幻想", exampleEn: "Mirrors can create an illusion of space.", exampleJp: "鏡は空間の錯覚を作り出すことができます。" },
  { word: "impact", meaning: "影響、衝撃", exampleEn: "The computer had a big impact on education.", exampleJp: "コンピュータは教育に大きな影響を与えました。" },
  { word: "incentive", meaning: "動機、刺激", exampleEn: "The bonus gave him an incentive to work harder.", exampleJp: "ボーナスは彼にもっと懸命に働く動機を与えました。" },
  { word: "incident", meaning: "出来事、事件", exampleEn: "A strange incident happened at school today.", exampleJp: "今日、学校で奇妙な出来事が起こりました。" },
  { word: "income", meaning: "収入", exampleEn: "His high income allows him to buy a big house.", exampleJp: "彼の高い収入が彼に大きな家を買うことを可能にします。" },
  { word: "index", meaning: "索引、指標", exampleEn: "Look up the word in the index of the book.", exampleJp: "本の索引でその単語を調べてください。" },
  { word: "individual", meaning: "個人", exampleEn: "Every individual has the right to speak freely.", exampleJp: "すべての個人が自由に話す権利を持っています。" },
  { word: "infant", meaning: "乳児、幼児", exampleEn: "The mother held her sleeping infant gently.", exampleJp: "母親は眠っている乳児を優しく抱きました。" },
  { word: "infection", meaning: "感染", exampleEn: "Wash the cut to prevent infection.", exampleJp: "感染を防ぐために切り傷を洗ってください。" },
  { word: "inflation", meaning: "インフレーション、物価上昇", exampleEn: "Inflation makes everyday items more expensive.", exampleJp: "インフレーションは日常の品物をより高くします。" },
  { word: "influence", meaning: "影響力", exampleEn: "Friends have a strong influence on teenagers.", exampleJp: "友人は10代の若者に強い影響力を持っています。" },
  { word: "ingredient", meaning: "材料", exampleEn: "Flour is the main ingredient of bread.", exampleJp: "小麦粉はパンの主な材料です。" },
  { word: "inhabitant", meaning: "住民", exampleEn: "This island has only 500 inhabitants.", exampleJp: "この島にはわずか500人の住民しかいません。" },
  { word: "initiative", meaning: "主導権", exampleEn: "She took the initiative to start a new club.", exampleJp: "彼女は新しいクラブを始める主導権を握りました。" },
  { word: "injury", meaning: "負傷、怪我", exampleEn: "He suffered a bad injury to his leg.", exampleJp: "彼は足にひどい怪我を負いました。" },
  { word: "innovation", meaning: "革新", exampleEn: "Smartphones were a great technological innovation.", exampleJp: "スマートフォンは偉大な技術的革新でした。" },
  { word: "input", meaning: "入力", exampleEn: "Please input your password here.", exampleJp: "ここにパスワードを入力してください。" },
  { word: "insect", meaning: "昆虫", exampleEn: "A bee is a busy flying insect.", exampleJp: "ミツバチは忙しく飛ぶ昆虫です。" },
  { word: "insight", meaning: "洞察力、見識", exampleEn: "The book gives us insight into Japanese culture.", exampleJp: "その本は日本の文化に対する洞察を与えてくれます。" },
  { word: "instance", meaning: "例、実例", exampleEn: "For instance, you can eat apples and oranges.", exampleJp: "例えば、りんごやオレンジを食べることができます。" },
  { word: "instinct", meaning: "本能", exampleEn: "Birds fly south by instinct.", exampleJp: "鳥は本能で南へ飛びます。" },

  // --- Priority 2 继续: 核心惯用语及短语 (461 - 500) ---
  { word: "pull over", meaning: "（車を）片側に寄せる", exampleEn: "The police told the driver to pull over.", exampleJp: "警察は運転手に車を寄せて止めるように言いました。" },
  { word: "pull through", meaning: "（病気や困難を）切り抜ける", exampleEn: "She was very sick, but she pulled through.", exampleJp: "彼女は重病でしたが、それを切り抜けました。" },
  { word: "put aside", meaning: "〜を脇に置く、蓄える", exampleEn: "I put aside some money for my trip.", exampleJp: "私は旅行のためにいくらかのお金を蓄えました。" },
  { word: "put away", meaning: "〜を片付ける", exampleEn: "Please put away your toys now.", exampleJp: "今すぐおもちゃを片付けてください。" },
  { word: "put forward", meaning: "〜を提案する", exampleEn: "He put forward a new plan at the meeting.", exampleJp: "彼は会議で新しい計画を提案しました。" },
  { word: "put out", meaning: "（火を）消す", exampleEn: "The firemen put out the big fire quickly.", exampleJp: "消防士たちは大火事をすぐに消しました。" },
  { word: "put together", meaning: "〜を組み立てる", exampleEn: "It took an hour to put together the desk.", exampleJp: "机を組み立てるのに1時間かかりました。" },
  { word: "rely on", meaning: "〜に頼る", exampleEn: "You can rely on me to help you.", exampleJp: "私を頼って助けを求めていいですよ。" },
  { word: "result in", meaning: "〜という結果になる", exampleEn: "The heavy rain resulted in a flood.", exampleJp: "大雨は洪水という結果になりました。" },
  { word: "result from", meaning: "〜から生じる", exampleEn: "His failure resulted from a lack of effort.", exampleJp: "彼の失敗は努力不足から生じました。" },
  { word: "run into", meaning: "〜に偶然出会う、衝突する", exampleEn: "I ran into my old teacher at the mall.", exampleJp: "私はショッピングモールで偶然昔の先生に会いました。" },
  { word: "run over", meaning: "（車が人を）ひく", exampleEn: "The car almost ran over the dog.", exampleJp: "車は危うく犬をひくところでした。" },
  { word: "search for", meaning: "〜を探す", exampleEn: "They searched for the lost key everywhere.", exampleJp: "彼らは失くした鍵をあちこち探しました。" },
  { word: "see off", meaning: "〜を見送る", exampleEn: "I went to the airport to see my friend off.", exampleJp: "私は友人を見送るために空港に行きました。" },
  { word: "set about", meaning: "〜に取りかかる", exampleEn: "We must set about cleaning the house now.", exampleJp: "私たちは今すぐ家の掃除に取りかからなければなりません。" },
  { word: "set aside", meaning: "〜を取っておく、無視する", exampleEn: "She sets aside one hour for reading every day.", exampleJp: "彼女は毎日読書のために1時間を取っておきます。" },
  { word: "set off", meaning: "出発する", exampleEn: "We will set off early tomorrow morning.", exampleJp: "私たちは明日の朝早くに出発します。" },
  { word: "set out", meaning: "出発する、〜し始める", exampleEn: "The hikers set out to climb the mountain.", exampleJp: "ハイカーたちは山に登るために出発しました。" },
  { word: "set up", meaning: "〜を設立する、準備する", exampleEn: "He set up a new company last year.", exampleJp: "彼は昨年、新しい会社を設立しました。" },
  { word: "settle down", meaning: "落ち着く、定住する", exampleEn: "He wants to marry and settle down in Tokyo.", exampleJp: "彼は結婚して東京に定住したいと思っています。" },
  { word: "show up", meaning: "現れる", exampleEn: "He did not show up at the party.", exampleJp: "彼はパーティーに現れませんでした。" },
  { word: "sign up", meaning: "登録する、申し込む", exampleEn: "I will sign up for the English class.", exampleJp: "私は英語のクラスに申し込みます。" },
  { word: "slow down", meaning: "スピードを落とす", exampleEn: "Please slow down when you drive near a school.", exampleJp: "学校の近くを運転するときはスピードを落としてください。" },
  { word: "stand by", meaning: "〜を支持する、待機する", exampleEn: "I will stand by you no matter what happens.", exampleJp: "何が起ころうとも私はあなたを支持します。" },
  { word: "stay up", meaning: "起きている", exampleEn: "Do not stay up too late watching TV.", exampleJp: "テレビを見て遅くまで起きているのはやめなさい。" },
  { word: "step down", meaning: "辞任する", exampleEn: "The president decided to step down.", exampleJp: "社長は辞任することを決めました。" },
  { word: "stick to", meaning: "〜に固執する、やり抜く", exampleEn: "You should stick to your plan.", exampleJp: "あなたは自分の計画をやり抜くべきです。" },
  { word: "take advantage of", meaning: "〜を利用する", exampleEn: "Take advantage of this good opportunity.", exampleJp: "この良い機会を利用しなさい。" },
  { word: "take apart", meaning: "〜を分解する", exampleEn: "He took apart the broken clock to fix it.", exampleJp: "彼は壊れた時計を修理するために分解しました。" },
  { word: "take back", meaning: "〜を取り消す、返品する", exampleEn: "I took the broken toy back to the store.", exampleJp: "私は壊れたおもちゃを店に返品しました。" },
  { word: "take down", meaning: "〜を書き留める", exampleEn: "The reporter took down what the mayor said.", exampleJp: "記者は市長が言ったことを書き留めました。" },
  { word: "take in", meaning: "〜を理解する、騙す", exampleEn: "I could not take in his long explanation.", exampleJp: "私は彼の長い説明を理解できませんでした。" },
  { word: "take off", meaning: "離陸する、脱ぐ", exampleEn: "The plane will take off in five minutes.", exampleJp: "飛行機は5分後に離陸します。" },
  { word: "take on", meaning: "（責任などを）引き受ける", exampleEn: "She took on too much work this week.", exampleJp: "彼女は今週、あまりにも多くの仕事を引き受けました。" },
  { word: "take up", meaning: "（趣味などを）始める、場所を取る", exampleEn: "He decided to take up golf as a hobby.", exampleJp: "彼は趣味としてゴルフを始めることに決めました。" },
  { word: "tear down", meaning: "〜を取り壊す", exampleEn: "They will tear down the old building to build a park.", exampleJp: "彼らは公園を作るために古い建物を取り壊します。" },
  { word: "tell apart", meaning: "〜を見分ける", exampleEn: "It is hard to tell the twin sisters apart.", exampleJp: "双子の姉妹を見分けるのは難しいです。" },
  { word: "think over", meaning: "〜をじっくり考える", exampleEn: "Please think over my offer.", exampleJp: "私の申し出についてじっくり考えてください。" },
  { word: "throw away", meaning: "〜を捨てる", exampleEn: "Do not throw away paper, please recycle it.", exampleJp: "紙を捨てないで、リサイクルしてください。" },
  { word: "try on", meaning: "〜を試着する", exampleEn: "Can I try on this blue shirt?", exampleJp: "この青いシャツを試着してもいいですか？" }
  
];
