
const vocabData = [
    { en: "agree with", jp: "〜に賛成する", enSent: "I agree with you.", jpSent: "私はあなたに賛成です。" },
    { en: "ask for", jp: "〜を求める", enSent: "He asked for water.", jpSent: "彼は水を求めました。" },
    { en: "be covered with", jp: "〜で覆われている", enSent: "The mountain is covered with snow.", jpSent: "山は雪で覆われています。" },
    { en: "be filled with", jp: "〜で満たされている", enSent: "The box is filled with toys.", jpSent: "その箱はおもちゃでいっぱいです。" },
    { en: "be full of", jp: "〜でいっぱいである", enSent: "The cup is full of water.", jpSent: "コップは水でいっぱいです。" },
    { en: "be good at", jp: "〜が得意である", enSent: "She is good at drawing.", jpSent: "彼女は絵を描くのが得意です。" },
    { en: "be interested in", jp: "〜に興味がある", enSent: "I am interested in history.", jpSent: "私は歴史に興味があります。" },
    { en: "be late for", jp: "〜に遅れる", enSent: "Don't be late for school.", jpSent: "学校に遅れないでください。" },
    { en: "be made of", jp: "〜で作られている", enSent: "This desk is made of wood.", jpSent: "この机は木で作られています。" },
    { en: "be proud of", jp: "〜を誇りに思う", enSent: "I am proud of my brother.", jpSent: "私は兄を誇りに思います。" },
    { en: "be ready for", jp: "〜の準備ができている", enSent: "Are you ready for the trip?", jpSent: "旅行の準備はできていますか？" },
    { en: "be surprised at", jp: "〜に驚く", enSent: "I was surprised at the news.", jpSent: "私はそのニュースに驚きました。" },
    { en: "be tired of", jp: "〜に飽きる/疲れる", enSent: "I am tired of waiting.", jpSent: "私は待つことに疲れました。" },
    { en: "belong to", jp: "〜に属する", enSent: "This dog belongs to me.", jpSent: "この犬は私のものです。" },
    { en: "catch a cold", jp: "風邪をひく", enSent: "I caught a bad cold.", jpSent: "ひどい風邪をひきました。" },
    { en: "come true", jp: "実現する", enSent: "My dream came true.", jpSent: "私の夢が実現しました。" },
    { en: "depend on", jp: "〜に頼る/次第である", enSent: "It depends on the weather.", jpSent: "それは天気次第です。" },
    { en: "do one's best", jp: "最善を尽くす", enSent: "I will do my best.", jpSent: "私は最善を尽くします。" },
    { en: "fall down", jp: "転ぶ", enSent: "The boy fell down.", jpSent: "その男の子は転びました。" },
    { en: "find out", jp: "見つけ出す/知る", enSent: "I found out the truth.", jpSent: "私は真実を知りました。" },
    { en: "get along with", jp: "〜と仲良くする", enSent: "I get along with her.", jpSent: "私は彼女と仲良くしています。" },
    { en: "get lost", jp: "道に迷う", enSent: "We got lost in the forest.", jpSent: "私たちは森で道に迷いました。" },
    { en: "get off", jp: "（バスなどから）降りる", enSent: "Let's get off the bus.", jpSent: "バスを降りましょう。" },
    { en: "get on", jp: "（バスなどに）乗る", enSent: "He got on the train.", jpSent: "彼は電車に乗りました。" },
    { en: "get over", jp: "〜を乗り越える", enSent: "She got over her cold.", jpSent: "彼女は風邪を治しました。" },
    { en: "get up", jp: "起きる", enSent: "I get up at six.", jpSent: "私は6時に起きます。" },
    { en: "give up", jp: "諦める", enSent: "Never give up.", jpSent: "決して諦めないで。" },
    { en: "go for a walk", jp: "散歩に行く", enSent: "Let's go for a walk.", jpSent: "散歩に行きましょう。" },
    { en: "go on a trip", jp: "旅行に行く", enSent: "We will go on a trip.", jpSent: "私たちは旅行に行きます。" },
    { en: "grow up", jp: "成長する/大人になる", enSent: "He grew up in Tokyo.", jpSent: "彼は東京で育ちました。" },
    { en: "hear from", jp: "〜から連絡がある", enSent: "I heard from my friend.", jpSent: "友達から連絡がありました。" },
    { en: "help oneself to", jp: "〜を自由にとる", enSent: "Please help yourself to the food.", jpSent: "食べ物を自由にお取りください。" },
    { en: "hurry up", jp: "急ぐ", enSent: "Hurry up!", jpSent: "急いで！" },
    { en: "in front of", jp: "〜の前に", enSent: "A car is in front of the house.", jpSent: "家の前に車があります。" },
    { en: "in the future", jp: "将来", enSent: "I want to be a doctor in the future.", jpSent: "将来は医者になりたいです。" },
    { en: "keep a diary", jp: "日記をつける", enSent: "She keeps a diary.", jpSent: "彼女は日記をつけています。" },
    { en: "keep one's word", jp: "約束を守る", enSent: "You must keep your word.", jpSent: "約束は守らなければなりません。" },
    { en: "laugh at", jp: "〜を笑う", enSent: "Don't laugh at him.", jpSent: "彼を笑わないでください。" },
    { en: "listen to", jp: "〜を聞く", enSent: "Listen to me.", jpSent: "私の話を聞いてください。" },
    { en: "look after", jp: "〜の世話をする", enSent: "I look after my dog.", jpSent: "私は犬の世話をします。" },
    { en: "look around", jp: "見回す", enSent: "He looked around the room.", jpSent: "彼は部屋を見回しました。" },
    { en: "look for", jp: "〜を探す", enSent: "I am looking for my key.", jpSent: "鍵を探しています。" },
    { en: "look forward to", jp: "〜を楽しみにする", enSent: "I look forward to the party.", jpSent: "パーティーを楽しみにしています。" },
    { en: "look like", jp: "〜のように見える", enSent: "He looks like his father.", jpSent: "彼は父親に似ています。" },
    { en: "make a mistake", jp: "間違える", enSent: "I made a mistake.", jpSent: "私は間違えました。" },
    { en: "make friends with", jp: "〜と友達になる", enSent: "I made friends with him.", jpSent: "彼と友達になりました。" },
    { en: "make up one's mind", jp: "決心する", enSent: "She made up her mind.", jpSent: "彼女は決心しました。" },
    { en: "pay for", jp: "〜の代金を払う", enSent: "I will pay for the book.", jpSent: "本のお金は私が払います。" },
    { en: "pick up", jp: "拾う/迎えに行く", enSent: "Pick up the paper.", jpSent: "紙を拾ってください。" },
    { en: "put off", jp: "延期する", enSent: "They put off the game.", jpSent: "彼らは試合を延期しました。" },
    { en: "put on", jp: "着る", enSent: "Put on your coat.", jpSent: "コートを着なさい。" },
    { en: "run away", jp: "逃げる", enSent: "The cat ran away.", jpSent: "猫が逃げました。" },
    { en: "shake hands", jp: "握手する", enSent: "They shook hands.", jpSent: "彼らは握手しました。" },
    { en: "show off", jp: "見せびらかす", enSent: "He showed off his new watch.", jpSent: "彼は新しい時計を見せびらかしました。" },
    { en: "sit down", jp: "座る", enSent: "Please sit down.", jpSent: "座ってください。" },
    { en: "smile at", jp: "〜に微笑む", enSent: "She smiled at me.", jpSent: "彼女は私に微笑みました。" },
    { en: "speak to", jp: "〜に話しかける", enSent: "I spoke to him.", jpSent: "私は彼に話しかけました。" },
    { en: "stand up", jp: "立ち上がる", enSent: "Stand up, please.", jpSent: "立ち上がってください。" },
    { en: "stay up late", jp: "夜更かしする", enSent: "Don't stay up late.", jpSent: "夜更かししないでください。" },
    { en: "take care of", jp: "〜の世話をする", enSent: "Take care of yourself.", jpSent: "体に気をつけてください。" },
    { en: "take off", jp: "脱ぐ/離陸する", enSent: "Take off your shoes.", jpSent: "靴を脱いでください。" },
    { en: "take part in", jp: "〜に参加する", enSent: "I will take part in the race.", jpSent: "レースに参加します。" },
    { en: "take place", jp: "行われる/起こる", enSent: "The event will take place here.", jpSent: "そのイベントはここで行われます。" },
    { en: "think of", jp: "〜を思いつく/考える", enSent: "I thought of a good idea.", jpSent: "良いアイデアを思いつきました。" },
    { en: "try on", jp: "試着する", enSent: "Try on this shirt.", jpSent: "このシャツを試着してみて。" },
    { en: "turn off", jp: "消す", enSent: "Turn off the TV.", jpSent: "テレビを消してください。" },
    { en: "turn on", jp: "つける", enSent: "Turn on the light.", jpSent: "電気をつけてください。" },
    { en: "wake up", jp: "目を覚ます", enSent: "I wake up early.", jpSent: "私は早く起きます。" },
    { en: "write to", jp: "〜に手紙を書く", enSent: "I will write to you.", jpSent: "あなたに手紙を書きます。" },
    { en: "a kind of", jp: "一種の〜", enSent: "It is a kind of bird.", jpSent: "それは鳥の一種です。" },
    { en: "a lot of", jp: "たくさんの", enSent: "I have a lot of books.", jpSent: "私はたくさんの本を持っています。" },
    { en: "a piece of", jp: "一枚の/一つの", enSent: "I need a piece of paper.", jpSent: "一枚の紙が必要です。" },
    { en: "after all", jp: "結局", enSent: "He didn't come after all.", jpSent: "結局彼は来ませんでした。" },
    { en: "after school", jp: "放課後", enSent: "Let's play after school.", jpSent: "放課後遊ぼう。" },
    { en: "all day", jp: "一日中", enSent: "It rained all day.", jpSent: "一日中雨が降りました。" },
    { en: "all over the world", jp: "世界中で", enSent: "Soccer is played all over the world.", jpSent: "サッカーは世界中でプレイされています。" },
    { en: "all the time", jp: "いつも/その間ずっと", enSent: "He is busy all the time.", jpSent: "彼はいつも忙しいです。" },
    { en: "as usual", jp: "いつものように", enSent: "He is late as usual.", jpSent: "彼はいつものように遅刻です。" },
    { en: "at first", jp: "最初は", enSent: "At first, it was hard.", jpSent: "最初は難しかったです。" },
    { en: "at last", jp: "ついに", enSent: "At last, we arrived.", jpSent: "ついに到着しました。" },
    { en: "accept", jp: "受け入れる", enSent: "Please accept this gift.", jpSent: "この贈り物を受け取ってください。" },
    { en: "act", jp: "行動する/演じる", enSent: "He acted quickly.", jpSent: "彼は素早く行動しました。" },
    { en: "add", jp: "加える", enSent: "Add salt to the soup.", jpSent: "スープに塩を加えてください。" },
    { en: "advise", jp: "忠告する", enSent: "He advised me to rest.", jpSent: "彼は私に休むよう忠告しました。" },
    { en: "allow", jp: "許す", enSent: "Dogs are not allowed here.", jpSent: "ここは犬の立ち入りは許されていません。" },
    { en: "apologize", jp: "謝る", enSent: "I apologize to you.", jpSent: "あなたに謝ります。" },
    { en: "appear", jp: "現れる/〜のように見える", enSent: "A star appeared in the sky.", jpSent: "空に星が現れました。" },
    { en: "approach", jp: "近づく", enSent: "The train is approaching.", jpSent: "電車が近づいています。" },
    { en: "arrive", jp: "到着する", enSent: "We arrived in Tokyo.", jpSent: "私たちは東京に到着しました。" },
    { en: "attend", jp: "出席する", enSent: "I will attend the meeting.", jpSent: "私は会議に出席します。" },
    { en: "avoid", jp: "避ける", enSent: "Avoid eating too much.", jpSent: "食べ過ぎを避けてください。" },
    { en: "bake", jp: "焼く", enSent: "She bakes a cake.", jpSent: "彼女はケーキを焼きます。" },
    { en: "bear", jp: "耐える/生む", enSent: "I can't bear the pain.", jpSent: "痛みに耐えられません。" },
    { en: "beat", jp: "打ち負かす/打つ", enSent: "Our team beat them.", jpSent: "私たちのチームが彼らを打ち負かしました。" },
    { en: "belong", jp: "属する", enSent: "This belongs to me.", jpSent: "これは私のものです。" },
    { en: "borrow", jp: "借りる", enSent: "Can I borrow a pen?", jpSent: "ペンを借りてもいいですか？" },
    { en: "cancel", jp: "取り消す", enSent: "I canceled the plan.", jpSent: "私は計画を取り消しました。" },
    { en: "celebrate", jp: "祝う", enSent: "We celebrate his birthday.", jpSent: "私たちは彼の誕生日を祝います。" },
    { en: "choose", jp: "選ぶ", enSent: "Choose a card.", jpSent: "カードを1枚選んでください。" },
    { en: "collect", jp: "集める", enSent: "He collects stamps.", jpSent: "彼は切手を集めています。" },
    { en: "communicate", jp: "意思を伝える", enSent: "We communicate in English.", jpSent: "私たちは英語でコミュニケーションをとります。" },
    { en: "compare", jp: "比較する", enSent: "Compare the two cars.", jpSent: "2つの車を比較してください。" },
    { en: "complain", jp: "不平を言う", enSent: "Don't complain about food.", jpSent: "食べ物の文句を言わないで。" },
    { en: "complete", jp: "完成させる", enSent: "He completed the work.", jpSent: "彼は仕事を完成させました。" },
    { en: "continue", jp: "続ける", enSent: "The rain continued.", jpSent: "雨が続きました。" },
    { en: "control", jp: "支配する/抑える", enSent: "Control your feelings.", jpSent: "感情を抑えなさい。" },
    { en: "cost", jp: "費用がかかる", enSent: "This car costs a lot.", jpSent: "この車はたくさんお金がかかります。" },
    { en: "count", jp: "数える", enSent: "Count from one to ten.", jpSent: "1から10まで数えてください。" },
    { en: "create", jp: "作り出す", enSent: "She created a new game.", jpSent: "彼女は新しいゲームを作り出しました。" },
    { en: "cross", jp: "横切る", enSent: "Cross the street here.", jpSent: "ここで道を渡ってください。" },
    { en: "damage", jp: "損害を与える", enSent: "The rain damaged the flowers.", jpSent: "雨が花にダメージを与えました。" },
    { en: "decide", jp: "決める", enSent: "I decided to go.", jpSent: "私は行くことに決めました。" },
    { en: "deliver", jp: "配達する", enSent: "He delivered the pizza.", jpSent: "彼はピザを配達しました。" },
    { en: "depend", jp: "頼る/次第である", enSent: "I depend on you.", jpSent: "私はあなたを頼りにしています。" },
    { en: "describe", jp: "描写する/説明する", enSent: "Describe the man.", jpSent: "その男の人の特徴を説明してください。" },
    { en: "destroy", jp: "破壊する", enSent: "The fire destroyed the house.", jpSent: "火事が家を破壊しました。" },
    { en: "die", jp: "死ぬ", enSent: "The tree died.", jpSent: "その木は枯れました。" },
    { en: "differ", jp: "異なる", enSent: "My idea differs from yours.", jpSent: "私の考えはあなたのものとは異なります。" },
    { en: "discover", jp: "発見する", enSent: "They discovered a new island.", jpSent: "彼らは新しい島を発見しました。" },
    { en: "discuss", jp: "話し合う", enSent: "We discussed the problem.", jpSent: "私たちはその問題について話し合いました。" },
    { en: "divide", jp: "分ける", enSent: "Divide the cake into four.", jpSent: "ケーキを4つに分けてください。" },
    { en: "draw", jp: "描く/引く", enSent: "Draw a line here.", jpSent: "ここに線を引いてください。" },
    { en: "drop", jp: "落とす", enSent: "He dropped his phone.", jpSent: "彼はスマホを落としました。" },
    { en: "dry", jp: "乾かす", enSent: "Dry your hands.", jpSent: "手を乾かしてください。" },
    { en: "earn", jp: "稼ぐ", enSent: "He earns a lot of money.", jpSent: "彼はたくさんのお金を稼ぎます。" },
    { en: "educate", jp: "教育する", enSent: "Schools educate children.", jpSent: "学校は子供を教育します。" },
    { en: "empty", jp: "空にする", enSent: "Empty the box.", jpSent: "箱を空にしてください。" },
    { en: "encourage", jp: "励ます", enSent: "He encouraged me.", jpSent: "彼は私を励ましてくれました。" },
    { en: "enter", jp: "入る", enSent: "Please enter the room.", jpSent: "部屋に入ってください。" },
    { en: "exchange", jp: "交換する", enSent: "We exchanged gifts.", jpSent: "私たちはプレゼントを交換しました。" },
    { en: "excuse", jp: "許す/言い訳", enSent: "Excuse me.", jpSent: "失礼します（許してください）。" },
    { en: "expect", jp: "予期する/期待する", enSent: "I expect good news.", jpSent: "良い知らせを期待しています。" },
    { en: "explain", jp: "説明する", enSent: "Please explain the rule.", jpSent: "ルールを説明してください。" },
    { en: "express", jp: "表現する", enSent: "Express your feelings.", jpSent: "あなたの気持ちを表現してください。" },
    { en: "fail", jp: "失敗する", enSent: "I failed the test.", jpSent: "私はテストに失敗しました。" },
    { en: "feed", jp: "食べ物を与える", enSent: "Feed the dog.", jpSent: "犬にご飯をあげてください。" },
    { en: "fill", jp: "満たす", enSent: "Fill the cup with milk.", jpSent: "コップを牛乳でいっぱいにしてください。" },
    { en: "finish", jp: "終える", enSent: "I finished my homework.", jpSent: "私は宿題を終えました。" },
    { en: "fit", jp: "合う", enSent: "This shirt fits me.", jpSent: "このシャツは私にぴったりです。" },
    { en: "fly", jp: "飛ぶ", enSent: "Birds fly in the sky.", jpSent: "鳥は空を飛びます。" },
    { en: "follow", jp: "ついて行く/従う", enSent: "Follow me.", jpSent: "私についてきてください。" },
    { en: "forget", jp: "忘れる", enSent: "Don't forget your bag.", jpSent: "カバンを忘れないでください。" },
    { en: "forgive", jp: "許す", enSent: "Please forgive me.", jpSent: "私を許してください。" },
    { en: "guess", jp: "推測する", enSent: "Guess my age.", jpSent: "私の年齢を当ててみて。" },
    { en: "happen", jp: "起こる", enSent: "What happened?", jpSent: "何が起きたの？" },
    { en: "hate", jp: "憎む/嫌う", enSent: "I hate rain.", jpSent: "私は雨が嫌いです。" },
    { en: "hide", jp: "隠す", enSent: "He hid the letter.", jpSent: "彼は手紙を隠しました。" },
    { en: "hit", jp: "打つ", enSent: "He hit the ball.", jpSent: "彼はボールを打ちました。" },
    { en: "hold", jp: "持つ/開く", enSent: "Hold my hand.", jpSent: "私の手を握って。" },
    { en: "hope", jp: "望む", enSent: "I hope you are well.", jpSent: "あなたが元気だといいなと望みます。" },
    { en: "hurt", jp: "傷つける", enSent: "My leg hurts.", jpSent: "足が痛いです（傷ついています）。" },
    { en: "imagine", jp: "想像する", enSent: "Imagine a blue bird.", jpSent: "青い鳥を想像してください。" },
    { en: "improve", jp: "良くする", enSent: "I want to improve my English.", jpSent: "私は英語を上達させたいです。" },
    { en: "include", jp: "含む", enSent: "The price includes tax.", jpSent: "値段には税金が含まれています。" },
    { en: "increase", jp: "増える/増やす", enSent: "The number is increasing.", jpSent: "数が増えています。" },
    { en: "introduce", jp: "紹介する", enSent: "Let me introduce my friend.", jpSent: "友達を紹介させてください。" },
    { en: "invite", jp: "招待する", enSent: "He invited me to the party.", jpSent: "彼は私をパーティーに招待しました。" },
    { en: "join", jp: "参加する/加わる", enSent: "Join our club.", jpSent: "私たちのクラブに加わって。" },
    { en: "jump", jp: "跳ぶ", enSent: "The frog jumped high.", jpSent: "カエルは高く跳びました。" },
    { en: "keep", jp: "保つ", enSent: "Keep the room clean.", jpSent: "部屋を清潔に保ちなさい。" },
    { en: "accident", jp: "事故", enSent: "I saw a car accident.", jpSent: "私は車の事故を見ました。" },
    { en: "action", jp: "行動", enSent: "Take action now.", jpSent: "今すぐ行動を起こしなさい。" },
    { en: "activity", jp: "活動", enSent: "I like outdoor activities.", jpSent: "私は外の活動が好きです。" },
    { en: "advice", jp: "助言", enSent: "Thank you for your advice.", jpSent: "助言をありがとう。" },
    { en: "age", jp: "年齢/時代", enSent: "What is his age?", jpSent: "彼の年齢はいくつですか？" },
    { en: "agreement", jp: "合意/約束", enSent: "We made an agreement.", jpSent: "私たちは合意しました。" },
    { en: "agriculture", jp: "農業", enSent: "Agriculture is important.", jpSent: "農業は重要です。" },
    { en: "airport", jp: "空港", enSent: "Let's go to the airport.", jpSent: "空港に行きましょう。" },
    { en: "amount", jp: "量/金額", enSent: "A large amount of money.", jpSent: "大量のお金。" },
    { en: "animal", jp: "動物", enSent: "A dog is an animal.", jpSent: "犬は動物です。" },
    { en: "answer", jp: "答え", enSent: "What is the answer?", jpSent: "答えは何ですか？" },
    { en: "apartment", jp: "アパート", enSent: "I live in an apartment.", jpSent: "私はアパートに住んでいます。" },
    { en: "area", jp: "地域/面積", enSent: "This area is quiet.", jpSent: "この地域は静かです。" },
    { en: "art", jp: "芸術/美術", enSent: "I love art.", jpSent: "私は美術が好きです。" },
    { en: "article", jp: "記事", enSent: "I read an article about space.", jpSent: "宇宙についての記事を読みました。" },
    { en: "artist", jp: "芸術家", enSent: "He is a famous artist.", jpSent: "彼は有名な芸術家です。" },
    { en: "attention", jp: "注意", enSent: "Pay attention.", jpSent: "注意を払いなさい。" },
    { en: "author", jp: "著者", enSent: "Who is the author?", jpSent: "著者は誰ですか？" },
    { en: "average", jp: "平均", enSent: "The average score is 80.", jpSent: "平均点は80点です。" },
    { en: "background", jp: "背景", enSent: "The background is blue.", jpSent: "背景は青色です。" },
    { en: "balance", jp: "バランス", enSent: "Keep your balance.", jpSent: "バランスを保って。" },
    { en: "bank", jp: "銀行/土手", enSent: "I went to the bank.", jpSent: "私は銀行に行きました。" },
    { en: "base", jp: "土台/基地", enSent: "The base of the tower.", jpSent: "塔の土台。" },
    { en: "beach", jp: "浜辺", enSent: "Let's walk on the beach.", jpSent: "浜辺を歩きましょう。" },
    { en: "bear", jp: "熊", enSent: "I saw a brown bear.", jpSent: "茶色い熊を見ました。" },
    { en: "beauty", jp: "美しさ", enSent: "The beauty of nature.", jpSent: "自然の美しさ。" },
    { en: "beginning", jp: "始まり", enSent: "At the beginning of the book.", jpSent: "本の初めに。" },
    { en: "behavior", jp: "振る舞い", enSent: "His behavior was strange.", jpSent: "彼の振る舞いは変でした。" },
    { en: "bell", jp: "鐘/ベル", enSent: "The bell rang.", jpSent: "ベルが鳴りました。" },
    { en: "bicycle", jp: "自転車", enSent: "I ride a bicycle.", jpSent: "私は自転車に乗ります。" },
    { en: "bird", jp: "鳥", enSent: "A bird is flying.", jpSent: "鳥が飛んでいます。" },
    { en: "birth", jp: "誕生", enSent: "The birth of a baby.", jpSent: "赤ちゃんの誕生。" },
    { en: "blood", jp: "血", enSent: "Blood is red.", jpSent: "血は赤いです。" },
    { en: "board", jp: "板/黒板", enSent: "Write on the board.", jpSent: "黒板に書きなさい。" },
    { en: "boat", jp: "ボート", enSent: "We rode a boat.", jpSent: "私たちはボートに乗りました。" },
    { en: "body", jp: "体", enSent: "Move your body.", jpSent: "体を動かして。" },
    { en: "bone", jp: "骨", enSent: "A dog loves bones.", jpSent: "犬は骨が大好きです。" },
    { en: "book", jp: "本", enSent: "Read a book.", jpSent: "本を読みなさい。" },
    { en: "boss", jp: "上司", enSent: "He is my boss.", jpSent: "彼は私の上司です。" },
    { en: "bottom", jp: "底", enSent: "The bottom of the sea.", jpSent: "海の底。" },
    { en: "branch", jp: "枝/支店", enSent: "A bird is on the branch.", jpSent: "鳥が枝にいます。" },
    { en: "bread", jp: "パン", enSent: "I eat bread for breakfast.", jpSent: "朝食にパンを食べます。" },
    { en: "break", jp: "休憩", enSent: "Let's take a break.", jpSent: "休憩しましょう。" },
    { en: "bridge", jp: "橋", enSent: "Cross the bridge.", jpSent: "橋を渡ってください。" },
    { en: "building", jp: "建物", enSent: "This is a tall building.", jpSent: "これは高い建物です。" },
    { en: "business", jp: "仕事/商売", enSent: "He is on business.", jpSent: "彼は仕事中です。" },
    { en: "button", jp: "ボタン", enSent: "Push the button.", jpSent: "ボタンを押してください。" },
    { en: "capital", jp: "首都", enSent: "Tokyo is the capital of Japan.", jpSent: "東京は日本の首都です。" },
    { en: "captain", jp: "キャプテン/船長", enSent: "He is the team captain.", jpSent: "彼はチームのキャプテンです。" },
    { en: "care", jp: "注意/世話", enSent: "Take care of your dog.", jpSent: "犬の世話をしなさい。" },
    { en: "active", jp: "活動的な", enSent: "He is an active boy.", jpSent: "彼は活動的な男の子です。" },
    { en: "afraid", jp: "恐れて", enSent: "Don't be afraid.", jpSent: "恐れないで。" },
    { en: "alive", jp: "生きている", enSent: "The fish is alive.", jpSent: "その魚は生きています。" },
    { en: "alone", jp: "一人で", enSent: "I am alone in the room.", jpSent: "私は部屋に一人です。" },
    { en: "angry", jp: "怒って", enSent: "He is angry.", jpSent: "彼は怒っています。" },
    { en: "anxious", jp: "心配して", enSent: "She is anxious about the test.", jpSent: "彼女はテストを心配しています。" },
    { en: "asleep", jp: "眠って", enSent: "The baby is asleep.", jpSent: "赤ちゃんは眠っています。" },
    { en: "awake", jp: "起きて", enSent: "I am fully awake.", jpSent: "私は完全に起きています。" },
    { en: "awful", jp: "ひどい", enSent: "This food tastes awful.", jpSent: "この食べ物はひどい味がします。" },
    { en: "basic", jp: "基礎の", enSent: "This is a basic rule.", jpSent: "これは基礎のルールです。" },
    { en: "blind", jp: "目の見えない", enSent: "He is a blind man.", jpSent: "彼は目の見えない人です。" },
    { en: "boring", jp: "退屈な", enSent: "The movie was boring.", jpSent: "その映画は退屈でした。" },
    { en: "brave", jp: "勇敢な", enSent: "He is a brave soldier.", jpSent: "彼は勇敢な兵士です。" },
    { en: "bright", jp: "明るい/賢い", enSent: "The sun is bright.", jpSent: "太陽が明るいです。" },
    { en: "broad", jp: "広い", enSent: "The river is broad.", jpSent: "その川は広いです。" },
    { en: "careful", jp: "注意深い", enSent: "Be careful.", jpSent: "気をつけて。" },
    { en: "careless", jp: "不注意な", enSent: "It was a careless mistake.", jpSent: "それは不注意な間違いでした。" },
    { en: "certain", jp: "確かな", enSent: "I am certain about it.", jpSent: "私はそれについて確信しています。" },
    { en: "cheap", jp: "安い", enSent: "This bag is cheap.", jpSent: "このカバンは安いです。" },
    { en: "cheerful", jp: "陽気な", enSent: "She is a cheerful girl.", jpSent: "彼女は陽気な女の子です。" },
    { en: "clear", jp: "明確な/晴れた", enSent: "The water is clear.", jpSent: "水が澄んでいます。" },
    { en: "common", jp: "共通の/普通の", enSent: "It is a common name.", jpSent: "それはありふれた名前です。" },
    { en: "cool", jp: "涼しい/かっこいい", enSent: "The wind is cool.", jpSent: "風が涼しいです。" },
    { en: "crazy", jp: "夢中で/おかしい", enSent: "He is crazy about soccer.", jpSent: "彼はサッカーに夢中です。" },
    { en: "dark", jp: "暗い", enSent: "The room is dark.", jpSent: "部屋が暗いです。" },
    { en: "dead", jp: "死んでいる", enSent: "The tree is dead.", jpSent: "その木は枯れています。" },
    { en: "deep", jp: "深い", enSent: "The sea is deep.", jpSent: "海は深いです。" },
    { en: "delicious", jp: "とても美味しい", enSent: "This cake is delicious.", jpSent: "このケーキはとても美味しいです。" },
    { en: "difficult", jp: "難しい", enSent: "English is difficult.", jpSent: "英語は難しいです。" },
    { en: "dirty", jp: "汚い", enSent: "My hands are dirty.", jpSent: "私の手は汚いです。" },
    { en: "dry", jp: "乾いた", enSent: "The towel is dry.", jpSent: "タオルは乾いています。" },
    { en: "eager", jp: "熱望して", enSent: "I am eager to learn.", jpSent: "私は学ぶことを熱望しています。" },
    { en: "empty", jp: "空の", enSent: "The box is empty.", jpSent: "箱は空です。" },
    { en: "equal", jp: "等しい", enSent: "We are all equal.", jpSent: "私たちはみんな平等です。" },
    { en: "excellent", jp: "優秀な", enSent: "This is an excellent book.", jpSent: "これは素晴らしい本です。" },
    { en: "fair", jp: "公平な", enSent: "The rule is fair.", jpSent: "そのルールは公平です。" },
    { en: "false", jp: "間違った", enSent: "That is a false story.", jpSent: "それは嘘の話です。" },
    { en: "familiar", jp: "よく知られている", enSent: "His face is familiar.", jpSent: "彼の顔はよく知られています。" },
    { en: "famous", jp: "有名な", enSent: "He is a famous singer.", jpSent: "彼は有名な歌手です。" },
    { en: "far", jp: "遠い", enSent: "My school is far.", jpSent: "私の学校は遠いです。" },



    { en: "ability", jp: "能力", enSent: "He has the ability to swim.", jpSent: "彼には泳ぐ能力があります。" },
    { en: "absence", jp: "不在", enSent: "His absence was noticed.", jpSent: "彼の不在は気づかれました。" },
    { en: "access", jp: "アクセス / 接近", enSent: "I have access to the internet.", jpSent: "私はインターネットにアクセスできます。" },
    { en: "action", jp: "行動", enSent: "We need to take action.", jpSent: "私たちは行動を起こす必要があります。" },
    { en: "activity", jp: "活動", enSent: "I enjoy club activities.", jpSent: "私はクラブ活動を楽しんでいます。" },
    { en: "advantage", jp: "利点", enSent: "This has a big advantage.", jpSent: "これには大きな利点があります。" },
    { en: "advice", jp: "助言", enSent: "He gave me good advice.", jpSent: "彼は私に良い助言をくれました。" },
    { en: "agreement", jp: "合意", enSent: "We reached an agreement.", jpSent: "私たちは合意に達しました。" },
    { en: "agriculture", jp: "農業", enSent: "Agriculture is important here.", jpSent: "ここでは農業が重要です。" },
    { en: "amount", jp: "量", enSent: "A large amount of money.", jpSent: "多額のお金。" },
    { en: "ancestor", jp: "祖先", enSent: "Our ancestors lived here.", jpSent: "私たちの祖先はここに住んでいました。" },
    { en: "anxiety", jp: "不安", enSent: "I feel anxiety about the test.", jpSent: "私はテストに不安を感じます。" },
    { en: "appearance", jp: "外見", enSent: "Don't judge by appearance.", jpSent: "外見で判断しないでください。" },
    { en: "appetite", jp: "食欲", enSent: "I have a good appetite.", jpSent: "私は食欲があります。" },
    { en: "appointment", jp: "約束 / 予約", enSent: "I have an appointment at 3.", jpSent: "私は3時に予約があります。" },
    { en: "architecture", jp: "建築", enSent: "I study architecture.", jpSent: "私は建築を学んでいます。" },
    { en: "article", jp: "記事", enSent: "I read an interesting article.", jpSent: "私は面白い記事を読みました。" },
    { en: "aspect", jp: "側面", enSent: "Think about every aspect.", jpSent: "あらゆる側面について考えなさい。" },
    { en: "attempt", jp: "試み", enSent: "It was a brave attempt.", jpSent: "それは勇敢な試みでした。" },
    { en: "attention", jp: "注意", enSent: "Pay attention to the teacher.", jpSent: "先生に注意を払いなさい。" },
    { en: "attitude", jp: "態度", enSent: "He has a bad attitude.", jpSent: "彼は態度が悪いです。" },
    { en: "audience", jp: "聴衆", enSent: "The audience clapped.", jpSent: "聴衆は拍手しました。" },
    { en: "author", jp: "著者", enSent: "Who is the author of this book?", jpSent: "この本の著者は誰ですか？" },
    { en: "average", jp: "平均", enSent: "He is of average height.", jpSent: "彼は平均的な身長です。" },
    { en: "background", jp: "背景", enSent: "What is your background?", jpSent: "あなたの背景（経歴）は何ですか？" },
    { en: "balance", jp: "バランス", enSent: "Keep your balance.", jpSent: "バランスを保ちなさい。" },
    { en: "basis", jp: "基礎", enSent: "This is the basis of the plan.", jpSent: "これが計画の基礎です。" },
    { en: "behavior", jp: "振る舞い", enSent: "His behavior is very good.", jpSent: "彼の振る舞いはとても良いです。" },
    { en: "belief", jp: "信念", enSent: "It is my strong belief.", jpSent: "それは私の強い信念です。" },
    { en: "biology", jp: "生物学", enSent: "I like biology.", jpSent: "私は生物学が好きです。" },
    { en: "blood", jp: "血", enSent: "Blood is red.", jpSent: "血は赤いです。" },
    { en: "bottom", jp: "底", enSent: "Look at the bottom of the sea.", jpSent: "海の底を見てください。" },
    { en: "branch", jp: "枝 / 支店", enSent: "A bird is on the branch.", jpSent: "鳥が枝にとまっています。" },
    { en: "breath", jp: "息", enSent: "Take a deep breath.", jpSent: "深呼吸してください。" },
    { en: "burden", jp: "負担", enSent: "It is a heavy burden.", jpSent: "それは重い負担です。" },
    { en: "campaign", jp: "キャンペーン", enSent: "They started a campaign.", jpSent: "彼らはキャンペーンを始めました。" },
    { en: "capacity", jp: "容量 / 能力", enSent: "The capacity is 50 people.", jpSent: "収容人数は50人です。" },
    { en: "capital", jp: "首都 / 資本", enSent: "Tokyo is the capital of Japan.", jpSent: "東京は日本の首都です。" },
    { en: "career", jp: "経歴 / 職業", enSent: "She has a great career.", jpSent: "彼女は素晴らしい経歴を持っています。" },
    { en: "case", jp: "場合 / 事件", enSent: "In that case, I will go.", jpSent: "その場合は、私が参ります。" },
    { en: "cause", jp: "原因", enSent: "What is the cause of the fire?", jpSent: "火事の原因は何ですか？" },
    { en: "cell", jp: "細胞", enSent: "Our body has many cells.", jpSent: "私たちの体はたくさんの細胞を持っています。" },
    { en: "century", jp: "世紀", enSent: "We are in the 21st century.", jpSent: "私たちは21世紀にいます。" },
    { en: "character", jp: "性格 / 登場人物", enSent: "He has a nice character.", jpSent: "彼は優しい性格です。" },
    { en: "charge", jp: "料金 / 責任", enSent: "What is the charge for this?", jpSent: "これの料金はいくらですか？" },
    { en: "choice", jp: "選択", enSent: "It is a good choice.", jpSent: "それは良い選択です。" },
    { en: "circumstance", jp: "状況", enSent: "Under these circumstances, we can't go.", jpSent: "このような状況下では、私たちは行けません。" },
    { en: "citizen", jp: "市民", enSent: "He is a good citizen.", jpSent: "彼は善良な市民です。" },
    { en: "climate", jp: "気候", enSent: "Japan has a mild climate.", jpSent: "日本は温和な気候です。" },
    { en: "collection", jp: "収集", enSent: "I have a stamp collection.", jpSent: "私は切手のコレクションを持っています。" },
    { en: "communication", jp: "コミュニケーション", enSent: "Communication is important.", jpSent: "コミュニケーションは重要です。" },
    { en: "community", jp: "地域社会", enSent: "I love my community.", jpSent: "私は自分の地域社会が好きです。" },
    { en: "company", jp: "会社 / 仲間", enSent: "He works for a big company.", jpSent: "彼は大きな会社で働いています。" },
    { en: "comparison", jp: "比較", enSent: "By comparison, this is better.", jpSent: "比較すると、こちらの方が良いです。" },
    { en: "condition", jp: "条件 / 状態", enSent: "My car is in good condition.", jpSent: "私の車は良い状態です。" },
    { en: "confidence", jp: "自信", enSent: "She has a lot of confidence.", jpSent: "彼女にはたくさんの自信があります。" },
    { en: "conflict", jp: "争い", enSent: "There was a conflict.", jpSent: "争いがありました。" },
    { en: "connection", jp: "繋がり", enSent: "Is there a connection?", jpSent: "繋がりはありますか？" },
    { en: "consequence", jp: "結果", enSent: "You must face the consequence.", jpSent: "あなたは結果を受け入れなければなりません。" },
    { en: "consideration", jp: "考慮", enSent: "Thank you for your consideration.", jpSent: "ご配慮ありがとうございます。" },
    { en: "contact", jp: "連絡", enSent: "Keep in contact.", jpSent: "連絡を取り合おう。" },
    { en: "context", jp: "文脈", enSent: "Read it in context.", jpSent: "文脈の中で読みなさい。" },
    { en: "contrast", jp: "対照", enSent: "In contrast, he is quiet.", jpSent: "対照的に、彼は静かです。" },
    { en: "contribution", jp: "貢献", enSent: "He made a great contribution.", jpSent: "彼は大きな貢献をしました。" },
    { en: "control", jp: "制御 / 支配", enSent: "Everything is under control.", jpSent: "すべて制御されています。" },
    { en: "conversation", jp: "会話", enSent: "We had a long conversation.", jpSent: "私たちは長い会話をしました。" },
    { en: "cost", jp: "費用", enSent: "The cost is too high.", jpSent: "費用が高すぎます。" },
    { en: "courage", jp: "勇気", enSent: "He showed great courage.", jpSent: "彼は大きな勇気を見せました。" },
    { en: "course", jp: "進路 / 講座", enSent: "I take an English course.", jpSent: "私は英語のコースを受けています。" },
    { en: "court", jp: "裁判所 / コート", enSent: "He went to the court.", jpSent: "彼は裁判所に行きました。" },
    { en: "credit", jp: "信用", enSent: "I use a credit card.", jpSent: "私はクレジットカードを使います。" },
    { en: "crime", jp: "犯罪", enSent: "Crime is bad.", jpSent: "犯罪は悪いです。" },
    { en: "crisis", jp: "危機", enSent: "We face a crisis.", jpSent: "私たちは危機に直面しています。" },
    { en: "crop", jp: "農作物", enSent: "They grow crops.", jpSent: "彼らは農作物を育てます。" },
    { en: "crowd", jp: "群衆", enSent: "There was a big crowd.", jpSent: "大きな群衆がいました。" },
    { en: "custom", jp: "習慣", enSent: "It is a Japanese custom.", jpSent: "それは日本の習慣です。" },
    { en: "danger", jp: "危険", enSent: "He is in danger.", jpSent: "彼は危険な状態にあります。" },
    { en: "decision", jp: "決定", enSent: "I made a decision.", jpSent: "私は決定を下しました。" },
    { en: "degree", jp: "程度 / 度", enSent: "The temperature is 30 degrees.", jpSent: "気温は30度です。" },
    { en: "department", jp: "部門 / 学科", enSent: "He works in that department.", jpSent: "彼はその部門で働いています。" },
    { en: "design", jp: "デザイン / 設計", enSent: "I like this design.", jpSent: "私はこのデザインが好きです。" },
    { en: "detail", jp: "詳細", enSent: "Tell me the details.", jpSent: "詳細を教えてください。" },
    { en: "difference", jp: "違い", enSent: "What is the difference?", jpSent: "違いは何ですか？" },
    { en: "difficulty", jp: "困難", enSent: "I have difficulty reading.", jpSent: "私は読むことに困難を感じます。" },
    { en: "direction", jp: "方向", enSent: "Which direction is north?", jpSent: "北はどの方向ですか？" },
    { en: "discussion", jp: "議論", enSent: "We had a discussion.", jpSent: "私たちは議論をしました。" },
    { en: "disease", jp: "病気", enSent: "He has a rare disease.", jpSent: "彼は珍しい病気を持っています。" },
    { en: "distance", jp: "距離", enSent: "The distance is long.", jpSent: "距離が長いです。" },
    { en: "education", jp: "教育", enSent: "Education is very important.", jpSent: "教育はとても重要です。" },
    { en: "effort", jp: "努力", enSent: "He made a great effort.", jpSent: "彼は大きな努力をしました。" },
    { en: "electricity", jp: "電気", enSent: "We need electricity.", jpSent: "私たちは電気を必要とします。" },
    { en: "emergency", jp: "緊急事態", enSent: "This is an emergency.", jpSent: "これは緊急事態です。" },
    { en: "employee", jp: "従業員", enSent: "He is an employee here.", jpSent: "彼はここの従業員です。" },
    { en: "energy", jp: "エネルギー", enSent: "I have no energy today.", jpSent: "今日はエネルギーがありません。" },
    { en: "environment", jp: "環境", enSent: "We must protect the environment.", jpSent: "環境を守らなければなりません。" },
    { en: "event", jp: "出来事 / 行事", enSent: "It was a big event.", jpSent: "それは大きな行事でした。" },
    { en: "experience", jp: "経験", enSent: "I have a lot of experience.", jpSent: "私には多くの経験があります。" },
    { en: "expert", jp: "専門家", enSent: "He is an expert in computer.", jpSent: "彼はコンピュータの専門家です。" },
    { en: "fact", jp: "事実", enSent: "Tell me the fact.", jpSent: "事実を教えてください。" },
    { en: "factory", jp: "工場", enSent: "He works in a factory.", jpSent: "彼は工場で働いています。" },
    { en: "failure", jp: "失敗", enSent: "Failure teaches us.", jpSent: "失敗は私たちに教えてくれます。" },
    { en: "fee", jp: "料金", enSent: "The entrance fee is 5 dollars.", jpSent: "入場料は5ドルです。" },
    { en: "feeling", jp: "感情", enSent: "I have a bad feeling.", jpSent: "悪い予感がします。" },
    { en: "figure", jp: "数字 / 姿", enSent: "Look at this figure.", jpSent: "この数字を見てください。" },
    { en: "force", jp: "力", enSent: "Use your force.", jpSent: "あなたの力を使いなさい。" },
    { en: "forest", jp: "森", enSent: "We walked in the forest.", jpSent: "私たちは森を歩きました。" },
    { en: "freedom", jp: "自由", enSent: "Freedom is important.", jpSent: "自由は重要です。" },
    { en: "friendship", jp: "友情", enSent: "Our friendship will last forever.", jpSent: "私たちの友情は永遠に続くでしょう。" },
    { en: "future", jp: "未来", enSent: "Think about your future.", jpSent: "あなたの未来について考えなさい。" },
    { en: "garbage", jp: "ゴミ", enSent: "Throw away the garbage.", jpSent: "ゴミを捨ててください。" },
    { en: "generation", jp: "世代", enSent: "We are the new generation.", jpSent: "私たちは新しい世代です。" },
    { en: "goal", jp: "目標", enSent: "My goal is to be a doctor.", jpSent: "私の目標は医者になることです。" },
    { en: "government", jp: "政府", enSent: "The government made a new law.", jpSent: "政府は新しい法律を作りました。" },
    { en: "guest", jp: "客", enSent: "We have a guest today.", jpSent: "今日はお客様がいます。" },
    { en: "habit", jp: "習慣", enSent: "I have a good habit.", jpSent: "私には良い習慣があります。" },
    { en: "health", jp: "健康", enSent: "Health is better than wealth.", jpSent: "健康は富に勝ります。" },
    { en: "heart", jp: "心 / 心臓", enSent: "He has a kind heart.", jpSent: "彼は優しい心を持っています。" },
    { en: "heat", jp: "熱", enSent: "I can't stand the heat.", jpSent: "この熱さに耐えられません。" },
    { en: "history", jp: "歴史", enSent: "I study Japanese history.", jpSent: "私は日本の歴史を勉強します。" },
    { en: "hobby", jp: "趣味", enSent: "My hobby is reading.", jpSent: "私の趣味は読書です。" },
    { en: "hole", jp: "穴", enSent: "There is a hole in my sock.", jpSent: "靴下に穴が開いています。" },
    { en: "holiday", jp: "休日", enSent: "Tomorrow is a holiday.", jpSent: "明日は休日です。" },
    { en: "human", jp: "人間", enSent: "We are human beings.", jpSent: "私たちは人間です。" },
    { en: "idea", jp: "考え", enSent: "I have a good idea.", jpSent: "私には良い考えがあります。" },
    { en: "image", jp: "画像 / 印象", enSent: "I have a good image of him.", jpSent: "彼には良い印象を持っています。" },
    { en: "importance", jp: "重要性", enSent: "I know the importance of study.", jpSent: "私は勉強の重要性を知っています。" },
    { en: "impression", jp: "印象", enSent: "First impression is important.", jpSent: "第一印象は重要です。" },
    { en: "individual", jp: "個人", enSent: "Every individual is different.", jpSent: "すべての個人は違います。" },
    { en: "industry", jp: "産業", enSent: "The car industry is big.", jpSent: "自動車産業は大きいです。" },
    { en: "influence", jp: "影響", enSent: "He has a big influence.", jpSent: "彼には大きな影響力があります。" },
    { en: "information", jp: "情報", enSent: "I need more information.", jpSent: "もっと情報が必要です。" },
    { en: "insect", jp: "昆虫", enSent: "I don't like insects.", jpSent: "私は昆虫が好きではありません。" },
    { en: "instance", jp: "例", enSent: "For instance, I like dogs.", jpSent: "例えば、私は犬が好きです。" },
    { en: "instrument", jp: "楽器 / 道具", enSent: "Can you play an instrument?", jpSent: "何か楽器を演奏できますか？" },
    { en: "interest", jp: "興味", enSent: "I have an interest in art.", jpSent: "私は芸術に興味があります。" },
    { en: "interview", jp: "面接", enSent: "I have a job interview.", jpSent: "私は仕事の面接があります。" },
    { en: "island", jp: "島", enSent: "Japan is an island country.", jpSent: "日本は島国です。" },
    { en: "issue", jp: "問題", enSent: "It is a big issue.", jpSent: "それは大きな問題です。" },
    { en: "item", jp: "品目 / 項目", enSent: "Choose one item.", jpSent: "一つの品目を選んでください。" },
    { en: "journey", jp: "旅", enSent: "It was a long journey.", jpSent: "それは長い旅でした。" },
    { en: "joy", jp: "喜び", enSent: "I jumped for joy.", jpSent: "私は喜びで飛び上がりました。" },
    { en: "judge", jp: "裁判官 / 審査員", enSent: "He is a fair judge.", jpSent: "彼は公平な裁判官です。" },
    { en: "knowledge", jp: "知識", enSent: "Knowledge is power.", jpSent: "知識は力なり。" },
    { en: "lack", jp: "不足", enSent: "We have a lack of water.", jpSent: "私たちは水不足です。" },
    { en: "language", jp: "言語", enSent: "English is a useful language.", jpSent: "英語は便利な言語です。" },
    { en: "law", jp: "法律", enSent: "You must obey the law.", jpSent: "法律に従わなければなりません。" },
    { en: "leader", jp: "指導者", enSent: "He is a good leader.", jpSent: "彼は良い指導者です。" },
    { en: "leaf", jp: "葉", enSent: "A leaf fell from the tree.", jpSent: "木から葉が落ちました。" },
    { en: "level", jp: "水準", enSent: "His English level is high.", jpSent: "彼の英語のレベルは高いです。" },
    { en: "library", jp: "図書館", enSent: "I study at the library.", jpSent: "私は図書館で勉強します。" },
    { en: "machine", jp: "機械", enSent: "This machine is broken.", jpSent: "この機械は壊れています。" },
    { en: "magazine", jp: "雑誌", enSent: "I bought a magazine.", jpSent: "私は雑誌を買いました。" },
    { en: "mail", jp: "郵便", enSent: "Is there any mail for me?", jpSent: "私に郵便はありますか？" },
    { en: "majority", jp: "過半数 / 大多数", enSent: "The majority voted yes.", jpSent: "過半数が賛成しました。" },
    { en: "manager", jp: "支配人 / 経営者", enSent: "He is the manager of the store.", jpSent: "彼がその店の店長です。" },
    { en: "manner", jp: "方法 / 態度", enSent: "His manner is very good.", jpSent: "彼の態度はとても良いです。" },
    { en: "market", jp: "市場", enSent: "I went to the market.", jpSent: "私は市場に行きました。" },
    { en: "master", jp: "主人 / 名人", enSent: "He is the master of this house.", jpSent: "彼がこの家の主人です。" },
    { en: "material", jp: "材料 / 資料", enSent: "This is a good material.", jpSent: "これは良い材料です。" },
    { en: "matter", jp: "問題 / 事柄", enSent: "It doesn't matter.", jpSent: "それは問題ではありません。" },
    { en: "mayor", jp: "市長", enSent: "He is the mayor of Tokyo.", jpSent: "彼は東京の市長です。" },
    { en: "meaning", jp: "意味", enSent: "What is the meaning of this word?", jpSent: "この単語の意味は何ですか？" },
    { en: "measure", jp: "対策 / 基準", enSent: "We must take measures.", jpSent: "私たちは対策を講じなければなりません。" },
    { en: "memory", jp: "記憶 / 思い出", enSent: "I have a good memory.", jpSent: "私には良い記憶力があります。" },
    { en: "message", jp: "伝言", enSent: "I will leave a message.", jpSent: "伝言を残します。" },
    { en: "method", jp: "方法", enSent: "This is a new method.", jpSent: "これは新しい方法です。" },
    { en: "middle", jp: "真ん中", enSent: "He is in the middle.", jpSent: "彼は真ん中にいます。" },
    { en: "mistake", jp: "間違い", enSent: "I made a mistake.", jpSent: "私は間違いを犯しました。" },
    { en: "model", jp: "模型 / 手本", enSent: "He made a plastic model.", jpSent: "彼はプラモデルを作りました。" },
    { en: "moment", jp: "瞬間", enSent: "Wait a moment, please.", jpSent: "少し待ってください。" },
    { en: "mood", jp: "気分", enSent: "I am in a good mood.", jpSent: "私は良い気分です。" },
    { en: "movement", jp: "動き / 運動", enSent: "Watch his hand movement.", jpSent: "彼の手の動きを見なさい。" },
    { en: "murder", jp: "殺人", enSent: "Murder is a terrible crime.", jpSent: "殺人はひどい犯罪です。" },
    { en: "mystery", jp: "謎", enSent: "It is a great mystery.", jpSent: "それは大きな謎です。" },
    { en: "nation", jp: "国家", enSent: "Japan is a peaceful nation.", jpSent: "日本は平和な国家です。" },
    { en: "nature", jp: "自然", enSent: "We must protect nature.", jpSent: "自然を守らなければなりません。" },
    { en: "neighbor", jp: "隣人", enSent: "My neighbor is very kind.", jpSent: "私の隣人はとても親切です。" },
    { en: "noise", jp: "騒音", enSent: "Don't make a noise.", jpSent: "音を立てないでください。" },
    { en: "notice", jp: "通知 / 掲示", enSent: "Read the notice on the wall.", jpSent: "壁の掲示を読みなさい。" },
    { en: "object", jp: "物体 / 目的", enSent: "What is this object?", jpSent: "この物体は何ですか？" },
    { en: "ocean", jp: "大洋", enSent: "The Pacific Ocean is very big.", jpSent: "太平洋はとても大きいです。" },
    { en: "office", jp: "事務所", enSent: "He is in the office.", jpSent: "彼は事務所にいます。" },
    { en: "officer", jp: "役人 / 警官", enSent: "He is a police officer.", jpSent: "彼は警察官です。" },
    { en: "opinion", jp: "意見", enSent: "What is your opinion?", jpSent: "あなたの意見は何ですか？" },
    { en: "opportunity", jp: "機会", enSent: "This is a great opportunity.", jpSent: "これは素晴らしい機会です。" },
    { en: "order", jp: "注文 / 順序", enSent: "May I take your order?", jpSent: "ご注文を伺ってもよろしいですか？" },
    { en: "owner", jp: "所有者", enSent: "Who is the owner of this car?", jpSent: "この車の持ち主は誰ですか？" },
    { en: "package", jp: "小包", enSent: "I received a package.", jpSent: "私は小包を受け取りました。" },
    { en: "pain", jp: "痛み", enSent: "I have a pain in my back.", jpSent: "背中に痛みがあります。" },
    { en: "pair", jp: "１対 / 一組", enSent: "I bought a pair of shoes.", jpSent: "私は靴を一足買いました。" },
    { en: "part", jp: "部分", enSent: "This is a part of the book.", jpSent: "これは本の一部です。" },
    { en: "passenger", jp: "乗客", enSent: "There are many passengers.", jpSent: "たくさんの乗客がいます。" },
    { en: "patient", jp: "患者", enSent: "The doctor sees the patient.", jpSent: "医者は患者を診ます。" },
    { en: "pattern", jp: "模様 / 様式", enSent: "I like this pattern.", jpSent: "私はこの模様が好きです。" },
    { en: "peace", jp: "平和", enSent: "We all want peace.", jpSent: "私たちはみんな平和を望んでいます。" },
    { en: "percentage", jp: "割合 / パーセント", enSent: "A small percentage of people.", jpSent: "少数の割合の人々。" },
    { en: "period", jp: "期間", enSent: "During this period, it rains.", jpSent: "この期間中、雨が降ります。" },
    { en: "person", jp: "人", enSent: "He is a nice person.", jpSent: "彼は良い人です。" },
    { en: "planet", jp: "惑星", enSent: "Earth is a planet.", jpSent: "地球は惑星です。" },
    { en: "plant", jp: "植物 / 工場", enSent: "Water the plant.", jpSent: "植物に水をあげてください。" },
    { en: "plastic", jp: "プラスチック", enSent: "This is made of plastic.", jpSent: "これはプラスチックでできています。" },
    { en: "pleasure", jp: "喜び", enSent: "It is my pleasure.", jpSent: "私の喜びです（どういたしまして）。" },
    { en: "plenty", jp: "豊富 / たくさん", enSent: "We have plenty of time.", jpSent: "私たちにはたっぷりの時間があります。" },
    { en: "pocket", jp: "ポケット", enSent: "I put it in my pocket.", jpSent: "私はそれをポケットに入れました。" },
    { en: "policy", jp: "政策 / 方針", enSent: "Honesty is the best policy.", jpSent: "正直は最善の策です。" },
    { en: "pollution", jp: "汚染", enSent: "Air pollution is bad.", jpSent: "大気汚染は悪いです。" },
    { en: "population", jp: "人口", enSent: "The population is growing.", jpSent: "人口が増えています。" },
    { en: "position", jp: "位置 / 立場", enSent: "What is your position?", jpSent: "あなたの立場は何ですか？" },
    { en: "power", jp: "力 / 権力", enSent: "Knowledge is power.", jpSent: "知識は力です。" },
    { en: "practice", jp: "練習 / 実行", enSent: "Practice makes perfect.", jpSent: "練習は完璧を作ります。" },
    { en: "president", jp: "大統領 / 社長", enSent: "He is the president.", jpSent: "彼は大統領です。" },
    { en: "pressure", jp: "圧力", enSent: "I feel a lot of pressure.", jpSent: "私は多くの圧力を感じます。" },
    { en: "price", jp: "価格", enSent: "The price is high.", jpSent: "価格が高いです。" },
    { en: "priest", jp: "聖職者", enSent: "He is a priest.", jpSent: "彼は神父です。" },
    { en: "prince", jp: "王子", enSent: "He is the prince of the country.", jpSent: "彼はその国の王子です。" },
    { en: "principle", jp: "原理 / 原則", enSent: "It is a basic principle.", jpSent: "それは基本原則です。" },
    { en: "prison", jp: "刑務所", enSent: "He was sent to prison.", jpSent: "彼は刑務所に送られました。" },
    { en: "prize", jp: "賞", enSent: "I won first prize.", jpSent: "私は一等賞をとりました。" },
    { en: "problem", jp: "問題", enSent: "No problem.", jpSent: "問題ありません。" },
    { en: "process", jp: "過程 / 工程", enSent: "It is a long process.", jpSent: "それは長い過程です。" },
    { en: "product", jp: "製品", enSent: "This is a new product.", jpSent: "これは新しい製品です。" },
    { en: "production", jp: "生産", enSent: "Car production increased.", jpSent: "車の生産が増えました。" },
    { en: "profit", jp: "利益", enSent: "We made a big profit.", jpSent: "私たちは大きな利益を出しました。" },
    { en: "program", jp: "番組 / 計画", enSent: "I like this TV program.", jpSent: "私はこのテレビ番組が好きです。" },
    { en: "progress", jp: "進歩", enSent: "You made good progress.", jpSent: "あなたは良い進歩をしました。" },
    { en: "project", jp: "計画 / プロジェクト", enSent: "This is our new project.", jpSent: "これは私たちの新しいプロジェクトです。" },
    { en: "promise", jp: "約束", enSent: "Keep your promise.", jpSent: "約束を守りなさい。" },
    { en: "proof", jp: "証拠", enSent: "Do you have any proof?", jpSent: "何か証拠はありますか？" },
    { en: "property", jp: "財産", enSent: "This is my private property.", jpSent: "これは私の私有財産です。" },
    { en: "proportion", jp: "割合 / 比率", enSent: "A large proportion of students.", jpSent: "大部分の学生。" },
    { en: "proposal", jp: "提案", enSent: "I accept your proposal.", jpSent: "あなたの提案を受け入れます。" },
    { en: "prospect", jp: "見込み", enSent: "There is no prospect of success.", jpSent: "成功の見込みはありません。" },
    { en: "protection", jp: "保護", enSent: "Environmental protection is needed.", jpSent: "環境保護が必要です。" },
    { en: "purpose", jp: "目的", enSent: "What is your purpose?", jpSent: "あなたの目的は何ですか？" },
    { en: "quality", jp: "質", enSent: "The quality is very good.", jpSent: "質はとても良いです。" },
    { en: "quantity", jp: "量", enSent: "Quantity is less important than quality.", jpSent: "量は質より重要ではありません。" },
    { en: "quarter", jp: "４分の１", enSent: "Cut it into quarters.", jpSent: "それを4分の1に切ってください。" },
    { en: "race", jp: "競争 / 人種", enSent: "He won the race.", jpSent: "彼はレースに勝ちました。" },
    { en: "rate", jp: "割合 / 速度", enSent: "The birth rate is falling.", jpSent: "出生率が落ちています。" },
    { en: "reality", jp: "現実", enSent: "Face the reality.", jpSent: "現実に直面しなさい。" },
    { en: "reason", jp: "理由", enSent: "Give me a reason.", jpSent: "理由を教えてください。" },
    { en: "record", jp: "記録", enSent: "He broke the world record.", jpSent: "彼は世界記録を破りました。" },
    { en: "relation", jp: "関係", enSent: "What is your relation to him?", jpSent: "彼との関係は何ですか？" },
    { en: "relationship", jp: "関係", enSent: "We have a good relationship.", jpSent: "私たちは良い関係を築いています。" },
    { en: "religion", jp: "宗教", enSent: "What is your religion?", jpSent: "あなたの宗教は何ですか？" },
    { en: "remark", jp: "意見 / 注目", enSent: "He made a rude remark.", jpSent: "彼は失礼な意見を言いました。" },
    { en: "reply", jp: "返事", enSent: "I am waiting for your reply.", jpSent: "あなたの返事を待っています。" },
    { en: "report", jp: "報告 / 報告書", enSent: "Read the report.", jpSent: "報告書を読んでください。" },
    { en: "request", jp: "要請 / 頼み", enSent: "I have a request.", jpSent: "頼みがあります。" },
    { en: "respect", jp: "尊敬 / 点", enSent: "I have deep respect for him.", jpSent: "私は彼に深い尊敬を抱いています。" }

];
