// words.js - 英検2級 頻出単語・熟語データ (Top 80 核心精选第一批)
// 数据来源：旺文社《でる順パス単 英検2級》、《予想問題ドリル》

const vocabData = [
    // =============== 【1. 超高頻出動詞】 ===============
    { en: "Provide", jp: "提供する", enSent: "They provide food for us.", jpSent: "彼らは私たちに食べ物を提供します。" },
    { en: "Require", jp: "必要とする", enSent: "This job requires English.", jpSent: "この仕事は英語を必要とします。" },
    { en: "Encourage", jp: "励ます / 促す", enSent: "My mother encourages me.", jpSent: "母は私を励ましてくれます。" },
    { en: "Preserve", jp: "保護する / 保存する", enSent: "We must preserve nature.", jpSent: "私たちは自然を保護しなければなりません。" },
    { en: "Determine", jp: "決定する", enSent: "I determined the date.", jpSent: "私は日付を決定しました。" },
    { en: "Improve", jp: "改善する", enSent: "I want to improve my English.", jpSent: "英語を上達させたいです。" },
    { en: "Recognize", jp: "認識する / 気づく", enSent: "I recognized her face.", jpSent: "彼女の顔に気づきました。" },
    { en: "Apologize", jp: "謝る", enSent: "He apologized to me.", jpSent: "彼は私に謝りました。" },
    { en: "Prevent", jp: "防ぐ / 妨げる", enSent: "This medicine prevents colds.", jpSent: "この薬は風邪を防ぎます。" },
    { en: "Reduce", jp: "減らす", enSent: "We must reduce garbage.", jpSent: "私たちはゴミを減らさなければなりません。" },
    { en: "Produce", jp: "生産する", enSent: "This factory produces cars.", jpSent: "この工場は車を生産しています。" },
    { en: "Accept", jp: "受け入れる", enSent: "I accept your gift.", jpSent: "あなたの贈り物を受け入れます。" },
    { en: "Replace", jp: "取り替える", enSent: "I replaced the battery.", jpSent: "私は電池を取り替えました。" },
    { en: "Mention", jp: "言及する", enSent: "He mentioned your name.", jpSent: "彼はあなたの名前を言いました。" },
    { en: "Complain", jp: "不平を言う", enSent: "Don't complain about food.", jpSent: "食べ物の文句を言わないで。" },
    { en: "Achieve", jp: "達成する", enSent: "He achieved his goal.", jpSent: "彼は目標を達成しました。" },
    { en: "Establish", jp: "設立する", enSent: "They established a new school.", jpSent: "彼らは新しい学校を設立しました。" },
    { en: "Represent", jp: "代表する", enSent: "He represents our team.", jpSent: "彼は私たちのチームを代表しています。" },
    { en: "Suggest", jp: "提案する", enSent: "I suggest a new plan.", jpSent: "新しい計画を提案します。" },
    { en: "Compare", jp: "比較する", enSent: "Compare the two pictures.", jpSent: "2つの写真を比較してください。" },

    // =============== 【2. 超高頻出名詞】 ===============
    { en: "Environment", jp: "環境", enSent: "We protect the environment.", jpSent: "私たちは環境を守ります。" },
    { en: "Candidate", jp: "候補者", enSent: "She is a good candidate.", jpSent: "彼女は良い候補者です。" },
    { en: "Pollution", jp: "汚染", enSent: "Air pollution is bad.", jpSent: "大気汚染は悪いです。" },
    { en: "Decade", jp: "10年間", enSent: "It took a decade.", jpSent: "10年かかりました。" },
    { en: "Disease", jp: "病気", enSent: "He caught a bad disease.", jpSent: "彼は重い病気にかかりました。" },
    { en: "Evidence", jp: "証拠", enSent: "There is no evidence.", jpSent: "証拠がありません。" },
    { en: "Resource", jp: "資源", enSent: "Water is an important resource.", jpSent: "水は重要な資源です。" },
    { en: "Method", jp: "方法", enSent: "This is a new method.", jpSent: "これは新しい方法です。" },
    { en: "Benefit", jp: "利益 / 利点", enSent: "Reading has many benefits.", jpSent: "読書には多くの利点があります。" },
    { en: "Influence", jp: "影響", enSent: "TV has a big influence.", jpSent: "テレビは大きな影響を与えます。" },
    { en: "Opportunity", jp: "機会 / チャンス", enSent: "This is a great opportunity.", jpSent: "これは素晴らしいチャンスです。" },
    { en: "Resident", jp: "住民", enSent: "He is a resident of Tokyo.", jpSent: "彼は東京の住民です。" },
    { en: "Equipment", jp: "機器 / 設備", enSent: "We need new equipment.", jpSent: "新しい設備が必要です。" },
    { en: "Progress", jp: "進歩 / 前進", enSent: "You made good progress.", jpSent: "あなたは良い進歩をしました。" },
    { en: "Quality", jp: "質 / 品質", enSent: "This bag is high quality.", jpSent: "このバッグは高品質です。" },
    { en: "Passenger", jp: "乗客", enSent: "The train has many passengers.", jpSent: "その電車には多くの乗客がいます。" },
    { en: "Vehicle", jp: "乗り物", enSent: "Cars are vehicles.", jpSent: "車は乗り物です。" },
    { en: "Community", jp: "地域社会", enSent: "I love my community.", jpSent: "私は自分の地域社会が好きです。" },
    { en: "Temperature", jp: "温度 / 気温", enSent: "The temperature is high.", jpSent: "気温が高いです。" },
    { en: "Customer", jp: "客 / 顧客", enSent: "The shop has many customers.", jpSent: "その店にはたくさんの客がいます。" },

    // =============== 【3. 超高頻出形容詞・副詞】 ===============
    { en: "Artificial", jp: "人工の", enSent: "This is artificial light.", jpSent: "これは人工の光です。" },
    { en: "Patient", jp: "忍耐強い", enSent: "Be patient with children.", jpSent: "子供には忍耐強く接しなさい。" },
    { en: "Significant", jp: "重要な / かなりの", enSent: "It is a significant change.", jpSent: "それは重要な変化です。" },
    { en: "Available", jp: "利用できる / 手に入る", enSent: "Is this seat available?", jpSent: "この席は利用できますか？" },
    { en: "Familiar", jp: "なじみのある", enSent: "I am familiar with this song.", jpSent: "私はこの歌をよく知っています。" },
    { en: "Frequent", jp: "頻繁な", enSent: "He makes frequent visits.", jpSent: "彼は頻繁に訪問します。" },
    { en: "Independent", jp: "独立した", enSent: "He is an independent man.", jpSent: "彼は独立した男性です。" },
    { en: "Proper", jp: "適切な", enSent: "Wear proper clothes.", jpSent: "適切な服を着なさい。" },
    { en: "Recent", jp: "最近の", enSent: "This is a recent photo.", jpSent: "これは最近の写真です。" },
    { en: "Severe", jp: "深刻な / 厳しい", enSent: "The weather is severe.", jpSent: "天気が厳しいです。" },
    { en: "Valuable", jp: "価値のある", enSent: "Time is valuable.", jpSent: "時間は価値があります。" },
    { en: "Traditional", jp: "伝統的な", enSent: "This is a traditional dance.", jpSent: "これは伝統的なダンスです。" },
    { en: "Specific", jp: "特定の / 具体的な", enSent: "Do you have a specific plan?", jpSent: "具体的な計画はありますか？" },
    { en: "Essential", jp: "不可欠な", enSent: "Water is essential for life.", jpSent: "水は生命に不可欠です。" },
    { en: "Exactly", jp: "正確に / ぴったり", enSent: "That is exactly right.", jpSent: "それはまったくその通りです。" },
    { en: "Gradually", jp: "徐々に", enSent: "It gets warmer gradually.", jpSent: "徐々に暖かくなります。" },

    // =============== 【4. 英検2級 必修熟語 (超重要！阅读填空常考)】 ===============
    { en: "Rely on", jp: "～に頼る", enSent: "Don't rely on him.", jpSent: "彼に頼ってはいけません。" },
    { en: "Take place", jp: "開催される / 起こる", enSent: "The event will take place tomorrow.", jpSent: "そのイベントは明日開催されます。" },
    { en: "Figure out", jp: "～を理解する / 解決する", enSent: "I figured out the problem.", jpSent: "私は問題を解決しました。" },
    { en: "Look forward to", jp: "～を楽しみにする", enSent: "I look forward to the party.", jpSent: "パーティーを楽しみにしています。" },
    { en: "Carry out", jp: "～を実行する", enSent: "We carried out the plan.", jpSent: "私たちは計画を実行しました。" },
    { en: "Depend on", jp: "～次第である / ～に依存する", enSent: "It depends on the weather.", jpSent: "それは天気次第です。" },
    { en: "In spite of", jp: "～にもかかわらず", enSent: "We went in spite of the rain.", jpSent: "雨にもかかわらず私たちは行きました。" },
    { en: "Point out", jp: "～を指摘する", enSent: "She pointed out my mistake.", jpSent: "彼女は私の間違いを指摘しました。" },
    { en: "Make up one's mind", jp: "決心する", enSent: "I made up my mind.", jpSent: "私は決心しました。" },
    { en: "Run out of", jp: "～を使い果たす", enSent: "We ran out of gas.", jpSent: "私たちはガソリンを使い果たしました。" },
    { en: "Take advantage of", jp: "～を利用する", enSent: "Take advantage of this chance.", jpSent: "このチャンスを利用しなさい。" },
    { en: "Be accustomed to", jp: "～に慣れている", enSent: "I am accustomed to getting up early.", jpSent: "私は早起きに慣れています。" },
    { en: "Consist of", jp: "～から成り立つ", enSent: "The team consists of five people.", jpSent: "チームは5人で成り立っています。" },
    { en: "Keep in touch", jp: "連絡を取り合う", enSent: "Let's keep in touch.", jpSent: "連絡を取り合いましょう。" },
    { en: "Make sense", jp: "意味をなす / 理にかなう", enSent: "That makes sense.", jpSent: "それは理にかなっています（なるほど）。" },
    { en: "Participate in", jp: "～に参加する", enSent: "He participated in the game.", jpSent: "彼はそのゲームに参加しました。" },
    { en: "Play a role", jp: "役割を果たす", enSent: "She plays an important role.", jpSent: "彼女は重要な役割を果たしています。" },
    { en: "Result in", jp: "～という結果になる", enSent: "The storm resulted in an accident.", jpSent: "嵐は事故という結果になりました。" },
    { en: "Stand for", jp: "～を表す / 象徴する", enSent: "USA stands for United States of America.", jpSent: "USAはアメリカ合衆国を表します。" },
    { en: "Tend to", jp: "～する傾向がある", enSent: "People tend to forget.", jpSent: "人は忘れる傾向があります。" },
    { en: "As long as", jp: "～する限り", enSent: "You can stay as long as you want.", jpSent: "好きなだけここにいていいですよ。" },
    { en: "Come across", jp: "～に偶然出会う", enSent: "I came across an old friend.", jpSent: "古い友人に偶然会いました。" },
    { en: "Deal with", jp: "～に対処する / 扱う", enSent: "How do you deal with stress?", jpSent: "ストレスにどう対処しますか？" },
    { en: "Focus on", jp: "～に集中する", enSent: "Please focus on your study.", jpSent: "勉強に集中してください。" }
];
